### ISSUE TITLE
[BUG] UnimplementedMethodException: ApexStringValue:substringAfterLast

### ISSUE THREAD

**Issue by efwalter** [forcedotcom/sfdx-scanner#1003]
**Describe the bug**
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnimplementedMethodException: ApexStringValue:substringAfterLast, vertex=MethodCallExpressionVertex{fullMethodName=sBillNumber.substringAfterLast, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[sBillNumber], BeginLine=343, DefiningType_CaseSafe=kwleg_lwcmethods, LastChild=false, DefiningType=KWLEG_LWCMethods, EndLine=343, Name_CaseSafe=sbillnumber, childIdx=0, BeginColumn=22, ReferenceType=METHOD, Name=sBillNumber}}}, chainedNames=[sBillNumber], properties={FirstChild=false, FullMethodName=sBillNumber.substringAfterLast, BeginLine=343, FullMethodName_CaseSafe=sbillnumber.substringafterlast, DefiningType_CaseSafe=kwleg_lwcmethods, LastChild=true, DefiningType=KWLEG_LWCMethods, EndLine=343, MethodName_CaseSafe=substringafterlast, childIdx=1, BeginColumn=34, MethodName=substringAfterLast}}: com.salesforce.graph.symbols.apex.ApexStringValue.apply(ApexStringValue.java:394);com.salesforce.graph.symbols.PathScopeVisitor.handleApexValueMethod(PathScopeVisitor.java:1462);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1222);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:749);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:77);com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:705)

```
 @AuraEnabled(cacheable=true)
    public static String getBillDetail(String sBillNumber, String sState, String sSession, String sCongress) {

        String sBillId = sBillNumber;
        if (sBillNumber.contains('-') ) {
            sBillId= sBillNumber.substringAfterLast('-');
        }
        .... do a callout

```
**To Reproduce**
Run the scanner on the method. the error will be thrown because the method substringAfterLast()

**Desktop (please complete the following information):**
 - Mac OS Ventura 13.1
 - @salesforce/sfdx-scanner 3.10.0

**Comment by efwalter** [comment]
Is there a way to make the scanner to ignore that line?

**Comment by rmohan20** [comment]
Hi @efwalter - thanks for reporting the issue. 
We'll work on fixing this.

To ignore the issue, you could add an [engine directive](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/working-with-sfge/#add-engine-directives). In your case, you could add the engine directive on `getBillDetail(...)`.

```
/* sfge-disable-stack ApexFlsViolationRule */
```

**Comment by efwalter** [comment]
Thank you @rmohan20, but the scanner still throws the error no matter if the flag is there or not

**Comment by jfeingold35** [comment]
@efwalter , we've merged a fix for this issue, and that should go out with the 3.13.0 release currently scheduled for June 6. Stay tuned.
