### ISSUE TITLE
[BUG] Operator is not handled for conditional clause: -:

### ISSUE THREAD

**Issue by efwalter** [forcedotcom/sfdx-scanner#1008]
**Describe the bug**
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: TodoException: Operator is not handled for conditional clause: -: com.salesforce.rules.fls.apex.operations.NegationContainmentUtil.getContainedNegationLevels(NegationContainmentUtil.java:61);com.salesforce.rules.fls.apex.operations.NegationContainmentUtil.getContainedNegationLevels(NegationContainmentUtil.java:83);com.salesforce.rules.fls.apex.operations.NegationContainmentUtil.getContainedNegationLevels(NegationContainmentUtil.java:54);com.salesforce.rules.fls.apex.operations.NegationContainmentUtil.includesNonNegatedClause(NegationContainmentUtil.java:28);com.salesforce.rules.fls.apex.BooleanStateDetectorVisitor.containsPotentiallyValidCheck(BooleanStateDetectorVisitor.java:22);com.salesforce.rules.fls.apex.AbstractFlsVisitor.afterVisit(AbstractFlsVisitor.java:63)

**Desktop (please complete the following information):**
 - Mac OS Ventura 13.1
 - @salesforce/sfdx-scanner 3.10.0

**Comment by efwalter** [comment]
@rmohan20 thank you, I'm trying to find the code where it exists, but not successfully, I think this other error here is related:

Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: TodoException: Operator is not handled yet: -: com.salesforce.rules.fls.apex.BooleanStateDetectorVisitor.isPrefixNegated(BooleanStateDetectorVisitor.java:129);com.salesforce.rules.fls.apex.BooleanStateDetectorVisitor.getContainedNegationLevels(BooleanStateDetectorVisitor.java:104);com.salesforce.rules.fls.apex.BooleanStateDetectorVisitor.getContainedNegationLevels(BooleanStateDetectorVisitor.java:116);com.salesforce.rules.fls.apex.BooleanStateDetectorVisitor.getContainedNegationLevels(BooleanStateDetectorVisitor.java:102);com.salesforce.rules.fls.apex.BooleanStateDetectorVisitor.includesNonNegatedClause(BooleanStateDetectorVisitor.java:65);com.salesforce.rules.fls.apex.BooleanStateDetectorVisitor.containsPotentiallyValidCheck(BooleanStateDetectorVisitor.java:51)

**Comment by rmohan20** [comment]
@efwalter Thanks for checking. I'm imagining your code has an IF condition or an ELSE IF somewhere that takes `-` in its conditional. We'll attempt to repro this as well when we pick up this issue.
