### ISSUE TITLE
[Bug] How to Install the plugin link is not working

### ISSUE THREAD

**Issue by rdudeja1133** [forcedotcom/sfdx-scanner#1011]
How to Install the plugin link is not working. Please update the instructions so I can set it up for my org

**Comment by rdudeja1133** [comment]
Link on the github is not working. Link you provided is working

Regards
RD



________________________________

**Comment by johnbelosf** [comment]
Got it thank you @rdudeja1133! I'll raise this as a bug

**Comment by jfeingold35** [comment]
We've just pushed a fix for this.
