### ISSUE TITLE
[BUG] FLS Violation not being found

### ISSUE THREAD

**Issue by mmoyaferrer** [forcedotcom/sfdx-scanner#1017]
**Describe the bug**
I want to find FLS violations inside of a folder in my repository, using DFA command, however, it does not find them.

**To Reproduce**
- Create a `temp` folder inside of the root repository
- Create a salesforce project inside of that `temp` folder
- Create an apex class with FLS violations on purpose within the above project
- Run DFA as  `sfdx scanner:run:dfa --target temp/force-app/Sample --projectdir temp/force-app/Sample/`

**Expected behavior**
I expect it to find the introduced FLS violation

**Screenshots**
![Screenshot_2023-03-14_at_10_38_34](https://user-images.githubusercontent.com/15876612/224960194-0038ec00-5e82-4683-b0e6-af69b2cadfb3.png)

**Desktop (please complete the following information):**
 - OS: Macos Ventura 3.0.1
 - Scanner Version sfdx-cli/7.187.1

**Additional context**
N/A

"Workaround": Have you found any ways to sidestep the problem
Using PMD which detects it

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".
Not business-stopping

**Comment by jfeingold35** [comment]
From context, it looks like this code is called in the context of a trigger. Is that correct? As per our [documentation](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/working-with-sfge/#limitations-of-salesforce-graph-engine), we don't currently support triggers, though this is an item on our backlog.

**Comment by jfeingold35** [comment]
@mmoyaferrer , to provide a little bit more information, DFA only considers [certain things](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/rules/#apexflsviolationrule) to be code entry points, and this doesn't fall into any of those criteria. For example, you could annotate the method as `@AuraEnabled`, and that would cause it to be included.

**Comment by mmoyaferrer** [comment]
> 

I understand now @jfeingold35 I was not aware of those, I will look better into the docs next time. Thank you for the clarification.
