### ISSUE TITLE
Unable to install sfdx-scanner plugin

### ISSUE THREAD

**Issue by ronika-das** [forcedotcom/sfdx-scanner#1019]
Hi team
**Describe the bug**
I am not able to install the plugin on my CI/CD pipelines on gitlab. It gets stuck on polling

**To Reproduce**
I am running the below commands:
$ npm config set strict-ssl=false
$ sfdx plugins:install @salesforce/sfdx-scanner

I am setting the ssl to false as I am trying to install the plugin behind company firewall.
We want to try pmd scanner for our teaml
After the second command, it gets stuck at polling

**Expected behavior**
The plugin to be installed and 
**Screenshots**
<img width="311" alt="image" src="https://user-images.githubusercontent.com/32714099/225312944-75cae204-c1bf-403b-968f-67576ff6a5f0.png">

**Desktop (please complete the following information):**
We are using Gitlab to execute the commands.
The docker image has node, salesforce cli and java.
Normal sfdx commands work fine.

**Additional context**
Before setting the ssl to False, I would get this error
"npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY"

**Workaround**: Have you found any ways to sidestep the problem?
Not yet

**Urgency**: How severe is this problem? "Business stopping" vs "Not business-stopping".
Not business-stopping. We want to try to use this plugin and see if it can be an alternative to other scanning tools.

**Comment by rmohan20** [comment]
Hi @ronika-das - thanks for letting us know.
Can you check and tell us what versions of Node and Salesforce CLI your docker image has?
```
sfdx --version
```
Also, can you update to the latest and retry?

**Comment by ronika-das** [comment]
Hi @rmohan20 
Yes sure

Node version -> v14.21.1
Salesforce CLI version -> sfdx-cli/7.171.0
I tried updating the cli to the latest version. After that, the plugin install command is running for a long time. It has been more than 10 mins.
Below image is my attempt
<img width="607" alt="image" src="https://user-images.githubusercontent.com/32714099/225720632-03d65e26-0e47-4183-b8ab-56ab441f53d7.png">



May I know if there is any alternative (maybe npm) command for installing the plugin?

**Comment by rmohan20** [comment]
Thanks @ronika-das. I'm unable to repro your issue in my local. As you mention, sounds like an env-related issue.
Salesforce CLI has added a new feature to auto-detect and install plugins. Wonder if this may work better for you.

Can you directly execute:
```
sfdx scanner:rule:list
```
If it fails with an "Attempted to resolve unregistered dependency token: 'RuleManager'", rerun the same command and this should complete the installation.

Let us know how this works for you.

**Comment by rmohan20** [comment]
Also, if you're simply trying out the tool, might be easier to directly install it on your local machine. This way, you can play around with the various options against your codebase to see how you want to use it.

**Comment by mitchspano** [comment]
I am experiencing the same issue after a fresh install of sfdx CLI

```shell
# remove old installation
sudo npm uninstall sfdx-cli --global
sudo rm -rf /usr/local/sfdx
sudo rm -rf /usr/local/lib/sfdx
sudo rm -rf /usr/local/bin/sfdx
sudo rm -rf ~/.local/share/sfdx ~/.config/sfdx ~/.cache/sfdx
sudo rm -rf ~/Library/Caches/sfdx
sudo rm -rf /usr/local/sf
sudo rm -rf /usr/local/bin/sf

# install fresh
sudo npm i sfdx-cli --global

# verify installation
sfdx -v
sfdx-cli/7.192.2 darwin-x64 node-v16.13.1

# attempt to install scanner plugin
sfdx plugins:install @salesforce/sfdx-scanner
# gets stuck here
Polling for new version(s) to become available on npm... ⣟ attempt: 203 of 300
```

**Comment by ronika-das** [comment]
@rmohan20 For me personally, it is loading on the local system.
However we want to try it on the CI/CD pipelines on Gitlab and wanted to be proactive :D

Here is my attempt at running

sfdx scanner:rule:list

It is not progressing and it has been more than 10mins
<img width="614" alt="image" src="https://user-images.githubusercontent.com/32714099/226287163-b24d95aa-e5be-40ce-9532-88ed5800763d.png">


Thanks!

**Comment by rmohan20** [comment]
@ronika-das @mitchspano Can either of you try out the troubleshooting steps that @iowillhoit has recommended above and let us know your findings, please?

**Comment by ronika-das** [comment]
Hi all @rmohan20  @iowillhoit 

Very strange, Today I am able to install and plugin and run the scanner:run command. Here is a look at the time.
Seems something worked on its own haha :D
I am going to try it out more and check

<img width="612" alt="image" src="https://user-images.githubusercontent.com/32714099/227128852-13eefaa9-770e-435a-8ce4-e979b5550975.png">



I was also able to install the mentioned plugins by running the below commands
- npm config set strict-ssl=false
- sfdx plugins:install @salesforce/plugin-release-management
- echo 'y' | sfdx plugins:install @cristiand391/sf-plugin-api

**Comment by ronika-das** [comment]
FYI, I did not do additional changes from side. Just reran the same set of commands as in first comment

$ npm config set strict-ssl=false
$ sfdx plugins:install @salesforce/sfdx-scanner
$ sfdx scanner:rule:list
$ sfdx scanner:run --target "**/default/**" --format "csv" --outfile "build/pathToFile.csv"

**Comment by mitchspano** [comment]
I was able to install using `sudo`

**Comment by rmohan20** [comment]
@ronika-das @mitchspano Thanks for reporting back. Still unclear what caused the issue.
Will close this for now since there doesn't seem to be any action needed at the moment.
