### ISSUE TITLE
[BUG] DFA - FLS/OLS checks violations reported when querying against relationship name

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/sfdx-scanner#1027]
**Describe the bug**
If you query FLS against an entity but then use the relationship name in the SOQL query, a violation is reported by the DFA scan

**To Reproduce**

Example code:

```
@AuraEnabled(cacheable=false)
public static List<Base_Object__c> getMyObjects(Id lastId) {
    if (!Schema.SObjectType.Base_Object__c.isAccessible()
        || !Schema.SObjectType.Base_Object__c.fields.Id.isAccessible()
        || !Schema.SObjectType.Base_Object__c.fields.Some_Field__c.isAccessible()
        || !Schema.SObjectType.Child_Object__c.isAccessible()
        || !Schema.SObjectType.Child_Object__c.fields.Id.isAccessible()
        || !Schema.SObjectType.Child_Object__c.fields.Target__c.isAccessible()
        || !Schema.SObjectType.Child_Object__c.fields.Base_Object__c.isAccessible()) {
        throw new SecurityException('You do not have access to necessary objects.');
    }

    if (lastId == null) {
        return [SELECT Id,Some_Field__c,
                (SELECT Id, Target__c, Base_Object__c FROM Child_Objects__r)
                FROM Base_Object__c
                WHERE Some_Field__c = 'Whatever'];
    }
    
    return [SELECT Id,Some_Field__c,
            (SELECT Id, Target__c, Base_Object__c FROM Child_Objects__r)
            FROM Base_Object__c
            AND Id > : lastId
            ORDER BY Id LIMIT 50000];
}
```

**Reported error**
> FLS validation is missing for [READ] operation on [Child_Objects__r] with field(s) [Target__c,Base_Object__c]. Confirm that the objects and fields involved in these segments have FLS checks: [Child_Objects__r].

**Expected behavior**
The engine of the DFA does not report a violation as there is none

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Scanner Version [e.g. 22] 3.0.0

**Additional context**

"Workaround": Have you found any ways to sidestep the problem? Not yet

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".

If we are forced to rely on these scans for the security review submissions will be business stopping

**Comment by rmohan20** [comment]
@az-oolloow Graph Engine does not have the capability to evaluate `__r` type of objects. To make sure that related vulnerabilities don't get overlooked, it creates a violation always, which is why you see this violation. Once you manually make sure that this isn't a vulnerability, please feel free to add an engine directive to skip checking this query.
I'm closing this issue, but please reopen it for any follow-up questions. Thanks.
