### ISSUE TITLE
INTERNAL ERROR: Unexpected error occurred while cataloging rules

### ISSUE THREAD

**Issue by Kamilsz** [forcedotcom/sfdx-scanner#1033]
**Describe the bug**
after removing a custom rule receive the following error when trying to run, add, remove or list rules. Updating, re-installing the scanner did not help

**Reported error:**
_INTERNAL ERROR: Unexpected error occurred while cataloging rules: Cannot invoke "java.net.URL.getPath()" because "resource" is null. Please log an issue with us at github.com/forcedotcom/sfdx-scanner._

**To Reproduce:**
create a custom rule and add it to the list of rules with sfdx scanner:rule:add 
Rule path: <rule folder>/category/xml/customRule.xml

**Expected behaviour**
scanner to run normally after removing custom rule

**Desktop (please complete the following information):**
macOS: 13.2.1 (22D68)
java version "20" 2023-03-21
Java(TM) SE Runtime Environment (build 20+36-2344)
Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)
Scanner:  v3.10.0

**the custom rule that was added then removed:**

<img width="553" alt="image" src="https://user-images.githubusercontent.com/3039025/227425480-53333981-2494-4956-808f-bcd64969f31a.png">

**Comment by jfeingold35** [comment]
@Kamilsz , could you clarify what you mean by "remove" the rule? Did you simply delete the file, or did you use `scanner:rule:remove`?

**Comment by Kamilsz** [comment]
Hi,

I used scanner:rule:remove

**Comment by jfeingold35** [comment]
Thanks for clarifying. I'll see if I can reproduce this. My understanding of the steps to reproduce  is that they are (1) add the rule, (2) remove the rule via `scanner:rule:remove`, and then (3) observe that everything is broken. Is that correct? In the meantime, you should be able to unblock yourself by manually editing the `~/.sfdx-scanner/CustomPaths.json` file and removing the offending rule.

**Comment by Kamilsz** [comment]
Yes, those are the steps I took. Not sure if that matters, but my rule was for XML and it was in the folder tree I mentioned above.

**Comment by jfeingold35** [comment]
@Kamilsz , I'm unable to reproduce this locally. A few notes, though:
1. Can you verify that you were able to unblock yourself by manually editing the `CustomPaths.json` file as described above?
2. After unblocking yourself, are you able to re-block yourself by using `scanner:rule:add` to add the rule and then `scanner:rule:remove` to remove it?

**Comment by Kamilsz** [comment]
@jfeingold35 I think my rule might be the issue here.
1. Yes, when I remove the file from the `CustomPaths.json` manually, I am unstuck.
2. Yes, as soon as I add my rule, whether by manually editing `CustomPaths.json` or by using `scanner:rule:ad`d I am stuck again.

**Comment by jfeingold35** [comment]
Dumb question: Is your rule wrapped in the `<ruleset>` tag?

**Comment by Kamilsz** [comment]
That actually solved it! <ruleset> tag was missing. Thank you!
