### ISSUE TITLE
[BUG] Graph Engine reached the path expansion upper limit (6688).. The analysis preemptively stopped running on this path to prevent an OutOfMemory error. Rerun Graph Engine targeting this entry method with a larger heap space.

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/sfdx-scanner#1041]
**Describe the bug**

Some of the entry paths of the DFA command fail with

```
Graph Engine reached the path expansion upper limit (6688).. The analysis preemptively stopped running on this path to prevent an OutOfMemory error. Rerun Graph Engine targeting this entry method with a larger heap space.
```

**To Reproduce**
Unclear?

**Expected behavior**
Unclear?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 13.3
 - Scanner Version [e.g. 22] 3.10.0

**Additional context**
**Essentially,** how can I run DFA with a larger heap space? I have 64 GB RAM on the target machine so using more RAM should not be an issue for me.

"Workaround": Have you found any ways to sidestep the problem? No

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping". N/A

**Comment by johnbelosf** [comment]
Hi @az-oolloow please check the "Understand OutOfMemory Errors" section in our [documents](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/working-with-sfge/) to understand how you can work around these issues
