### ISSUE TITLE
[BUG] Path evaluation timed out after 900000 ms

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/sfdx-scanner#1042]
**Describe the bug**
Running `dfa` command I get `Path evaluation timed out after 900000 ms` for a number of paths

**To Reproduce**
Unclear

**Expected behavior**
A way to increase the time out?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 13.3
 - Scanner Version [e.g. 22] 3.10.0

**Additional context**
**Essentially,** how can I increase the timeout so that evaluation does not end for my complex codebase?

"Workaround": Have you found any ways to sidestep the problem? No

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".

It will be business stopping if we are forced to use this for ISV security reviews.

**Comment by johnbelosf** [comment]
Hi @az-oolloow please check the "Understand OutOfMemory Errors" section in our [documents](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/working-with-sfge/) to understand how you can work around these issues

**Comment by rmohan20** [comment]
Hi @az-oolloow - thanks for checking with us.
`--rule-thread-timeout` parameter on `scanner:run:dfa` will take an override value for the timeout.

**Comment by johnbelosf** [comment]
Closing for now - please reopen if still an issue
