### ISSUE TITLE
[BUG] can't use "sfdx project delete source"

### ISSUE THREAD

**Issue by gudge25** [forcedotcom/sfdx-scanner#1055]
sfdx --version
sfdx-cli/7.196.9 darwin-x64 node-v18.15.0

<img width="576" alt="image" src="https://user-images.githubusercontent.com/2346208/233050351-ecf3d1b5-c062-4ae1-ab03-bdfbfcafe3ae.png">

so i run:
sfdx project delete source --manifest /Users/Anton_Satskyi/Downloads/W-001551-destructivePackage.xml --target-org UAT
and  got an error
```
`Error (1): Nonexistent flag: --manifest`
See more help with --help

```
it was working  on old  sfdx versions command

**Comment by johnbelosf** [comment]
@gudge25 is this related with Salesforce Code Analyzer? It seems a CLI question

**Comment by gudge25** [comment]
oh  my bad sorry
