### ISSUE TITLE
[BUG] Unable to Install SFDX CLI Scanner in Win 10 Enterprise Edition

### ISSUE THREAD

**Issue by devboorla** [forcedotcom/sfdx-scanner#1066]
**Describe the bug**
I get the below error while install sfdx cli Scanner

Polling for new version(s) to become available on npm... done
Finished digital signature check.
Installing plugin @salesforce/sfdx-scanner... | [1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@salesforce%2fsfdx-scanner: write EPROTO A0630000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\\ws\\deps\\openssl\\openssl\\ssl\\statem\\extensions.c:922:
Installing plugin @salesforce/sfdx-scanner... failed
    JitPluginInstallError: Could not install @salesforce/sfdx-scanner
    Code: JitPluginInstallError

**To Reproduce**
Go to a command promt 
enter the command to install SFDX CLI Scanner
**Expected behavior**
SFDX CLI Scanner gets installed 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise
 - Scanner Version : Latest

**Additional context**
It is within Large Enterprise context. 
Has it got it to anything with this issue: https://github.com/forcedotcom/cli/issues/1300  ? 
"Workaround": Have you found any ways to sidestep the problem?
No

"Urgency": How severe is this problem? "Business stopping"

**Comment by johnbelosf** [comment]
Hi @devboorla can you provide more context on why this is business stopping?

Can you confirm you also have the latest version of Salesforce CLI? And installed Java?

**Comment by devboorla** [comment]
Hi! Sure. We are trying to implement this within out CI/CD program before we start our development for our next big release. The development is about to start next week. This is part of a much broader changes that we plan on bringing to our CI/CD. Once the development starts, we cannot introduce this new process as it will be too much of a change for our teams during the dev cycle. If we miss this window, then we won't be able to implement this process for next several months. Hence the urgency. 

Yes. I do have the latest CLI and Java version (Zulu Open SDK)
sfdx-cli/7.198.7 win32-x64 node-v18.16.0
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)

**Comment by rmohan20** [comment]
Hi @devboorla - we haven't been able to repro the issue.
Is it possible that there's a firewall blocking you since you are within a large enterprise context?
This looks similar to an older issue that sfdx-cli cannot resolve: https://github.com/forcedotcom/cli/issues/1857 - might be worth trying out the workarounds mentioned there.

**Comment by jfeingold35** [comment]
@devboorla , Is this still a problem for you?

**Comment by jfeingold35** [comment]
Unable to reproduce internally, and user went silent.
