### ISSUE TITLE
[BUG] v3.12.0 - Attempted to resolve unregistered dependency token: "RuleManager" 

### ISSUE THREAD

**Issue by mmoyaferrer** [forcedotcom/sfdx-scanner#1077]
**Describe the bug**
When executing Graph analyzer or RetireJS through the sfdx scanner, the next error is thrown than process is stopped 
- For DFA: `ERROR running scanner:run:dfa:  Attempted to resolve unregistered dependency token: "RuleManager"`
- For RetireJS: `ERROR running scanner:run:  Attempted to resolve unregistered dependency token: "RuleManager"`

**To Reproduce**

1. Our execution is part of a Bitbucket pipeline, where we run  `salesforce/salesforcedx:latest-full` docker image as a baseline (not sure if this could impact)
2. Install sfdx scanner, `sfdx plugins:install @salesforce/sfdx-scanner` (version v3.12.0)
3. Run DFA or RetireJS, `sfdx scanner:run:dfa --format table --target force-app --projectdir force-app` or `sfdx scanner:run --format table --target force-app --engine "retire-js"` respectively

**Expected behavior**
Returns analysis result

**Screenshots**

<img width="791" alt="Screenshot 2023-05-17 at 16 21 15" src="https://github.com/forcedotcom/sfdx-scanner/assets/15876612/e8bfb8d8-c389-4514-8e2b-2800af3c2dc1">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - `salesforce/salesforcedx:latest-full` docker image
 - Scanner Version [e.g. 22] - v3.12.0 

**Additional context**

Is it possible that this bug was re-introduced? I saw it in a previous version in [this StackExchange](https://stackoverflow.com/questions/67534139/i-get-this-error-running-pmd-from-salesforce-cli-error-running-scannerrun-at) post

"Workaround": Have you found any ways to sidestep the problem? No

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping". Not business-stopping

**Comment by johnbelosf** [comment]
hi @mmoyaferrer can you try to run the command again? We have an issue that we're currently fixing whereby if Code Analyzer is installed via the CLI's new "just-in-time install" feature (like I see in your screenshot), you will get this error.

However it should run fine if you try again.

**Comment by jfeingold35** [comment]
@mmoyaferrer , we believe we've resolved this issue with our June 7 release. If possible, can you try to run the command again and let us know if it works? If so, we'd like to close this issue.

**Comment by jfeingold35** [comment]
Since we haven't heard anything to the contrary, we're going to close this issue as completed for now, and we can re-open it if need be.
