### ISSUE TITLE
[BUG] Unable to register and execute custom XML rules

### ISSUE THREAD

**Issue by mitchspano** [forcedotcom/sfdx-scanner#1104]
### Describe the bug
I am unable to register custom XML rules using the `rule:add` command and have them produce findings when the scan is run.

### To Reproduce

I am following the instructions located [here](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/custom-rules/author/#pmd-custom-rules).
> Define rules in XML files with a path that matches this format: &lt;some base dir&gt;/category/&lt;language&gt;/&lt;filename&gt;.xml.

Project directory:
```
.
├── LICENSE
├── README.md
├── config
│   └── project-scratch-def.json
├── force-app
│   └── main
│       └── default
│           └── flows
│               └── foobar.flow-meta.xml
├── pmd
│   └── category
│       └── xml
│           └── flow.xml
└── sfdx-project.json
```

`pmd/category/xml/flow.xml`
```xml
<?xml version="1.0"?>
<ruleset name="FlowRules" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>Flow Rules</description>

    <rule name="ShouldUseAutoLayout" language="xml"
        message="Flows should have CanvasMode = AUTO_LAYOUT_CANVAS"
        class="net.sourceforge.pmd.lang.rule.XPathRule">
        <priority>3</priority>
        <properties>
            <property name="version" value="2.0"></property>
            <property name="xpath">
                <value><![CDATA[
                //Flow/processMetadataValues[name/text[@Image='CanvasMode']]/value[stringValue/text[@Image!='AUTO_LAYOUT_CANVAS']]
                ]]> </value>
            </property>
        </properties>
    </rule>

</ruleset>
```

The rule works fine when executed in raw PMD:
```shell
java -cp "/Users/mitchellspano/pmd/lib/*:/Users/mitchellspano/Documents/myProject/*" net.sourceforge.pmd.PMD \
  -f json \
  --no-cache \
  -d "/Users/mitchellspano/Documents/myProject/force-app" \
  -R "/Users/mitchellspano/Documents/myProject/pmd/category/xml/flow.xml"
```

```json
{
  "formatVersion": 0,
  "pmdVersion": "6.53.0",
  "timestamp": "2023-07-01T12:20:22.696-05:00",
  "files": [
    {
      "filename": "/Users/mitchellspano/Documents/myProject/force-app/main/default/flows/foobar.flow-meta.xml",
      "violations": [
        {
          "beginline": 28,
          "begincolumn": 9,
          "endline": 30,
          "endcolumn": 16,
          "description": "Flows should have CanvasMode \u003d AUTO_LAYOUT_CANVAS",
          "rule": "ShouldUseAutoLayout",
          "ruleset": "FlowRules",
          "priority": 3
        }
      ]
    }
  ],
  "suppressedViolations": [],
  "processingErrors": [],
  "configurationErrors": []
}
```

However, it does not work when added to the sfdx scanner plugin:

```shell
$ sfdx scanner:rule:add --language xml --path "pmd/category/xml/flow.xml"

$ sfdx scanner:run -t "force-app" --pmdconfig "pmd/category/xml/flow.xml"
```
```
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
About to run PMD with custom config in pmd/category/xml/flow.xml. Please make sure that any custom rule references have already been added to the plugin through scanner:rule:add command.
Executed engines: pmd-custom, retire-js. No rule violations found.
```

### Expected behavior
I would have expected the scanner to produce the same findings as calling PMD directly.

### System Versions
- OS:  Mac OS Ventura
- node: 16.13.1
- sfdx cli: 7.192.2 
- pmd: 6.53.0
- sfdx-scanner: 3.10.0

### Workaround
Write the rules in Java and compile them - not very useful workaround.

### Urgency
Business stopping as the tool cannot be used for simple custom rules

I have also tried with the exampled put together by @rsoesemann  but encountered the same issues using that sample project - https://github.com/rsoesemann/unhappy-soup

**Comment by mitchspano** [comment]
I believe this is related to #992. After checking out [this comment](https://github.com/forcedotcom/sfdx-scanner/issues/992#issuecomment-1452105622) I was able to get it to work:

```shell
sed 's,"\!\*\*/\*-meta.xml","\*\*/\*-meta.xml",g' ~/.sfdx-scanner/Config.json
```

`pmd/allRules.xml`
```xml
<?xml version="1.0"?>
<ruleset name="AllRules" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>All Rules</description>
    <rule ref="pmd/category/xml/flow.xml" />
</ruleset>
```

```
$ sfdx scanner:rule:add --language xml --path "/Users/mitchellspano/Documents/myProject/pmd/category/xml/flow.xml"

$ sfdx scanner:run -t "force-app" --pmdconfig "pmd/allRules.xml"
```
```
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
About to run PMD with custom config in pmd/allRules.xml. Please make sure that any custom rule references have already been added to the plugin through scanner:rule:add command.
 LOCATION                                             DESCRIPTION                                         CATEGORY  U R L 
 ──────────────────────────────────────────────────── ─────────────────────────────────────────────────── ───────── ───── 
 force-app/main/default/flows/foobar.flow-meta.xml:28   Flows should have CanvasMode = AUTO_LAYOUT_CANVAS FlowRules       
Executed pmd-custom, found 1 violation(s) across 1 file(s).
Executed retire-js, found 0 violation(s) across 0 file(s).
Rule violations were logged to the console.
```

**What is the intention of scanning metadata being disabled by default?**
Can we opt out of this without a modification to the `.Config.json` file?

While it's relatively to modify this value during local execution, it is not so easy when in the context of a GitHub action such as https://github.com/mitchspano/sfdx-scan-pull-request.

**Comment by rsoesemann** [comment]
@rmohan20 @johnbelosf could you please help @mitchspano to resolve this. The community is relying on his great Github Action but he is unable to find out how to make Custom XML rules in rulesets work from his Action.

Thanks in advance!

**Comment by jfeingold35** [comment]
@rsoesemann , @mitchspano , Roopa and John are both on extended leaves of absence, so I'll be helping you today.
To that end, I have a few notes.
1. You shouldn't need to use both `scanner:rule:add` and `--pmdconfig` at once the way your example does. They're meant for slightly different use cases, as follows:
a. `scanner:rule:add` is for users who have a set of custom rules they want to run *alongside* ours. You can use `scanner:rule:add` to register custom rules (as JARs or XMLs) with our internal catalog, and they'll be displayed in `scanner:rule:list` and run in `scanner:run` alongside PMD's built-in rules, with no need for `--pmdconfig`.
b. `--pmdconfig` is for users who have a set of custom rules they want to run *instead of* ours. You can use `--pmdconfig` to specify an XML file containing custom rule definitions, and those rules will run instead of the rules we have in our internal catalog.
2. The decision to exclude `-meta.xml` files was made a very long time ago, but my recollection is that we did so primarily for performance/usability reasons. PMD's default XML rules aren't terribly relevant to such files, so at the time all it was doing was throwing syntax violations for the handful of things you can do in a metadata file that PMD doesn't consider to be valid XML.

Long-term, we can definitely revisit whether it makes sense to continue excluding metadata files by default, and what the possible consequences of removing that exclusion would be.
I'll spend some time brainstorming ways to get you some relief in the short-term.

Thank you for your patience.

**Comment by rsoesemann** [comment]
@jfeingold35 while I understand the original reasons to ignore XML it's a significat mistake for the Scanners and PMDs adoption. I just recently gave conference talks about Custom XPath Rules for arbitrary Salesforce Metadata and it was wildly and happily received.

I would love to spend some time with @johnbelosf @rmohan20 and you to convince you to change that asap.

BTW: Here is the talks slides https://docs.google.com/presentation/d/1t8LokITTGUEnAwf0-bJSLbMgXS6-F19_-eAMmOfN1OA/edit?usp=sharing

**Comment by jfeingold35** [comment]
@rsoesemann , I certainly understand your frustration with the user experience in this area, and the team remains committed to providing our users with a quality product. However, our bandwidth is currently extremely limited, so we're having to make some difficult choices about where to invest our time.
In September, our bandwidth should increase enough to allow us to revisit this.

**Comment by jfeingold35** [comment]
After consideration, we've decided to treat this as a bug. We're aiming to ship a fix with the upcoming 3.17.0 release. I'll post further updates here as and when they become available.

**Comment by jfeingold35** [comment]
@mitchspano , @rsoesemann , I'm pleased to report that the recently-merged PR #1198 fixes this issue. Starting in the upcoming 3.17.0 release, `!**/*-meta.xml` will no longer be present in the default configuration for PMD. Additionally, a post-update script has been added to remove this entry from existing configurations the first time they run a command on 3.17.0 or later.
I'm going to close this Issue for now, and we can re-open it later if need be.

**Comment by marcopinder** [comment]
@jfeingold35 When can we expect the 3.17.0 release to be available?

**Comment by jfeingold35** [comment]
@marcopinder , the 3.17.0 release is scheduled for tomorrow. It should be released some time in the late morning (US Central Time).

**Comment by rsoesemann** [comment]
@mitchspano does this work for you now after updating the plugin?

@jfeingold35 How would I need to change https://github.com/rsoesemann/unhappy-soup to make this work with a single file rulset.xml?

1. Move all <rule> nodes into the central ruleset.xml
2. Call `sfdx scanner:run --format table --target force-app --engine "pmd" --pmdconfig=pmd/ruleset.xml`
3. Would I need to add rules before and how?

**Comment by jfeingold35** [comment]
@rsoesemann , the `--pmdconfig` flag is unnecessary here. When I was validating my fix, I did `sfdx scanner:rule:add --language xml --path './category/xml/custom.xml'` and then the rules were available through `sfdx scanner:run` the same as the default rules.
