### ISSUE TITLE
JAVA_HOME error

### ISSUE THREAD

**Issue by rajnimtr** [forcedotcom/sfdx-scanner#1126]
Getting the below issue while running sfdx scanner:

The Java Home is invalid: C:\Program Files\Java\jre1.8.0_341. Error code: ENOENT.
Please verify that Java 1.8 or later is installed on your machine and try again.
If the problem persists, please manually add a 'javaHome' property to your Config.json file, referencing your Java home directory.

**Comment by jfeingold35** [comment]
Just to make sure all of our bases are covered, is there a `C:\Program Files\Java\jre1.8.0_341` folder on your machine?

**Comment by rajnimtr** [comment]
No. The one which I have C:\Program Files\Java\jre1.8.0_361. Not sure from where its pulling the '_341' one

**Comment by jfeingold35** [comment]
Your answers to these questions will help us figure out how this might have happened.
1. Is this a new install of the Analyzer, or is this an old install that suddenly broke?
2. Did you recently update your machine's version of Java?

Regardless, you can fix it by deleting the `javaHome` property of your `~/.sfdx-scanner/Config.json` and running any analyzer command again.

**Comment by merseytechnology** [comment]
> Regardless, you can fix it by deleting the `javaHome` property of your `~/.sfdx-scanner/Config.json` and running any analyzer command again.

I experienced the same issue and this fixed it for me

**Comment by rajnimtr** [comment]
Thanks for the reply. I deleted the JavaHome property and ran it again but still getting the same error. The analyzer is the new version and Java is the same version. No update made to Java. However, the Java_home in the env variable has been updated to fix this issue. But looks like its referring the _341 from somewhere

**Comment by rajnimtr** [comment]
@jfeingold35 The JAVA_HOME env variable was updated before I deleted the javaHome property. The scanner gives the same response irrepective of whether the javaHome key is present or not in the config.json file

**Comment by jfeingold35** [comment]
@rajnimtr , if you remove the `javaHome` property from the config, then the next command you run should repopulate it with a new value, and it will set that value based on the `JAVA_HOME` environment variable if it exists.
So if your `JAVA_HOME` is set to the `_361` value, then that value should be used to set the `javaHome` property.

Please verify that your `JAVA_HOME` variable is set to the `_361` value. You can do this by running `node`, and then running `process.env`. One of the entries should be `JAVA_HOME`. Please confirm that this value is the `_361` and not the `_341`.

**Comment by rajnimtr** [comment]
@jfeingold35 This is superful help. I think the Java_home in the env variables is not set at the system variable level but set at the user level. I am not the admin of my system. So perhaps I need to raise a ticket to get the Java_Home set at the sys variable. Do you think that would work? Again, thanks a ton for your inputs.

**Comment by jfeingold35** [comment]
@rajnimtr , I'm actually not positive whether that would work, but I think it's probably worth a shot. Alternatively, if your goal is to just unblock your system and be done with it, you could manually edit the `_341` value in the config file's `javaHome` property to be `_361` instead.

**Comment by rajnimtr** [comment]
@jfeingold35 I tried updating the config.json file to _361 for the javaHome property but the scanner is not acknowledging that path. Still facing the same issue. I have requested our help desk to update the sys variable and will check

**Comment by jfeingold35** [comment]
@rajnimtr , just to be sure, you updated it to `C:\Program Files\Java\jre1.8.0_361`, and that didn't work either?

**Comment by jfeingold35** [comment]
@rajnimtr , any updates on this?

**Comment by rajnimtr** [comment]
@jfeingold35 I am still not able to make it run in my work system but its working in my personal system. I have updated the env variable under the system variable. No luck so far.

**Comment by jfeingold35** [comment]
@rajnimtr , if your `javaHome` property in `~/.sfdx-scanner/Config.json` is manually set to the correct value, then it shouldn't matter what your `JAVA_HOME` environment variable is.
So if your machine's Java installation lives in `C:\Program Files\Java\jre1.8.0_361`, then you should set your `javaHome` property to `"C:\\Program Files\\Java\\jre1.8.0_361"`, making sure to wrap the value in quotes and use `\\` in place of `\`. Please try this and let me know if it works.

**Comment by rajnimtr** [comment]
@jfeingold35 It worked :) I was updating the wrong config.json. I was updating the one in the .sf folder instead of the .sfdx-scanner folder.

**Comment by jfeingold35** [comment]
Happy to help.

**Comment by kmavrov** [comment]
Joining the conversation here where can i find the `~/.sfdx-scanner/Config.json` exactly on Windows, because i am having the same issue with updating versions.
