### ISSUE TITLE
[BUG] ERROR: Class is defined in multiple files

### ISSUE THREAD

**Issue by efwalter** [forcedotcom/sfdx-scanner#1129]
**Describe the bug**
Running the dfa command: sfdx scanner:run:dfa --format=csv --outfile=./reports/CodeAnalyzerDFA.csv --target=./main/default/classes --projectdir=./main/default  --category=Security
is throwing this error:
Error
ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: BatchErrorHandler is defined in multiple files
Files=[./main/default/classes/BatchErrorHandler.cls, ./main/default/triggers/KWD_BatchErrorHandler.trigger]

**To Reproduce**
run sfdx scanner:run:dfa --format=csv --outfile=./reports/CodeAnalyzerDFA.csv --target=./main/default/classes --projectdir=./main/default  --category=Security

**Expected behavior**
Generate a CSV with the issues found

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4.1 (c)
 - Scanner Version 3.14.0

**Additional context**
The name of the trigger and the apex class are the same, which is causing the issue

"Workaround": none so far

"Urgency": It's impacting our managed package release!

**Comment by jfeingold35** [comment]
@efwalter , You're correct that a trigger sharing the same name as a class/interface shouldn't cause the error you're seeing. We'll log this as a bug.
That said, I have a question: Can you change the name of the trigger to `KWD_BatchErrorHandler` so it matches the name of its file? Top-level classes/interfaces/triggers should match the name of their file anyway, and doing this name change would at least unblock your release.

**Comment by efwalter** [comment]
oh sorry, I forgot to remove the KWD_ from the second file, my mistake,
but both files have KWD_ on their names, I just tried to make "easier" to understand removing it from here

**Comment by jfeingold35** [comment]
@efwalter , thanks for the clarification.
I've logged a bug for this issue, and we'll let you know as soon as it's fixed. In the meantime, we've verified that the issue only occurs in v3.13.0 and later, so if you can't rename the trigger then you should be able to work around it by pinning your version to 3.12.0 for now. Could you try that and let us know if that works?
Thanks!

**Comment by efwalter** [comment]
@jfeingold35 yes, downgrading the version did work

thanks

**Comment by jfeingold35** [comment]
@efwalter , glad to hear it! We'll let you know as soon as the bug is fixed.

**Comment by jfeingold35** [comment]
@efwalter , we've merged a fix for this bug, and it'll go out in the upcoming 3.16.0 release (scheduled for this Tuesday, 9/5).
