### ISSUE TITLE
Running the scanner with category filter causes only the retirejs engine to be used

### ISSUE THREAD

**Issue by jkranz-rk** [forcedotcom/sfdx-scanner#1131]
**Describe the bug**
When you run the scanner with the `--category 'security'` flag, it only uses the retire-js engine

**To Reproduce**
In a project that has a mix of violations, run:
`sf scanner run --target 'force-app/main/default'`
verify that the scanner reports the violations from across the engines, including violations in security category and others

then run:

`sf scanner run --target 'force-app/main/default' --category 'security'`

**Expected behavior**
The scanner should run all of the rules that are in the 'security' category and report any violations

**Actual/Observed behavior**
The scanner results indicate that only the retire-js engine was used

**Desktop (please complete the following information):**
 - OS: Windows 11
 - SF CLI Version: @salesforce/cli/2.1.7
 - Node Version: node-v19.6.1
 - Scanner Version: @salesforce/sfdx-scanner 3.14.0

**Comment by jfeingold35** [comment]
Category names are case-sensitive. Try using "Security" instead of "security".

**Comment by jkranz-rk** [comment]
`facepalm`

@jfeingold35 thank you!!
