### ISSUE TITLE
[BUG] InternalExecutionError in report after scan is complete

### ISSUE THREAD

**Issue by ilin-argirov** [forcedotcom/sfdx-scanner#1142]
**Describe the bug**
Running the Code Analyzer results in entries in the report stating "InternalExecutionError ". Bear in mind that some entries show legitimate security issues ("ApexFlsViolationRule") whilst a few are categorised as "InternalExecutionError".

`Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. `

`Error and stacktrace: UnexpectedException: MethodCallExpressionVertex{fullMethodName=Database.query, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[Database], BeginLine=425, DefiningType_CaseSafe=antavoservice, LastChild=false, DefiningType=AntavoService, EndLine=425, Name_CaseSafe=database, childIdx=0, BeginColumn=35, ReferenceType=METHOD, Name=Database}}}, chainedNames=[Database], properties={FirstChild=true, FullMethodName=Database.query, BeginLine=425, FullMethodName_CaseSafe=database.query, DefiningType_CaseSafe=antavoservice, LastChild=false, DefiningType=AntavoService, EndLine=425, MethodName_CaseSafe=query, childIdx=0, BeginColumn=44, MethodName=query}}: com.salesforce.graph.symbols.apex.ApexSoqlValueFactory.lambda$static$0(ApexSoqlValueFactory.java:21);com.salesforce.graph.ops.ApexStandardLibraryUtil.getStandardType(ApexStandardLibraryUtil.java:154);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1224);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:749);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:79);com.salesforce.graph.ops.expander.ApexPathExpander.performAfterVisit(ApexPathExpander.java:577)`

**To Reproduce**
Run the code analyzer on a client's proprietary code base.

**Expected behavior**
I would expect to receive legitimate ApexFlsViolationRule entries instead of InternalExecutionError.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Scanner Version: 3.13.0

**Additional context**
I have followed the recommendation to add engine directives to skip scanning the affected segments of code. I have tried directives for specific rows in the code, method directives and even class directives - the same InternalExecutionError keeps happening and is not removed from the report results.

"Workaround": None

"Urgency": Not business-stopping

**Comment by jfeingold35** [comment]
@ilin-argirov , It looks like you're calling `Database.query`. What specific overload of that method are you calling? This sounds like it might be a duplicate of #1122.

**Comment by ilin-argirov** [comment]
@jfeingold35, you are correct. The conditions in which this bug presents itself are identical to the ones posted in the issue you linked. Apologies for the duplicate submission!

**Comment by jfeingold35** [comment]
Closing this as a duplicate of #1122.
