### ISSUE TITLE
Support for pmd v7.0.0.0 rule engine

### ISSUE THREAD

**Issue by mainakgupta33** [forcedotcom/sfdx-scanner#1145]
**Is your feature request related to a problem? Please describe.**
Currently the PMD rule engine supported is pmd v6.5.5 but with Salesforce latest summer 23 release
a lot features like Usermode keywords are not being recognised by the older PMD versions and running
the scanner on codes containing those keywords still report the classes to be non CRUD validation compliant.

**Describe the solution you'd like**
If the support for latest PMD v7.0.0.x can be added and can be put in the CLI parameter to mention the desired
pmd version then this will solve the problem.

**Describe alternatives you've considered**
Alternatives checked is the APEX PMD plugin for VSCode but that runs on even lower PMD version 5.9 by default
and it doesn't work in a stable way even the bin location of PMD 7 is provided.
**Additional context**

"Workaround": Can you do something similar with existing capabilities?

"Urgency": How badly do you need this feature? "Nice to have" vs "Highly beneficial" vs "Can't live without it".
Since there is no alternatives available as of now that makes it "Can't live without it" category as without it 
it makes the point of using PMD scan useless if it can't tell if the best practices are followed and marks the codes 
as false positive even when latest best practices are followed.

**Comment by jfeingold35** [comment]
@mainakgupta33 , I understand your frustration. However, the team's bandwidth is currently extremely limited, and we've made the decision to hold off on updating to PMD 7 until it goes GA, to avoid excessive churn.
We'll keep you appraised as the situation develops, and we appreciate your patience in the meantime.

**Comment by stephen-carter-at-sf** [comment]
We decided to create a --preview-pmd7 flag with https://github.com/forcedotcom/sfdx-scanner/pull/1359 to be released in March.
