### ISSUE TITLE
[BUG] ApexCRUDViolation false positive reported on dynamic sObject

### ISSUE THREAD

**Issue by Vijaykumarj** [forcedotcom/sfdx-scanner#1147]
**Describe the bug**
Got the "Validate CRUD permission before SOQL/DML operation (rule: Security-ApexCRUDViolation)" error on while trying to insert the **dynamic sObject** in apex class even we checked the isCreateable() permission before inserting the record.

**To Reproduce**
1. Create the dynamic sObject
2. Validate the Create permissions 
3. Assign the values to any one the field
4. Ran the SFDC scanner command

     Below is code snippet to reproduce the steps
![image](https://github.com/forcedotcom/sfdx-scanner/assets/26544969/b3bf7a3a-6832-43c5-bcae-fa8b6a528e4e)

**Expected behavior**
It should not be considered as ApexCRUDViolation violation. 

**Screenshots**
Below is the error screenshot of violation
![image](https://github.com/forcedotcom/sfdx-scanner/assets/26544969/8048ce51-f9cf-461d-a1ee-71790cbedd90)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Scanner Version @salesforce/sfdx-scanner 3.14.0

**Additional context**
If this is correct violation, what is the workaround in this situation (for dynamic sObjectType).

"Workaround": No

"Urgency": Business stopping

**Comment by jfeingold35** [comment]
@Vijaykumarj , this is actually a bug with the underlying PMD rule. So we recommend you log this issue directly with them.

**Comment by Vijaykumarj** [comment]
Thanks @jfeingold35 for confirmation. When performing their Security Audit assessment, would Salesforce team not consider it a bug?

**Comment by jfeingold35** [comment]
@Vijaykumarj , Security Audit is conducted by a separate team, so I'm not actually positive whether this would be considered a bug. However, I know the audit process gives you a chance to document false positives for this exact reason.
Additionally, PMD does allow you to suppress violations at the line- or class-level by using the `// NOPMD` or `@SuppressWarnings` annotation.
But regardless, the behavior you've described does seem to constitute a bug in PMD, and in the interest of getting that bug fixed, we still recommend that you check whether PMD already has an existing Issue for it, and create one if none already exists.

**Comment by jfeingold35** [comment]
Closing this Issue, as it represents a problem with PMD, not with Code Analyzer itself.
