### ISSUE TITLE
No output file if there are no violations

### ISSUE THREAD

**Issue by charlie-minns** [forcedotcom/sfdx-scanner#1157]
**Describe the bug**

An output file does not get created when no violations are detected, which I need to submit for security review.

This appears to be the expected behaviour based on line 33 (https://github.com/forcedotcom/sfdx-scanner/blob/dev/src/lib/util/RunOutputProcessor.ts), as line 48 does not run.

It looks like this has been the behaviour for a while, has anyone else come across this issue? Or alternatively, can I submit without the file or upload an empty file? Any guidance would be much appreciated if I have missed something.

**To Reproduce**

Run `sfdx scanner:run --format=csv --outfile=CodeAnalyzerGeneral.csv --target="./" --category="Security"` or `sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="DIR_NAME" --category="Security"`

No file is created if there are no violations, but one is created as expected if I add a violation.

**Expected behavior**

I am not sure what the file should contain if there are no violations. I would have thought that the security review team look for something in particular in that file to know the scan has run and no violations were found.

For consistency I think a file should be outputted if the flag is set, or at least a message that says the file has deliberately not been created.

**Desktop (please complete the following information):**
 - OS: Windows
 - Scanner Version: 3.15.0

"Urgency": Business stopping - cannot submit for security review without the file

**Comment by jfeingold35** [comment]
@charlie-minns , thanks for bringing this to our attention. We've added an item for this to our backlog to address this, and we'll keep you posted as the situation develops.
In the meantime, we recommend that you upload a file saying "there are no errors found with the Salesforce Code Analyzer".

**Comment by capeterson** [comment]
As @jfeingold35 notes, we flagged this to the security review ops team so they're aware of the gap and to accept this kind of manually created file as an interim workaround. If you have issues with that approach please let us know.

**Comment by charlie-minns** [comment]
@jfeingold35 @capeterson Works for me  - thank you both!

**Comment by jfeingold35** [comment]
@charlie-minns , we've pushed a fix for this that should go out with the upcoming 3.17.0 release. We're going to close the issue for now, but we can reopen it later if need be.
