### ISSUE TITLE
[BUG]  sfdx scanner:run:dfa not working

### ISSUE THREAD

**Issue by SPCPA** [forcedotcom/sfdx-scanner#1160]
**Describe the bug**

When running the following command:
`sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"`

From https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/security_review_code_analyzer_scan.htm 

I get the following error:

` sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="force-app/" --projectdir="./" --category="Se
curity"
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
(node:5540) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
Analyzing with Salesforce Graph Engine. See C:\USERPATH\.sfdx-scanner\sfge.log for details.... Error
ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: Graph engine encountered compilation errors. Fix the errors in C:\USERPATH\Documents\Bitbucket\ipfolio\.sfdx\tools\246\StandardApexLibrary\ApexPages\IdeaStandardController.cls and retry., Caused by:
Invalid syntax at 4:30. (Unexpected token 'delete'.)

Executed engines: sfge. No rule violations found.`

**To Reproduce**

Run the command

**Expected behavior**

The command should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] => Windows 10 Enterprise
 - Scanner Version [e.g. 22]: @salesforce/sfdx-scanner 3.15.0 
 - SFDX: @salesforce/cli/2.5.8 win32-x64 node-v18.15.0

**Additional context**

"Workaround": Have you found any ways to sidestep the problem?
No

**Comment by jfeingold35** [comment]
@SPCPA , we've merged a fix for this issue, and it'll go out in the upcoming 3.16.0 release, currently scheduled for Tuesday, September 5.
For now, we'll close this Issue, but we can re-open it if you continue to experience the problem after the new release.
We appreciate your patience.
