### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by anantkamat82** [forcedotcom/sfdx-scanner#1163]
**Describe the bug**
The Header name is wrongly spelled as "Catgegory" instead of "Category".

**To Reproduce**
Navigate to Rules section here - https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/rules/#apexflsviolationrule. Check the column headers.

**Expected behavior**
The column header should read "Category".
<img width="510" alt="Rules" src="https://github.com/forcedotcom/sfdx-scanner/assets/40661180/fbd3f155-9e15-4633-b08a-6a85816abe65">

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Scanner Version [e.g. 22] : NA

**Additional context**
NA

"Workaround": Have you found any ways to sidestep the problem? - Currently no workarounds since this involves changing the content.

"Urgency": How severe is this problem? "Not business-stopping".

**Comment by jfeingold35** [comment]
@anantkamat82 , oops! Thanks for bringing this one to our attention! We'll correct it in the upcoming 3.16.0 release (currently scheduled for Tuesday, 9/5).

**Comment by anantkamat82** [comment]
When will it reflect since the link I pasted still shows Catgegory instead of Category

**Comment by jfeingold35** [comment]
The updated documentation will go live on 9/5 when we publish the release.
