### ISSUE TITLE
[BUG] pmd seemingly not found

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/sfdx-scanner#1172]
**Describe the bug**
When scanning using
```
sfdx scanner:run --target "force-app/main/default/classes/SomeClass.cls" --category "Code Stye"
```
I get
```
Executed engines: retire-js. No rule violations found.
```

When I explicity specify engine

```
sfdx scanner:run --target "force-app/main/default/classes/UpdateCasePriorityBatch.cls" --category "Code Stye" -e pmd
```

I get
```
Executed engines: . No rule violations found.
```

Same class in CI reports some issues.

**To Reproduce**
Not quite sure

**Additional context**
I've recently botched my sfdx via brew upgrade somehow. Did easily fix by installing latest pkg.

I did reinstall plugin via cli.

When trying to run pmd via jetbrains, after loading [this](https://github.com/pmd/pmd/blob/master/pmd-apex/src/main/resources/category/apex/codestyle.xml) ruleset it manages to crash entire IDE with this error:

<img width="418" alt="Screenshot 2023-09-06 at 11 21 10 AM" src="https://github.com/forcedotcom/sfdx-scanner/assets/7092409/47264b26-da17-4828-b695-6510d7d01cd8">

Does pmd need to be installed manually or in specific location?

**Comment by sjurgis** [comment]
Running PMD 6.55 via cli works ok
```
 bash run.sh pmd -R ../../codestyle.xml -d /Users/user/workspace/repo/force-app/main/default/classes/someClass.cls
```

**Comment by jfeingold35** [comment]
@sjurgis , is the command an exact copy-paste?
If so, then `--category "Code Stye"` should be `..."Code Style"` with an L.

**Comment by sjurgis** [comment]
Oh. My. God... You're right.
