### ISSUE TITLE
No Reports generated when no violations found

### ISSUE THREAD

**Issue by Bosley99** [forcedotcom/sfdx-scanner#1183]
Describe the bug
Issue: when no violations found, no report is generated - so there isn't anything to upload back to the Security Review.

I ran the scanner several times, and fixed all the issues.  The exact commands are listed below. Now the scanner reports "No Rule Violations Found." The problem is - no reports are generated to upload to the Security Review!

"Urgency":  How is this Business stopping? 
We can't submit our App for security review.

To Reproduce
Run these two commands: 
1. sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security" 
2. sfdx scanner:run --format=csv --outfile=CodeAnalyzerGeneral.csv --target="./" --category="Security"

Expected behavior
Two files generated  - one for each scan - indicating that no rule violations are found.

Screenshots
If applicable, add screenshots to help explain your problem. See attached PDF with screenshot.

Desktop (please complete the following information):

OS: iOS
Scanner Version: v3.16.0 (installed/updated tonight) 
Additional context

"Workaround": Have you found any ways to sidestep the problem? Not yet.
[CodeScanner - No Violations Found 0918.pdf](https://github.com/forcedotcom/sfdx-scanner/files/12654613/CodeScanner.-.No.Violations.Found.0918.pdf)

**Comment by jfeingold35** [comment]
@Bosley99 , this is a duplicate of #1157.
