### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ashishrajbanshi** [forcedotcom/sfdx-scanner#1192]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Scanner Version [e.g. 22]

**Additional context**

"Workaround": Have you found any ways to sidestep the problem?

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".

**Comment by jfeingold35** [comment]
@ashishrajbanshi , can you please fill in the required fields?
