### ISSUE TITLE
[BUG] ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: Graph engine encountered compilation errors.

### ISSUE THREAD

**Issue by ashishrajbanshi** [forcedotcom/sfdx-scanner#1194]
**Describe the bug**
ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: Graph engine encountered compilation errors.

Fix the errors in D:\xxx\xxx\.sfdx\tools\246\StandardApexLibrary\ApexPages\IdeaStandardController.cls and retry., Caused by:
Invalid syntax at 4:30. (Unexpected token 'delete'.)

Fix the errors in D:\xxx\xxx\.sfdx\tools\246\StandardApexLibrary\Search\SuggestionOption.cls and retry., Caused by:
Invalid syntax at 4:31. (Unexpected token 'limit'.)

**To Reproduce**
Used `sfdx scanner:run:dfa --format=html --outfile=Approval_CodeAnalyzerDFA.html --target="./" --projectdir="./" --category="Security"`

**Expected behavior**
Expected to be scan correctly and output the result.

**Screenshots**
![image](https://github.com/forcedotcom/sfdx-scanner/assets/46884226/f298f93c-be81-498d-be24-d8898555b36c)

![image](https://github.com/forcedotcom/sfdx-scanner/assets/46884226/f065c1e3-60f8-4dbd-9b4f-4a7bea0f5386)

**Desktop (please complete the following information):**
 - OS: Window
 - Scanner Version : 
 @salesforce/sfdx-scanner 3.15.0 (3.15.0)
packaging 1.22.1 (1.22.1)

"Workaround": Error caused in _D:\xxx\xxx\.sfdx\tools\246\StandardApexLibrary\ApexPages\IdeaStandardController.cls and retry., Caused by: Invalid syntax at 4:30. (Unexpected token 'delete'.)_ is fixed by replacing delete with remove keyword.

"Urgency": It is holding security scan review of many projects.

**Comment by jfeingold35** [comment]
@ashishrajbanshi , we'll log this as a bug and add it to our backlog. However, as per [the documentation](https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/security_review_code_analyzer_scan.htm), you have the ability to document false positives during security review. So if you have a workaround, can you simply use that workaround to unblock yourself for now?

**Comment by rmohan20** [comment]
This is working as designed. `delete` and `limit` are [reserved keywords in Apex](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_reserved_words.htm). These cannot be used as method names or variable names. Graph Engine cannot analyze code that doesn't compile.
