### ISSUE TITLE
[BUG] Java version never gets outputted

### ISSUE THREAD

**Issue by gseiboldmtb** [forcedotcom/sfdx-scanner#1196]
**Describe the bug**
In the verifyJavaVersion method of the src/lib/JreSetupManager.ts file, the version variable is never set if the else clause is hit. To state this is more of a user use case, when the user's java version is not within the range of accepted java versions, the program tries to let the user know which version of java they're using and that is not greater than java 1.8 and the string that is supposed to hold the user's java version is never populated.

**To Reproduce**
Have an incorrect java version and try to run the scanner tool. OR set JAVA_TOOL_OPTIONS environment variable equal to "-Dfile.encoding=UTF-8"

**Expected behavior**
The user's java version is outputted with the error message of line 154 in src/lib/JreSetupManager.ts. AND if the JAVA_TOOL_OPTIONS environment variable is set to "-Dfile.encoding=UTF-8", that the program will still determine the user's java version correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows server 2016
 - Scanner Version: 3.16.0

**Additional context**
The regex expression located on line 129 of src/lib/JreSetupManager.ts uses the output of java -version which will pick up the JAVA_TOOL_OPTIONS and specifically the 8 from UTF-8 mentioned above which makes it look like the user's java version is major version 8.

"Workaround": Have you found any ways to sidestep the problem?
Remove the JAVA_TOOL_OPTIONS environment variable and use the correct java version.

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".
Not business-stopping but very difficult to debug what was wrong with the program without reading through the code.

**Comment by jfeingold35** [comment]
Thanks for bringing this to our attention. We'll add this to our backlog.
