### ISSUE TITLE
--target to become more like --path

### ISSUE THREAD

**Issue by nhall97** [forcedotcom/sfdx-scanner#123]
Hi,

Perhaps I'm misunderstanding the plugin configuration, but is there anyway to use the --target similar to that of the PMD --path?

It seems that --target only supports one file at a time?

Thanks.

**Comment by jfeingold35** [comment]
I assume you mean the `--target` parameter for the `run` command, right? If so, then I'm happy to say that `--target` accepts globs, directories, and files. It's also an array-type parameter, so you can provide an array of any of those things, separated by a comma. E.g., `--target "some/path/to/a/file.cls,another/path/to/a/dir,a/third/path/that/is/a/glob/**.*.cls"`. Please let us know if that doesn't work in the currently published version.

**Comment by nhall97** [comment]
@jfeingold35 Understood, thanks for the confirmation!
