### ISSUE TITLE
[BUG]When executing a custom ESlint rule with the scanner

### ISSUE THREAD

**Issue by allurisriakhil** [forcedotcom/sfdx-scanner#1233]
**Description**:
I am new to eslint and trying to execute a newly created custom eslint rule with the scanner command. But unable to get the desired output of the rule.                         

**Documentation**:

**Steps To Reproduce**:
1. Create a new rule called enforce-file-name.js to check wether the file name starts with AK_ or not as below 

```
/**
 * @fileoverview Custom ESLint rule to check if a file name starts with "AK_".
 */

module.exports = {
    meta: {
      type: 'suggestion', 
      docs: {
        description: 'Enforce file names to start with "AK_"',
        category: 'Best Practices',
        recommended: true,
      },
    },
  
    create: function(context) {
      return {
        Program: function(node) {
          if (context.getFilename() && !context.getFilename().startsWith('AK_')) {
            context.report({
              node: node,
              message: 'File name should start with "AK_"',
            });
          }
        },
      };
    },
  };
```

2. Created a .eslintrc.json file in the same directory 

```
{
  "parserOptions": {
    "ecmaVersion": 6
  },
  "rules": {
    "enforce-file-name/enforce-file-name.js": "error"
}
}
```
3. Executing the command below

`sfdx scanner:run --target rule/ --eslintconfig .eslintrc.json`

the rule directory consists of a sample js file with name filename.js

The output of the above command is as below

```
sfdx scanner:run --target rule/ --eslintconfig .eslintrc.json
 ›   Warning: sfdx-cli update available from 7.196.8 to 7.209.6.
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
About to run Eslint with custom config in .eslintrc.json. Please make sure your current directory has all the required NPM dependencies.
 LOCATION           DESCRIPTION                                         CATEGORY U R L 
 ────────────────── ─────────────────────────────────────────────────── ──────── ───── 
 rule/filename.js:1   Definition for rule                               problem        
                      'enforce-file-name/enforce-file-name.js' was not                 
                      found.                                                           
Executed pmd, found 0 violation(s) across 0 file(s).
Executed eslint-custom, found 1 violation(s) across 1 file(s).
Executed retire-js, found 0 violation(s) across 0 file(s).
Rule violations were logged to the console.
```

**Expected Behavior**:
The description and category should be as described in the enforce-file-name.js but that is not the case. Instead i am getting definition for rule not found as shown above.

**Screenshots**:
N/A

**Desktop**:
- Operating System: Ventura 13.6
- Code Analyzer version: @salesforce/sfdx-scanner 3.11.0
- Salesforce CLI version: sfdx-cli/7.196.8 darwin-x64 node-v18.15.0

**Additional Context**:

**Workaround**:

**Urgency**:

Please let me know if i am missing any step or what is the issue in this case? Thanks.

**Comment by allurisriakhil** [comment]
Hi @jfeingold35, Hope you are doing good. 

Could you please help me with this issue. Thanks.

**Comment by jfeingold35** [comment]
@allurisriakhil , have you verified that the rule produces the expected output when you run ESLint directly instead of running it via `sfdx-scanner`?

**Comment by allurisriakhil** [comment]
@jfeingold35, no i did not verify it with ESlint directly i tried executing it with via `sfdx-scanner` directly.

**Comment by jfeingold35** [comment]
@allurisriakhil , could you please try verifying it with ESLint directly? If that doesn't work, then it suggests the problem is with the rule itself, rather than the scanner, and in that case you're better off seeking help from the ESLint community than from us specifically.
If the rule does work when running ESLint directly, then it suggests the problem is with the scanner specifically, and we can move forward from there.

**Comment by jfeingold35** [comment]
@allurisriakhil , it looks like you're using a version of `sfdx-scanner` that's 6 months out of date. In the intervening time, we've already fixed the problem you're describing with `ignorePatterns`.
