### ISSUE TITLE
Cannot install SFDX Scanner

### ISSUE THREAD

**Issue by SPCPA** [forcedotcom/sfdx-scanner#1236]
Hello,

I'm following this tutorial (https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/security_review_code_analyzer_scan.htm) to install sfdx scanner because my machine has changed.
So I have installed SF cli:
$ sf version
@salesforce/cli/2.16.7 win32-x64 node-v20.8.1

When I type the following command:
$ sf plugins install @salesforce/sfdx-scanner
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/sfdx-scanner.
Finished digital signature check.
Installing plugin @salesforce/sfdx-scanner@latest... failed
 »   Error: @salesforce/sfdx-scanner does not exist in the registry.

Any hints what I'm doing wrong?
Thanks

**Comment by SPCPA** [comment]
Worked after doing another SF update.

**Comment by singlebat** [comment]
Sorry, I have the same issue. Please tell me what do you update? does another SF update mean that you have updated the SF CLI to the latest version?
