### ISSUE TITLE
Regarding the usage of sf cli with the scanner commands

### ISSUE THREAD

**Issue by allurisriakhil** [forcedotcom/sfdx-scanner#1248]
Hi,

As the salesforce cli was shifted from using sfdx to sf cli I tried using the sf commands instead of sfdx with the scanner commands and it worked and got the results.

The command i used is as below:

`sf scanner run --format csv  --target "source-code"`

And when i run 

`sf scanner --help`

o/p:

```
USAGE
  $ sf scanner COMMAND

TOPICS
  scanner rule  view or add rules to scan code
  scanner run   scan a codebase with a selection of rules

COMMANDS
  scanner run  scan a codebase with a selection of rules
```

But there is no supporting documentation for sf scanner run. So i would like to know wether i can use the sf instead of sfdx with the scanner commands or not. Will it effect any of the features offered with the sfdx scanner commands? 

Thanks.

**Comment by jfeingold35** [comment]
@allurisriakhil , I believe `sf scanner run` should still work. The issue here is that our plugin was developed around `sfdx`, and `sf` has some different things about how it configures its help text. We're already working on this.

**Comment by johnbelosf** [comment]
This issue is resolved
