### ISSUE TITLE
[BUG] sf scanner run not generating output while running in CircleCI.

### ISSUE THREAD

**Issue by himansupuswar** [forcedotcom/sfdx-scanner#1250]
**Description:**
sf scanner run not generating output while running in CircleCI but it works in  my local machine (Mac)

**Steps To Reproduce:**

1.  Run sf scanner in circle ci. using this command  
2. mkdir codescan          
3.  sf scanner:run --target './force-app/main/default/classes/,./force-app/main/default/lwc/,./force-app/main/default/pages/' -- 
projectdir './force-app/main/default' --format csv --outfile 'codescan/CodeAnalyzerGeneral.csv' --category 'Design,Best Practices,Security' --engine 'eslint,pmd,cpd,retire-js' --normalize-severity --verbose --loglevel trace

**Expected Behavior:**
generate output as **CSV** file and gets uploaded in the **Circleci artifacts** section

Laptop:
Operating System. Mac Sonoma 14.1.1
Code Analyzer version. Example: v3.18.0
Salesforce CLI version. Example: @salesforce/cli/2.17.14
 
<img width="1419" alt="image" src="https://github.com/forcedotcom/sfdx-scanner/assets/35326397/23597ff0-ca53-4ebe-b757-c6c4ecf22450">

**Comment by jfeingold35** [comment]
@himansupuswar , I need more information in order to provide aid. What is the scanner saying its outcome was? Is it saying there were no violations? Or is it failing with an error message? Or something else?

**Comment by himansupuswar** [comment]
@jfeingold35 no error & no violation message as such. that screenshot contains the exact output after running sf scanner command.

**Comment by jfeingold35** [comment]
@himansupuswar , can you post the `.circleci/config.yml` file and indicate the corresponding step? Also, have you consulted our [documentation regarding CI/CD integration](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/ci-cd-integration/)?

**Comment by himansupuswar** [comment]
sf scanner:run --target './force-app/main/default/classes/,./force-app/main/default/lwc/,./force-app/main/default/pages/' --projectdir './force-app/main/default' --format csv --outfile 'codescan/CodeAnalyzerGeneral.csv' --category 'Design,Best Practices,Security' --engine 'eslint,pmd,cpd,retire-js' --normalize-severity --verbose --loglevel trace

**Comment by himansupuswar** [comment]
@jfeingold35 That the entire output generated in Circleci.

**Comment by jfeingold35** [comment]
@himansupuswar , well that's weird. What happens if you target just one file instead of the entire directory? Try manually introducing a violation into one file (e.g., an unsecured SOQL) and then scanning just that file.

**Comment by himansupuswar** [comment]
@jfeingold35  Okay I will try that.

**Comment by stephen-carter-at-sf** [comment]
@himansupuswar Are you still having this issue with @salesforce/sfdx-scanner version 3.22 or later? 
(side note you'll want to update your config to install java 11 instead of java 8 now)

**Comment by stephen-carter-at-sf** [comment]
Since we have not heard back from you regarding this, we will be closing this issue for now.
