### ISSUE TITLE
Scanner Bug when using Zippex 3rd party class

### ISSUE THREAD

**Issue by adamerstelle** [forcedotcom/sfdx-scanner#1251]
**Description**:
DFA scan gives me an error when scanning code that generates a ZIP file. Additionally, the instruction telling it to disable scanning the method doesn't appear to work, resulting in the error remaining in CSV files.

**Steps to Reproduce**:

1. Clone this simple MRE project: https://github.com/adamerstelle/sfdx-scanner-issue-1251
2. sf scanner run dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"

**Expected Behavior:**

1. give me a reason that the code failed. Since this particular code does not have any DML, I would expect to not have any ApexFlsViolationRule or InternalExecutionError line items in the CSV report.
2.  Clearer guidance on how to skip scanning and producing this error in CSV report.

**Error and stacktrace**: UnimplementedMethodException: ApexStringValue:charAt, vertex=MethodCallExpressionVertex{fullMethodName=hexStr.charAt, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[hexStr], BeginLine=150, DefiningType_CaseSafe=hexutil, LastChild=false, DefiningType=HexUtil, EndLine=150, Name_CaseSafe=hexstr, childIdx=0, BeginColumn=26, ReferenceType=METHOD, Name=hexStr}}}, chainedNames=[hexStr], properties={FirstChild=true, FullMethodName=hexStr.charAt, BeginLine=150, FullMethodName_CaseSafe=hexstr.charat, DefiningType_CaseSafe=hexutil, LastChild=false, DefiningType=HexUtil, EndLine=150, MethodName_CaseSafe=charat, childIdx=0, BeginColumn=33, MethodName=charAt}}: com.salesforce.graph.symbols.apex.ApexStringValue.apply(ApexStringValue.java:396);com.salesforce.graph.symbols.PathScopeVisitor.handleApexValueMethod(PathScopeVisitor.java:1487);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1242);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:800);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:79);com.salesforce.graph.ops.expander.ApexPathExpander.performAfterVisit(ApexPathExpander.java:577)

**Comment by jfeingold35** [comment]
@adamerstelle , the code _is_ giving you a reason that it failed:
>  UnimplementedMethodException: ApexStringValue:charAt,

Apparently, we haven't implemented support for this built-in method on the Apex String class. We can add a bug to our backlog for adding support for this method.
