### ISSUE TITLE
[False Result] Inconsistency in "Validate CRUD permission before SOQL/DML operation" rule related to SOQL queries on custom metadata Objects.

### ISSUE THREAD

**Issue by Syed-Salesforce** [forcedotcom/sfdx-scanner#1262]
### Salesforce Code Analyzer False Results Template

**Description:**

We have performed a Code Scan analysis on the Custom Metadata of the sandbox org.
But there is some inconsistency in flagging out the rule 'Validate CRUD permission before SOQL/DML operation' on one of the class.

**Documentation:**

what should be the solution for custom metadata object SOQL queries based on the below link?

CRUD permission/field accessibility check is not applicable for custom metadata types.

https://salesforce.stackexchange.com/questions/368961/where-to-set-metadata-type-field-security

https://salesforce.stackexchange.com/questions/275576/do-we-need-to-check-crud-permissions-on-custom-metadata-type-custom-setting-to-p

**False Results Report:**

Rule is flagging out for below type of query:

try{

callout = [SELECT  first_c  FROM first__mdt
                               WHERE DeveloperName = :customMetadataName];
} catch

Not flagging out for below type of query:

List<Second__mdt> secondList = new List<Second_mdt>([Select second_c from second__mdt WHERE DeveloperName = :'customMetadataName' LIMIT 1])

**Steps To Reproduce:**

Retrieved the custom metadata from ANT tool.

Performed the code scan analysis with the below command

sfdx scanner:run --target={location} --outfile=result.csv --format=csv

**Expected Behavior:**

The rule 

**Screenshots:**

**Desktop:**

**Additional Context:**

**Workaround:**

**Urgency:**

URGENT

**Comment by jfeingold35** [comment]
This is actually an issue with the underlying PMD rule (ApexCRUViolation), and has been logged against PMD as [issue #4760](https://github.com/pmd/pmd/issues/4760).
