### ISSUE TITLE
[Question] Is the Scanner using the latest PMD 7 RC?

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-scanner#1273]
I am asking a question here as the Discussion forum seems stale:

Does the Scanner now use the latest PMD 7 Release Candidate which contains an updated Jorje Parser which respects `as user` DML?

I am asking for multiple reasons:

1. Salesforce was super stressed and eager to get this change in PMD but the Scanner seems not yet to use it. Or where is the PR showing that change?
2. I am unsure how to see which PMD or engines it is using and how to overwrite this in my own Github Actions.

**Comment by johnbelo** [comment]
@rsoesemann I replied in #1026 - we have encountered some compatibility issues between PMD6 and 7 and we are running further tests before we are able to upgrade. Our current plan is to do so as part of a new major release for Code Analyzer.

Other teams within Salesforce are using PMD7 and the user mode PR specifically internally, so this change was definitely welcome.

**Comment by johnbelosf** [comment]
@rsoesemann  I replied in https://github.com/forcedotcom/sfdx-scanner/issues/1026 - we have encountered some compatibility issues between PMD6 and 7 and we are running further tests before we are able to upgrade. Our current plan is to do so as part of a new major release for Code Analyzer.

Other teams within Salesforce are using PMD7 and the user mode PR specifically internally, so this change was definitely welcome.

**Comment by vc4u** [comment]
@johnbelosf Is there any way outside teams can utilize the same release with PMD 7? Writing code to satisfy Security Review conditions is becoming painful, with absence of not able to use User Mode properly. People wants to keep code clean, `Database` methods require dedicated error handling, increases the code as well. There are places we would want to use Database methods, and there are places it is better to just do DML insert/update with user mode. So ability to scan user mode with non-database based DMLs would be a great help for partner ISVs with the CLI.

**Comment by johnbelosf** [comment]
@vc4u you cannot choose an alternative engine to the one bundled with Code Analyzer. We want to provide PMD7 as soon as it's safe to do so. In the meantime, bear in mind that Graph Engine does support user mode if you are concerned about CRUD/FLS specifically.

In addition, we are planning to soon release a new collection of PMD rules that are specific to Security Review. This will hopefully come out in January.

**Comment by johnbelosf** [comment]
Please feel free to open a discussion here in our GitHub repo if needed - I think this specific issue has been answered so I'm closing it for the time being.
