### ISSUE TITLE
[BUG] Scanner run taking more than 30minutes

### ISSUE THREAD

**Issue by emegger** [forcedotcom/sfdx-scanner#1317]
**Description**:
Running the scanner with the following command from the terminal inside of IntelliJ it takes more than 30min to complete while for my colleagues (same repo) it takes only 1 -2 minutes.
sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"

**Steps To Reproduce**:
Hard to reproduce without my machine.

**Expected Behavior**:
Code analyzer should complete within a reasonable time like 1 or 2 minutes.

**Screenshots**:

![image](https://github.com/forcedotcom/sfdx-scanner/assets/156182213/5187e98a-01c4-4010-8a9d-b92a4c2b3312)

**Desktop**:

- Operating System. Windows 10
- Code Analyzer version: v3.19.0
- Salesforce CLI version: @salesforce/cli/2.22.7 win32-x64 node-v20.10.0
- Java: jdk-17.0.9.9-hotspot
- IntelliJ IDEA: 2023.2.2

**Urgency**:

At the moment I can't really use Salesforce Code Analyzer as it takes far too much time to see the results.
Thanks in advance for your help!

**Comment by johnbelosf** [comment]
@emegger this is working as expected. Unlike the static analysis you do with scanner:run, when you use scanner:run:dfa we use data flow analysis - we create a graph of all the possible code paths and then simulate their execution to identify more advanced problems. Depending on the complexity of your code base, this can take several hours.

More info on our docs: https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/introduction/

**Comment by emegger** [comment]
Hi, @johnbelosf!
My question is what can be the reason that the analysis of the same code takes so much more time on my machine than on my colleagues' machines?

**Comment by johnbelosf** [comment]
@emegger are you both using the same OS, CLI versions, Code Analyzer versions? And is the codebase similar?

**Comment by emegger** [comment]
Yes! same OS, same CLI version and exact same codebase

**Comment by johnbelosf** [comment]
OK. But you're starting the scan from CLI, not the IDE, correct?

**Comment by emegger** [comment]
I'm starting the scan from terminal within IDE.

**Comment by johnbelosf** [comment]
Alright it sounds like we need to get some more information - if you have the time to try to uninstall Code Analyzer and reinstall it and do the same with the CLI, that might be a way forward. Otherwise stay tuned and we will come back with a few more questions

**Comment by emegger** [comment]
I have done this already a couple of times yesterday - without any change :-/

**Comment by jfeingold35** [comment]
@emegger , a few silly questions:
- Are your colleagues running the same scan that you are?
- Are they initiating it from the same place?
- Are their machines' specs different from yours?
- You say that when you initiated the scan from a bash terminal, it was still running after four minutes. Would your colleagues' machine have already finished the scan by that point?

**Comment by emegger** [comment]
Not silly at all!

- Yes, they are running the same scan as me.
- They are also initiating it from the terminal but inside of VS code while I start it within Intellij
- machine spcecs are the same
- the scan run takes 1-2 minutes on my colleagues' machines and yes should have finished by that point. (mine would not even have finished after 30min - where I cancelled it finally.

**Comment by jfeingold35** [comment]
@emegger , Hm. Your screenshot indicates that you're running `scanner run`, not `scanner run dfa`, so a long-running scan is unexpected.
If your machines have the same specs and you're running the same scan against the same codebase, then I'm struggling to think of anything that could realistically be causing it to take so much longer on your machine than on theirs.
Perhaps another silly question, but does your scan complete in a timely manner if you use VSCode? Or alternatively, if a colleague uses IntelliJ, do they see the same slowdown as you?

**Comment by emegger** [comment]
I will ask a colleague with Intellij to run the scan.
Another thought I will check if some antivirus scan is messing with the code analyzer scan.

**Comment by emegger** [comment]
Update: for my colleague with Intellij it works fine.
In the meantime I had a look at the log file I found in .sf and it seems the process gets stuck while Writing Config file with content.
Has this occured with other users as well?

**Comment by emegger** [comment]
Thanks - I have sorted the issue out. obviously on my side there where more files to scan than on my colleagues'
 side. Sorry to bother you. Seems the scanner works fine. Will therefore close this ticket.
