### ISSUE TITLE
[BUG] sfdx installation error

### ISSUE THREAD

**Issue by jiacheng-xu** [forcedotcom/sfdx-scanner#1325]
### `scanner run` Issue Template

Fill out this template to submit your Code Analyzer issue.

**Description**:
cmd: sfdx scanner run
What I got:
```
Installing plugin @salesforce/sfdx-scanner@3.19.0... failed
 _   Warning: @salesforce/sfdx-scanner > @salesforce/command@5.3.9: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
    JitPluginInstallError: Could not install @salesforce/sfdx-scanner
    Code: JitPluginInstallError
```

sfdx --version
`@salesforce/cli/2.24.4 linux-x64 node-v16.20.0`

sf --version
`@salesforce/cli/2.24.4 linux-x64 node-v16.20.0`

 npm --version
`8.19.4`

node --version
`v16.20.0`

**Desktop**:
- Operating System. Example: Ubuntu 18

**Additional Context**:

**Workaround**:

**Urgency**:
Very urgent. Internal. please DM jiacheng.xu for questions and update.

**Comment by stephen-carter-at-sf** [comment]
I replied to you internally.

**Comment by stephen-carter-at-sf** [comment]
The old version of node v16 is the issue most likely. [jiacheng-xu](https://github.com/jiacheng-xu) has decided to upgrade away from ubuntu 18 to ubuntu 20 or greater so that he can have node v20 or greater. He will confirm that this fixes his problem soon...

**Comment by ar-srinivas** [comment]
We are facing the same issue even with the latest node version of 20.11.1

ubuntu@xxxx:~$ sf plugins install @salesforce/sfdx-scanner@latest
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/sfdx-scanner.
Finished digital signature check.
@salesforce/cli: Installing plugin @salesforce/sfdx-scanner@latest... failed
 ›   Error: @salesforce/sfdx-scanner does not exist in the registry.


ubuntu@xxx:~$ node --version
v20.11.1

@stephen-carter-at-sf

**Comment by stephen-carter-at-sf** [comment]
If you are seeing a "does not exist in the registry"... that might mean you have a yarnrc or npmrc file somewhere on your machine that is altering the registry that you are pulling from.

**Comment by ar-srinivas** [comment]
@stephen-carter-at-sf Is there a way to find those files? Of found those files, should we delete them or make any changes?

**Comment by stephen-carter-at-sf** [comment]
When is the last time you did a "sf update"? What do you see for "sf --version"?
I ask because I believe the sf cli recently switched from yarn to npm.

https://docs.npmjs.com/cli/v10/configuring-npm/npmrc gives info on where .npmrc files can live on your machine. 

If using an older sf version which still uses yarn, then see https://yarnpkg.com/configuration/yarnrc

**Comment by ar-srinivas** [comment]
@stephen-carter-at-sf I just reinstalled the latest cli and the current version is:
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.37.4",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Linux 6.2.0-1017-aws",
  "rootPath": "/home/ubuntu/sf",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.2 (core)",
    "@oclif/plugin-plugins 5.0.7 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.4 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.37.4 (core)",
    "apex 3.1.4 (core)",
    "auth 3.5.5 (core)",
    "data 3.2.5 (core)",
    "deploy-retrieve 3.5.6 (core)",
    "info 3.1.3 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.1 (core)",
    "org 4.0.4 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.1 (core)",
    "settings 2.1.2 (core)",
    "sobject 1.2.2 (core)",
    "source 3.2.3 (core)",
    "telemetry 3.1.18 (core)",
    "templates 56.1.1 (core)",
    "trust 3.5.4 (core)",
    "user 3.4.3 (core)"
  ]
}

**Comment by stephen-carter-at-sf** [comment]
https://docs.npmjs.com/cli/v10/configuring-npm/npmrc

Did you check the 4 possible locations to see if you have an npm config file that is using a different registry other than https://registry.npmjs.org/ ?

* per-project config file (/path/to/my/project/.npmrc)
* per-user config file (~/.npmrc)
* global config file ($PREFIX/etc/npmrc)
* npm builtin config file (/path/to/npm/npmrc)

Alternatively, you could add a ~/.npmrc file and have it say:
registry=https://registry.npmjs.org/

to force the registry and then try to install again.

**Comment by ar-srinivas** [comment]
Thank you @stephen-carter-at-sf, your response helped us to correct the npm and now we are able to install the plugin. But post installation the cli is failed to execute, giving the below error.

xxxx: $ sf -v
@salesforce/cli/2.40.7 linux-x64 node-v20.12.2
xxx:~$ sf plugins install @salesforce/sfdx-scanner@latest
You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.

Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/sfdx-scanner.
Finished digital signature check.
npm warn ERESOLVE overriding peer dependency
added 818 packages, removed 104 packages, and changed 14 packages in 28s
@salesforce/cli: Installing plugin @salesforce/sfdx-scanner@latest... installed v3.24.0
xxxx:~$ sf -v
    TypeError: invalid pattern

**Comment by stephen-carter-at-sf** [comment]
If you are having issues with the "sf" cli and not the sfdx-scanner plugin in particular, then please post your issue over at https://github.com/forcedotcom/cli

**Comment by ar-srinivas** [comment]
@stephen-carter-at-sf I posted it here as the issue is occurring only after installing the sf scanner plugin. If I don't install it, the cli works well. 

Thank you, I will post on the cli forum
