### ISSUE TITLE
[BUG] Error shown when class is defined in multiple files - using submodules in git repo

### ISSUE THREAD

**Issue by OrtooAdam** [forcedotcom/sfdx-scanner#1334]
We are scanning a git repo containing Salesforce Apex classes etc.. and this repo utilises the 'submodules' feature of git to allow us to reference other repos as modules to include in parent repo.
In this instance we had a submodule that itself included a submodule that was separately included in the parent thus

Parent Repo
Submodules
- includes submodule A
- Includes submodule B
- - submodule B also included a submodule, submodule A

Note. in this instance submodule A was some framework classes to support unit testing and so valid to be included in both.

Therefore 1 or more class files exist in multiple locations all under this package code base.

The scanner doesn't seem to like the same file appearing multiple times in source being scanned - we can't rectify this as the separate modules do need these classes.

**Documentation:**
Analyzing with Salesforce Graph Engine. See /Users/adam/.sfdx-scanner/sfge.log for details.... Error
ERROR running scanner:run:dfa:  Amoss_HttpRequestVerifier is defined in multiple files. Files=[/Users/Shared/Development/sf_dev/plugin-actions/submodules/framework/framework/default/amoss_main/default/classes/Amoss_HttpRequestVerifier.cls, /Users/Shared/Development/sf_dev/plugin-actions/submodules/amoss/force-app/amoss_main/default/classes/Amoss_HttpRequestVerifier.cls]

[sfge.log](https://github.com/forcedotcom/sfdx-scanner/files/14039869/sfge.log)

**Steps To Reproduce:**
Create a source file structure where you have included submodules and some classes appear in more than 1 submodule.

**Expected Behavior:**
The "packageDirectories" in the sfdx-project.json indicate an order - assuming Salesforce CLi deployment utilises this order then we would want any duplicate classes to be considered from "packageDirectories" bottom to top in importance - like how CSS and Java classpath resolves naming clashes.

**Screenshots:**
N/A

**Desktop:**
Mac Mini M1, Monterey 12.1

**Additional Context:**
Scanning in preparation for security review.

**Workaround:**
None

**Urgency:**
High - preparation for security review for appexchange listing

**Comment by johnbelosf** [comment]
hi @OrtooAdam - thanks for raising this. It might take us a while to prioritise this. If you are not able to run Graph Engine due to this issue, please don't let this hold you back from submitting for Security Review.

I would also suggest you use our new pmd-appexchange set of rules created specifically for Security Review, as it might help you find additional issues:
https://forcedotcom.github.io/sfdx-scanner/en/v3.x/architecture/pmd-engine/

**Comment by bobalicious** [comment]
@OrtooAdam - it sounds like you have a dependency tree that's flat (I.E. all the submodules that the top level requires are defined at the top level) but it's running the pull of your submodules from git recursively.

That is - you shouldn't have duplicate classes in the codebase.

It sounds like the solution would be:

* Do not retrieve the submodules recursively
* ONLY scan the files that are specified in the root project file
* As you say, resolve the order and only process the versions of the classes that would actually be deployed

**Comment by rmohan20** [comment]
This is working as designed. Graph Engine has [a known limitation](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/working-with-sfge/#limitations-of-salesforce-graph-engine) around handling multiple classes with the same name. We don't have a way to address this in the way Graph Engine is implemented today.

A workaround would be to trigger separate runs that have a different set of `--projectdir` values to avoid having multiple classes of the same name in the analysis space.
