### ISSUE TITLE
[BUG] Invoking `sf scanner rule list` without filter criteria doesn't return all rules

### ISSUE THREAD

**Issue by jmsfez** [forcedotcom/sfdx-scanner#1371]
Hello,

The following command returns only **216 rules**
`sf scanner rule list --json | grep engine | wc -l
`
While the following command returns the effective **839 rules**
`sf scanner rule list --engine "eslint, eslint-lwc, eslint-typescript, pmd, pmd-appexchange, retire-js, sfge, cpd" --json | grep engine | wc -l
`
So, it seems that **by default, when no engine are given, the scanner run list doesn't provide the exhaustive list of rules**.
It would be nice if you can fix that bug 😉

**Comment by johnbelosf** [comment]
Hi @jmsfez this is working as expected - sf scanner rule list returns the list of active & default rules you get when running sf scanner run and scanner run dfa.
We will clarify this in our docs.

You can always get a comprehensive list of rules per engine following your approach.
