### ISSUE TITLE
[False Result] - Assigning to a property called "key"

### ISSUE THREAD

**Issue by mattlacey** [forcedotcom/sfdx-scanner#1372]
### Salesforce Code Analyzer False Results Template

**Description:**
Scanner reporting use of hard-coded credentials

**Documentation:**

AvoidHardcodedCredentials	Remove hard-coded credentials from source code.	https://github.com/forcedotcom/sfdx-scanner/blob/dev/pmd-appexchange/docs/AvoidHardcodedCredentials.md

**False Results Report:**
The line of code triggering this is:

```
        this.key = '';
```
It's simply an Apex class property where key is being used as an identiier

**Steps To Reproduce:**

**Expected Behavior:**
Scanner should have no issues with the line of code in question

**Screenshots:**

**Desktop:**

Sonoma 14.3.1
Analyzer 3.21.0
@salesforce/cli/2.30.8 darwin-arm64 node-v20.11.1

**Comment by stephen-carter-at-sf** [comment]
For these cases, we are recommending to just add //NOPMD comment on the line where you know the key isn't a secret.
