### ISSUE TITLE
can not install the sfdx scanner[BUG]

### ISSUE THREAD

**Issue by singlebat** [forcedotcom/sfdx-scanner#1377]
### `scanner run` Issue Template

Fill out this template to submit your Code Analyzer issue.

**Description**:

I want to install the salesforce code analyzer .when I type the following command I got an error.
My salesforce CLI has been updated to the latest version . so does the vscode and nodejs.

PS C:\Users\xxx\Downloads\work\vscode\lws\lws> sfdx plugins:install @salesforce/sfdx-scan
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/sfdx-scanner.
Finished digital signature check.
Installing plugin @salesforce/sfdx-scanner@latest... failed
 »   Error: @salesforce/sfdx-scanner does not exist in the registry.

Please tell me what should I do to fix this.
**Documentation**:

**Steps To Reproduce**:

**Expected Behavior**:

**Screenshots**:

**Desktop**:

**Additional Context**:

**Workaround**:

**Urgency**:

**Comment by jfeingold35** [comment]
@singlebat , what version of `sf` are you running? If you run `sf update` and then `sf plugins install @salesforce/sfdx-scanner`, does that work?

**Comment by stephen-carter-at-sf** [comment]
Can you check to see if you have a .yarnrc or .nmprc file that is not pointing to npm registry?

**Comment by singlebat** [comment]
@jfeingold35 
it woked !  thank you so much, I never thought the reason would be the old version of CLI. since I will update CLI as soon as the reminder shows msg.

**Comment by singlebat** [comment]
> @singlebat , what version of `sf` are you running? If you run `sf update` and then `sf plugins install @salesforce/sfdx-scanner`, does that work?
