### ISSUE TITLE
[BUG]Get SyntaxError during scanner run

### ISSUE THREAD

**Issue by kumo2kumo** [forcedotcom/sfdx-scanner#1379]
**Description**:
**I scanned my code with Salesforce Code Analyzer for security review and got SyntaxError.**

run:  `sf scanner run --format=csv --outfile=CodeAnalyzerGeneral.csv --target="./" --category="Security"`
error:  `SyntaxError: Error parsing C:\Users\<username>\AppData\Local\sf\node_modules\@salesforce\sfdx-scanner\node_modules\simple-swizzle\package.json: Unexpected token '', ""... is not valid JSON`

**Steps To Reproduce**:
1. update latest version of the CLI, by ` sf update.`
2. install by `sf plugins install @salesforce/sfdx-scanner.`
3. change to the top-level directory of my code and metadata.
4. run` sf scanner run --format=csv --outfile=CodeAnalyzerGeneral.csv --target="./" --category="Security"`
5. got error  `SyntaxError: Error parsing C:\Users\<username>\AppData\Local\sf\node_modules\@salesforce\sfdx-scanner\node_modules\simple-swizzle\package.json: Unexpected token '', ""... is not valid JSON`

follwed by [salesforce guide](https://developer.salesforce.com/docs/atlas.en-us.248.0.packagingGuide.meta/packagingGuide/security_review_code_analyzer_scan.htm)

**Desktop**:
- OS : windwos 11
- Code Analyzer version: 3.21.0
- Salesforce CLI version: @salesforce/cli/2.30.8 win32-x64 node-v20.11.1
- node version: v20.11.1

**Workaround**:
- I tried doing it with a different project code and ran into the same error.
- The version of node was 18, so I upgraded it to v20.11.1.

**Comment by stephen-carter-at-sf** [comment]
Hello @kumo2kumo . I am unable to reproduce this error. Can you please first try updating to our latest-beta to see if the issue happens there as well. That is, do the following:

sf plugins uninstall @salesforce/sfdx-scanner
sf plugins install @salesforce/sfdx-scanner@latest-beta

then run your command.

If you still get an error, can you please copy/paste the contents of the C:\Users\<username>\AppData\Local\sf\node_modules\@salesforce\sfdx-scanner\node_modules\simple-swizzle\package.json file here as a comment.

**Comment by kumo2kumo** [comment]
Hi, @stephen-carter-at-sf. Thanks for your reply.
I did the following commands as you told me and it worked!

```
sf plugins uninstall @salesforce/sfdx-scanner
sf plugins install @salesforce/sfdx-scanner@latest-beta
```
Thank you very much for your help.

**Comment by stephen-carter-at-sf** [comment]
Great. Closing this issue then.
