### ISSUE TITLE
[BUG] InternalExecutionError on assignment of inherited instance variables from abstract class

### ISSUE THREAD

**Issue by jaelee125** [forcedotcom/sfdx-scanner#1406]
I'm not exactly sure what the issue is. SN_Constants class is a class we use to store constants. This class only has public static final String, Integer, Map, List, and Set.

Error and stacktrace: UnexpectedException: Undefined variable. key=mappingType, value=ApexStringValue{ value=Optional[Object]} ApexValue(ApexStringValue) {status=INITIALIZED, declarationVertex=ApexStringValue{ value=Optional.empty} ApexValue(ApexStringValue) {status=UNINITIALIZED, declarationVertex=Field{properties={FirstChild=false, BeginLine=50, Type=String, DefiningType_CaseSafe=sn_constants, LastChild=false, DefiningType=SN_Constants, EndLine=50, Name_CaseSafe=config_type_object, childIdx=24, BeginColumn=29, Name=CONFIG_TYPE_OBJECT}}, valueVertex=null, resolvedValues={}, returnedFrom=null, invocableExpression=null, method=null}, valueVertex=LiteralExpression{properties={FirstChild=true, BeginLine=50, DefiningType_CaseSafe=sn_constants, LastChild=false, DefiningType=SN_Constants, EndLine=50, Value=Object, childIdx=0, LiteralType=STRING, BeginColumn=50}}, resolvedValues={}, returnedFrom=null, invocableExpression=null, method=null}: com.salesforce.graph.symbols.MethodInvocationScope.updateVariable(MethodInvocationScope.java:114);com.salesforce.graph.symbols.AbstractClassInstanceScope.updateVariable(AbstractClassInstanceScope.java:129);com.salesforce.graph.symbols.PathScopeVisitor.updateVariable(PathScopeVisitor.java:190);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1005);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:744);com.salesforce.graph.vertex.AssignmentExpressionVertex.afterVisit(AssignmentExpressionVertex.java:37)

**Comment by jaelee125** [comment]
Map<String, Object> objectDefinition = new Map<String, Object>{
	'networkObject' => networkObjectAPIName,
	'objectLabel' => 'Document'
};

SN_MetadataWrappers.ObjectDefinitionWrapper objectDefinitionWrapper = new SN_MetadataWrappers.ObjectDefinitionWrapper(objectDefinition);

SN_MetadataWrapper Class:

public class ObjectDefinitionWrapper extends ObjectsAndFieldsDefinitionWrapper {
    public ObjectDefinitionWrapper(Map<String, Object> wrapperMap) {
    	    type = SN_Constants.CONFIG_TYPE_OBJECT;
	    networkObject = (String) wrapperMap.get(NETWORK_OBJECT_KEY);
            processExtendedData(wrapperMap);
    }
}

ObjectsAndFieldsDefinitionWrapper is an abstract class. It seems to flag the line type = SN_Constants.CONFIG_TYPE_OBJECT.

**Comment by jaelee125** [comment]
Adding any sort of engine directives in SN_MetadataWrapper does not seem to do anything

**Comment by jaelee125** [comment]
`public with sharing class SN_MetadataWrappers {
       
	public abstract class ObjectsAndFieldsDefinitionWrapper extends MetadataWrapper {		
		@AuraEnabled public String type;
		@AuraEnabled public String networkObject;
	}

	public class ObjectDefinitionWrapper extends ObjectsAndFieldsDefinitionWrapper {
	
		public ObjectDefinitionWrapper(Map<String, Object> wrapperMap) {
			type = SN_Constants.CONFIG_TYPE_OBJECT;
			networkObject = (String) wrapperMap.get(NETWORK_OBJECT_KEY);
		}
	}
}`

`SN_MetadataWrappers.ObjectDefinitionWrapper objectWrapper = new SN_MetadataWrappers.ObjectDefinitionWrapper(objectMap);`

The above fails. If I duplicate inherited instance variables in the class, it passes.

**Comment by jaelee125** [comment]
@sagar-j-sfdc Do you have any work arounds for this or any idea to get the engine directives to work for this issue?

**Comment by jaelee125** [comment]
@jfeingold35 Any update on this?

**Comment by jfeingold35** [comment]
Unfortunately, no updates at this time. We'll look into it and let you know once we have something. Thank you for your patience.

**Comment by jfeingold35** [comment]
@jaelee125 , we're able to reproduce. It looks like the problem is that the scope of the child class isn't automatically receiving the properties inherited from the parent class.
Unfortunately, the fix looks to be possibly non-trivial. We'll add it to our backlog, but in the meantime, if your workaround is unblocking you, we recommend continuing to use it.
