### ISSUE TITLE
[BUG] ApexFlsViolationRule on dynamic queries with values passed in as parameter

### ISSUE THREAD

**Issue by jaelee125** [forcedotcom/sfdx-scanner#1407]
ApexFlsViolationRule is flagged on this example code

public static List<SObject> exampleMethod(String exampleParam) {
    String dynamicQuery = 'SOME dynamic Query' + ' WHERE Name = :exampleParam';
    return Database.query(String.escapeSingleQuotes(dynamicQuery), AccessLevel.USER_MODE);
}

However, if you do queryWithBinds and pass in a Map with exampleParam, ApexFlsViolationRule is not flagged.

**Comment by stephen-carter-at-sf** [comment]
Ok, I verified that this seems to now be fixed with our latest-beta.

@jaelee125 Can you please install the following and try again:
sf plugins install @salesforce/sfdx-scanner@latest-beta

Will mark this as fixed for now.
