### ISSUE TITLE
[BUG] SF CLI Installation issue with NodeJS 20.12.2 on Windows

### ISSUE THREAD

**Issue by jag-j** [forcedotcom/sfdx-scanner#1442]
If you are trying to install SF CLI with NodeJS 20.12.2 on Windows, it would fail because of a known issue in CLI - https://github.com/forcedotcom/cli/issues/2822. A fix for this (and other spawn uses) was shipped in nightly last night and will be promoted to latest-rc later today (April 17th) by the CLI team.

It will be promoted to latest on April 24th.

**Comment by jiacheng-xu** [comment]
I have seen another issue after I updated NodeJS on Salesforce corp mac.

✗ node --version
v20.12.2
✗ npm install @salesforce/cli --global  
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/@salesforce
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@salesforce'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@salesforce'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/@salesforce'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /Users/[xxxx]/.npm/_logs/2024-04-23T18_17_27_917Z-debug-0.log

**Comment by jfeingold35** [comment]
SF-CLI has released their new version with a fix for this issue, thereby fixing us downstream from them. As such, we're closing this issue.
