### ISSUE TITLE
SyntaxError: Unexpected closing tag "div" scanner results html file 

### ISSUE THREAD

**Issue by chrzasz** [forcedotcom/sfdx-scanner#1554]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Scanner is generating html file with resuls but html file contains syntax error

### Output / Logs

```
[error] sf-code-scanner-results.html: SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (301:26)
[error]   299 | <body>
[error]   300 |     <h1 id="reportTitle">Salesforce Code Analyzer Report</h1>
[error] > 301 |         <div id="summaryChart"/></div>
[error]       |                                 ^^^^^^
[error]   302 |         <h4 id="summaryFiles"></h4>
[error]   303 |         <h4 id="summaryViolations"></h4>
[error]   304 |         <div class="fw-container">
```

### Steps To Reproduce

1. run scanner via cli: `sf scanner run --target="force-app" --outfile sf-code-scanner-results.html`
2. validate sytax error for div "summaryChart" `<div id="summaryChart"/></div>`

### Expected Behavior

no any html sytax errors in generated html file 

### Operating System

Windows 11

### Salesforce CLI Version

@salesforce/cli/2.51.6 win32-x64 node-v20.15.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.3.2

### Additional Context (Screenshots, Files, etc)

![image](https://github.com/user-attachments/assets/df877ffc-3ab9-4f85-8918-e4a9a13d9834)

### Workaround

Ignore generated by scanner html file in .prettierignore file of your project

### Urgency

Low

**Comment by stephen-carter-at-sf** [comment]
Thank you for bringing this to our attention.
