### ISSUE TITLE
[BUG] <Code analyzer generating empty file>

### ISSUE THREAD

**Issue by bhagyashreesawant13** [forcedotcom/sfdx-scanner#1557]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Code analyzer plugin from Visual Studio Code is generating empty file when command is run,

### Output / Logs

[output3.csv](https://github.com/user-attachments/files/16429002/output3.csv)
<img width="539" alt="image" src="https://github.com/user-attachments/assets/884da61a-2587-4ee2-b6e8-5686997da421">

### Steps To Reproduce

Code analyzer plugin from Visual Studio Code is generating empty file when below command is run,
sfdx scanner:run --target "C:\Program Files\Microsoft VS Code\bin\retrieve_09S9O000007JUzGUAW\classes\mbs_InquiryTriggerHandler.cls"  --format "csv" --outfile "C:\Users\b.eknath.sawant\.vscode\Bhagyashree\YELLOWDev\Yellow DEV\CodeResult\output3.csv"

### Expected Behavior

![Uploading image.png…]()
Empty file will be generated.

### Operating System

Windows 11 Enterprise

### Salesforce CLI Version

@salesforce/cli/2.45.6 win32-x64 node-v20.14.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.3.2  Uninstalled JIT Plugins: community 3.2.15 custom-metadata 3.3.11 dev 2.3.1 devops-center 1.2.13 env 3.0.30 functions 1.23.0 signups 2.3.6 @salesforce/sfdx-plugin-lwc-test 1.2.0

### Java Version

java 22.0.1 2024-04-16 Java(TM) SE Runtime Environment (build 22.0.1+8-16) Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

### Workaround

We retrieved the metadata from package.xml file in Microsoft VS code. When we received an empty file without any errors and only headers. 
After that we retrieved the metadata from workbench, and gave the exact location of generated files as Target but didnt work either.

### Urgency

Moderate

**Comment by jfeingold35** [comment]
@bhagyashreesawant13 , What's the bug here? When you specify an outfile, then that outfile will be empty if there are no violations.

**Comment by bhagyashreesawant13** [comment]
Hi Josh,

We ran the query on entire code.
Our code has violations but we are not able to generate the report via code
analyzer.
Kindly help us.

Thanks & Regards,
Bhagyashree Eknath Sawant

**Comment by jfeingold35** [comment]
@bhagyashreesawant13 , do you get the expected violations if you run against only a subset of your files?

**Comment by bhagyashreesawant13** [comment]
Hi Josh,

No even on the subset of files, code analyzer is generating empty file only.

Thanks & Regards,
Bhagyashree Eknath Sawant

**Comment by jfeingold35** [comment]
@bhagyashreesawant13 , how long does it take to run? And can you run it against a single file, or is it not working even with just one file?

**Comment by bhagyashreesawant13** [comment]
Hi Josh,

It takes hardly 2-4 minutes to run the job and yes it generates empty file
for single code as well.

Thanks & Regards,
Bhagyashree Eknath Sawant

**Comment by stephen-carter-at-sf** [comment]
@bhagyashreesawant13 Can you help explain exactly what you believe should be the intended behavior here? And can you better explain your repro steps exactly? Lastly, have tried running code analyzer independent of using VSCode? Is this just a VS Code extension issue?

**Comment by bhagyashreesawant13** [comment]
Hi Josh,

I need to check with business if I am allowed to share the code files.
Also, we know about the violations because a security audit was performed
for salesforce.

Thanks & Regards,
Bhagyashree E Sawant.

**Comment by bhagyashreesawant13** [comment]
Hi Stephen,

We are expecting to get some error/warnings in the existing code for our
org.
As we already have an audit file generated which has all the data showing
lack of best practices resulting in warnings or errors.
Now we are working on fixing those issues, but want to be able to see if we
are facing any errors after making the changes.
So we can run a query on code analyzer which is expected to
generate results showing any existing violations in our code.

Question, how to run an independent code analyzer? We are using VS code
extension only.
Thanks & Regards,
Bhagyashree E Sawant.

**Comment by stephen-carter-at-sf** [comment]
In order to run the VS Code Extension, you should have had to install the cli. To confirm, check from a terminal by running the command
```
sf plugins
```
and you should see
```
@salesforce/sfdx-scanner X.Y.Z
```
where `X.Y.Z` is something like `4.4.0`.
This means you have the cli installed. If so, then try running your command with:
```
sf scanner run <YOUR_ARGUMENTS_HERE>
```
where the documentation of the run command is found over at: https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/run.html

**Comment by bhagyashreesawant13** [comment]
Hi Stephen,

Yes I have CLI installed and I have run above mentioned commands.
Also ran the query as per the article but it is generating empty file only.
No idea what to do now. Is there any other way I can check my org code for
warnings?

Thanks & Regards,
Bhagyashree Eknath Sawant

**Comment by stephen-carter-at-sf** [comment]
What do you mean it is generating an empty file? Can you please give me the exact command you are running from the terminal and then give me a copy of the file (or at least give a screen shot of it).

**Comment by bhagyashreesawant13** [comment]
Hi Stephen, 
I have attached the screenshot from the file which was generated at the time of security audit.
We are fixing those changes and want to generate the report on the org code to know if the violations from the original report have reduced or not with the help of code analyzer.
We are expecting such report to be produced by code analyzer.
<img width="959" alt="approval process errors from code analyzer report" src="https://github.com/user-attachments/assets/759439a1-cadf-46ea-a87e-82a86c471965">

Please let me know if you have any more questions.

**Comment by bhagyashreesawant13** [comment]
Yes Stephen, I am expecting code analyzer to find violations. We have received this report from Salesforce support.

**Comment by stephen-carter-at-sf** [comment]
I'm sorry, I feel like we are miscommunication over and over here. First you said your Salesforce code analyzer results were empty. Now you are showing me violations... so I'm assuming those violations are not coming from Salesforce Code Analyzer. So what tool are they coming from?

Can you please write up a complete summary of:
* What exactly you are doing (outline each step)
* What behavior are you getting that you do not expect... and tell us why you don't expect that behavior
* What behavior do you expect

If you are using other tools (in this case... if you are expecting violations that Code Analyzer is not getting)... tell us where you are getting these violations from.

You say you received a report form Salesforce support? Did they give you these violations? What was the support request for? Can you link to the support request?

**Comment by stephen-carter-at-sf** [comment]
Closing issue since the product is working as expected and we haven't heard back from you in a week.
