### ISSUE TITLE
Error (1): spawn ENOTDIR with any command 

### ISSUE THREAD

**Issue by azanatta** [forcedotcom/sfdx-scanner#1561]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Any command I launch (with run or run dfa) I get 
Error (1): spawn ENOTDIR

I have installed the sfdx-scanner 4.4.0 using 
sf plugins install @salesforce/sfdx-scanner  
sf cli version:
@salesforce/cli/2.52.6 darwin-arm64 node-v20.15.1

I have also tried to downgrade first to 4.3.2, then to 4.3.0 - nothing changes.

Example of commands run are:
sf scanner run --target ./sfdx-source/cnx/main/default/classes/ConfigurationHandler.cls --outfile results.html
sf scanner run --target ./sfdx-source/cnx/ --target "/classes/" --json
sf scanner run --format csv --target './**/*.cls' --severity-threshold 3 --outfile 'apexScanResults.csv' 
sf scanner run  --projectdir .    
sf scanner run dfa --target classes --projectdir "." --outfile results.html  

All commands were tried with variations (with and without quotes/double quotes)

### Output / Logs

 ›   Warning: Plugin @salesforce/sfdx-scanner (4.4.0) differs from the version specified by sf (4.3.2)
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): spawn ENOTDIR

### Steps To Reproduce

1. Install scanner plugin (sf plugins install @salesforce/sfdx-scanner )
2. Run any "sf scanner run" command

### Expected Behavior

Receive a more insightful error output.

### Operating System

MacOS Sonoma 14.5

### Salesforce CLI Version

@salesforce/cli/2.52.6 darwin-arm64 node-v20.15.1

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.4.0

### Urgency

High

**Comment by stephen-carter-at-sf** [comment]
@azanatta Can you try a few things.

First try to first do export `DEBUG=oclif*` before running the command and then run again to see if it gives you a stack trace.

If not, then look inside of your ~/.sfdx scanner folder to see if the log files contain a stack trace for the error.

Lastly, please tell me what your java version is and what the path is:
```
java --version
where java
echo $JAVA_HOME
```
and tell me if there is a `'javaHome'` value inside of your `~/.sfdx-scanner/Config.json` file

**Comment by stephen-carter-at-sf** [comment]
Closing this issue since we haven't heard back from you and we are unable to reproduce. @azanatta If you still need help, then please answer my questions above and reopen this issue.
