### ISSUE TITLE
[BUG] Path evaluation timed out after 900000 ms

### ISSUE THREAD

**Issue by arnabmst** [forcedotcom/sfdx-scanner#1570]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Running dfa command I get Path evaluation timed out after 900000 ms for a number of paths
[CodeAnalyzerDFA.csv](https://github.com/user-attachments/files/16595563/CodeAnalyzerDFA.csv)

### Output / Logs

[sfge-08-12-2024-1.log.gz](https://github.com/user-attachments/files/16595593/sfge-08-12-2024-1.log.gz)

### Steps To Reproduce

Initial Script :- sf scanner run dfa --format csv --outfile CodeAnalyzerDFA.csv --target ./ --projectdir ./ --category Security
After modification :- sf scanner run dfa --format csv --outfile CodeAnalyzerDFA.csv --target ./ --projectdir ./ --category Security --pathexplimit -1 --rule-thread-count 2 --rule-thread-timeout 300000

### Expected Behavior

Timed out error will not come

### Operating System

macOS Ventura 13.3.1 (a)

### Salesforce CLI Version

@salesforce/cli/2.50.6 darwin-arm64 node-v20.15.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.3.2

### Java Version

java version "17.0.11" 2024-04-16 LTS

### Additional Context (Screenshots, Files, etc)

[CodeAnalyzerDFA.csv](https://github.com/user-attachments/files/16595693/CodeAnalyzerDFA.csv)
[sfge-08-12-2024-1.log.gz](https://github.com/user-attachments/files/16595694/sfge-08-12-2024-1.log.gz)

### Workaround

We initially ran the script "sf scanner run dfa --format csv --outfile CodeAnalyzerDFA.csv --target ./ --projectdir ./ --category Security"
We we got the error we followed this [document](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/working-with-graph-engine.html) and updated the script to "sf scanner run dfa --format csv --outfile CodeAnalyzerDFA.csv --target ./ --projectdir ./ --category Security --pathexplimit -1 --rule-thread-count 2 --rule-thread-timeout 300000" and still got the error

### Urgency

Critical

**Comment by jag-j** [comment]
Hello @arnabmst: This is a known issue with large/complex codebases and is being tracked as part of https://github.com/forcedotcom/sfdx-scanner/issues/1294. If this is blocking your App Exchange security review, please mark this as a 'false positive' and link this issue. Thank you. I will close this issue for now.
