### ISSUE TITLE
[False Result] ApexFlsViolationRule - Defect issues that CodeAnalyzer does not recognize

### ISSUE THREAD

**Issue by OrangeHarry** [forcedotcom/sfdx-scanner#1581]
### Bug Description

Hello good afternoon.
we are preparing to upload the ISV package as 2GP Packaged and register it on App Exchange.

The code below is how we check FLS.

Util.cls
/**
* @FLSCheck
* @return true, false
*/
public static Boolean fieldsUpdateableCheck(SObject record) {
    if (Util.isEmpty(record)) return false;
    return fieldsCheck(record, 'isUpdateable');
}

/**
* @FLSCheck
*/
public static Boolean fieldsCheck(SObject record, String checkMethod) {
    if (Util.isEmpty(record)) return false;

    // key : Field API Name, Value : Field value
    Map objectMap = record.getPopulatedFieldsAsMap();
    System.debug(LoggingLevel.DEBUG, 'objectMap >> ' + objectMap);
    Set fieldSet = objectMap.keySet();
    // Id Value Remove
    fieldSet.remove('Id');

    List fieldDescList = new List();
    Schema.DescribeFieldResult fieldDesc;
    for (String fieldName : fieldSet) {
        fieldDesc = record.getSObjectType().getDescribe().fields.getMap().get(fieldName).getDescribe();
        fieldDescList.add(fieldDesc);
    }

    for (Schema.DescribeFieldResult field : fieldDescList) {
        // checkMethod ('isCreateable', 'isUpdateable', 'isUpsertable')
        switch on checkMethod {
            when 'isCreateable' {
                if (!field.isCreateable()) {
                    return false;
                }
            }
            when 'isUpdateable' {
                if (!field.isUpdateable()) {
                    return false;
                }
            }
            when 'isUpsertable' {
                if (!field.isCreateable() && !field.isUpdateable()) {
                    return false;
                }
            }
        }
    }
    return true;
}

Below is the method used in the method that performs DML. (example)

List<PartsOrderLineItem__c> updateRecordList= new List<PartsOrderLineItem__c>();
PartsOrderLineItem__c item;
for (PartsOrderLineItemWrapper wp : wpList) {
            item = new PartsOrderLineItem__c();
            item.Id = wp.id;
            item.Result__c = isSuccess ? 'Success': 'Error';
            item.StockAvailability__c = wp.stockAvailability;
            item.Message__c = wp.message
            item.QuantityRequested__c = wp.quantityRequested;
            updateRecordList.add(item);
}

if (!updateRecordList.isEmpty()) {
    if (Util.fieldsUpdateableCheck(updateRecordList[0])) {
        Database.update(updateRecordList, AccessLevel.USER_MODE);
    } else {
        throw new AuraHandledException(System.Label.COM_MSG_FIELDS_PERMISSION_VALIDATION); // You do not have field permissions for record modification and creation.
    }
}

The fieldsCheck() method we created in the Util class extracts fields defined in actual use and performs a field-level permission check. Redundant code can be reduced and management and maintenance are much better.
The functional test was completed, but CodeAnalyzer is a static analysis tool, so it spits out an ApexFlsViolationRule defect saying that it did not check field permissions for that part.

FLS validation is missing for [Update] operation on [PartsOrderLineItem__c] with field(s) [Result__c,StockAvailability__c,Message__c,QuantityRequested__c]

I created a method to check field permissions, but I can't use it.
We have more than 400 such methods.
If possible, I would like to use it as a utility.
Also, I understand that you can submit data for areas where there are clearly no problems.

### Output / Logs

FLS validation is missing for [Update] operation on [PartsOrderLineItem__c] with field(s) [Result__c,StockAvailability__c,Message__c,QuantityRequested__c]

Database.update(updateRecordList, AccessLevel.USER_MODE);

### Steps To Reproduce

The method is
Permissions are checked based on Schema.DescribeFieldResult. 

Boolean fieldupdatebleCheck = true;
List<Schema.DescribeFieldResult> fieldDescList = new List<Schema.DescribeFieldResult>{
                PartsOrderLineItem__c.Result__c.getDescribe();
                PartsOrderLineItem__c.StockAvailability__c.getDescribe();
                PartsOrderLineItem__c.Message__c.getDescribe();
                PartsOrderLineItem__c.QuantityRequested__c.getDescribe()
        };
        
for (Schema.DescribeFieldResult field : fieldDescList ) {
            if(!field.isUpdateable()){
                fieldupdatebleCheck = false;
                return;
            }
 }
        
 In the same way as above 
ApexFlsViolationRule has passed.
So, I tried using the same method to change the method of extracting fields and checking permissions instead of directly listing the fields and checking permissions, but the ApexFlsViolationRule flaw occurred again.     

### Expected Behavior

As a result of actually testing the above code, the permission check is being performed normally.
[Result__c, StockAvailability__c, Message__c, QuantityRequested__c]

Only the four fields defined above are extracted and permissions are checked.

However, CodeAnlyzer says that the FLS permission was not checked because it was not directly indicated in the code.

### Operating System

Windows 11 Pro / 23H2 / 22631.4037

### Salesforce CLI Version

@salesforce/cli/2.53.6 win32-x64 node-v20.11.1

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.4.0

### Java Version

openjdk version "11.0.17" 2022-10-18 LTS

### Urgency

High

**Comment by jag-j** [comment]
Hello @OrangeHarry, Salesforce Graph Engine does more than static analysis since it uses data-flow analysis. However, we're still uncertain why it's flagging the ApexFlsViolationRule in your situation. We suspect that the issue might be related to the switch statements in your fieldsCheck() function. Could you try replacing them with if-else statements and see if that resolves the problem? Please keep us updated. Thank you!

**Comment by jag-j** [comment]
Hello @OrangeHarry, this does look like false positive. Can you mark this as false positive in your security review? Thanks and let us know if you have any other questions. I'll mark this as closed for now.

**Comment by OrangeHarry** [comment]
Thanks for checking @jag-j. I could document it as a false positive, but I'm worried because there are about 400 ways to do it.

I have a question. Is documenting it as a false positive just submitting it as a document, or do I have to add logic in my code to bypass CodeAnlyzer?
