### ISSUE TITLE
[False Result] Graph engine doesnt work with Null coalesce operator

### ISSUE THREAD

**Issue by TachyonicSpace** [forcedotcom/sfdx-scanner#1608]
### Bug Description

in our codebase, we are getting an error when trying to use the Graph engine. the code at the lines below is the following: ownerId = contact.deptOwner__c ?? '0056T000008NJT2QAO',
inside a case constructor. when getting this error and looking at the errors below, it seems it thinks this is supposed to be a ternary operator and not a Coalesce operator.

### Output / Logs

2024-08-27 13:04:35.596 [error] Graph engine encountered compilation errors. Fix the errors in /*Class Path Here*/ and retry., Caused by:
Invalid syntax at 237:62. (Unexpected token '?'.)
Invalid syntax at 237:84. (Expecting ':' but was: ',')
Invalid syntax at 245:14. (Extra ';', at ')'.)

### Steps To Reproduce

-have a Coalesce operator in one of the methods in my code base (not necessarily the file i try to run the command from).
-try to run the Graph engine command
-error occurs while it is running

### Expected Behavior

i expect it to notice that Feature of the apex language, and not think its a malformed ternary operator

### Operating System

Windows 11

### Salesforce CLI Version

@salesforce/cli/2.13.9 win32-x64 node-v18.15.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 3.17.0 (3.17.0)

### Java Version

java version "17.0.7" 2023-04-18 LTS

### Urgency

Moderate

**Comment by stephen-carter-at-sf** [comment]
You are using an old version of our @salesforce/sfdx-scanner plugin that did not support the newer apex functionality. Please upgrade to v4+ with the following commands:
```
sf update
sf plugins install @salesforce/sfdx-scanner@latest
```
