### ISSUE TITLE
[False Result] False positive FLS in DFT Report

### ISSUE THREAD

**Issue by JayMalde** [forcedotcom/sfdx-scanner#1624]
### Bug Description

I have written a Class which checks for CRUD FLS check and performs DML Operation.

Once I run the DFT Scan Command it gives me following on every DML
Same Code is not having any issues in Checkmarx Code Scanner.

ApexFlsViolationRule: FLS validation is missing for [INSERT] operation on [Log__c] with field(s) [Exception_Message__c,Title__c,Unique_Identifier__c].

I have attached the class to reproduce.
[Dml.txt](https://github.com/user-attachments/files/16996808/Dml.txt)

### Output / Logs

ApexFlsViolationRule: FLS validation is missing for [INSERT] operation on [Log__c] with field(s) [Exception_Message__c,Title__c,Unique_Identifier__c].

### Steps To Reproduce

1. Use following class to perform DML
2. Run DFT Scan

### Expected Behavior

It should give something like this
ApexFlsViolationRule: FLS validation is missing for [INSERT] operation on [Log__c] with field(s) [Exception_Message__c,Title__c,Unique_Identifier__c].

### Operating System

Windows 11

### Salesforce CLI Version

v18.16.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

4.4.0

### Java Version

java 17.0.9 2023-10-17 LTS

### Additional Context (Screenshots, Files, etc)

[Dml.txt](https://github.com/user-attachments/files/16996832/Dml.txt)

### Workaround

I was not able to found any workaround.

### Urgency

Critical

**Comment by jfeingold35** [comment]
@JayMalde , I'm able to reproduce this, but it resolves when I change the `Database.insert()` call to an `insert as user`. Does that resolve the issue on your end?

**Comment by JayMalde** [comment]
@jfeingold35 , Josh I was able to resolve the issue. Thanks for the help.
