### ISSUE TITLE
[False Result] Unable to invoke the rule "AvoidLmcIsExposedTrue" for a Lightning Message Channgel

### ISSUE THREAD

**Issue by abhisheksaxena7** [forcedotcom/sfdx-scanner#1654]
### Have you verified this is Salesforce Code Analyzer specific?

Yes

### Description

I am trying to run a scan with the PMD-Appexchange engine, on a metadata of type [LightningMessageChannel](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_lightningmessagechannel.htm) where I know there is a violation of the rule: [AvoidLmcIsExposedTrue](https://github.com/forcedotcom/sfdx-scanner/blob/dev/pmd-appexchange/docs/AvoidLmcIsExposedTrue.md). 

Here is the sample file which has the violation:
```
<?xml version="1.0" encoding="UTF-8"?>
<LightningMessageChannel xmlns="http://soap.sforce.com/2006/04/metadata">
    <masterLabel>SampleMessageChannel</masterLabel>
    <isExposed>true</isExposed>
    <description>This is a sample Lightning Message Channel.</description>
</LightningMessageChannel>
```
This sample has been taken from the Sample given on the [Metadata API Guide for LightningMessageChannel](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_lightningmessagechannel.htm)
 
The last version of Salesforce Code Analyzer where I am able to get the violation is version 3.26.0 of Salesforce Code Analyzer, I am unable to run it on any 4.x versions of Salesforce Code Analyzer.

### Output / Logs

It says, no rule violations found.
![image](https://github.com/user-attachments/assets/6f387da0-33dd-4a9d-94f9-e237ed24de1a)

### Steps To Reproduce

1. Install the latest v4.6.0 version of Salesforce Code Analyzer.
2. Create a sample LightningMessageChannel component in your source directory
    ![image](https://github.com/user-attachments/assets/fdad53fc-7858-4c47-8a6e-d093217e0308)
3. Run `sf scanner run --engine pmd-appexchange --target ./`

### Expected Behavior

Get a violation from pmd-appexchange engine, like it used to throw with versions until 3.26 like following
![image](https://github.com/user-attachments/assets/b23e7cd0-5dbf-4fc4-805d-06a93af48dca)

### Operating System

MacOS Ventura 13.5.2

### Salesforce CLI Version

@salesforce/cli/2.62.6 darwin-arm64 node-v20.17.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner@4.6.0 (latest)

### Additional Context (Screenshots, Files, etc)

1. [The Test you have in the repo](https://github.com/forcedotcom/sfdx-scanner/blob/821304415447671faaa026717166dd1f0388cdeb/test/commands/scanner/run.filters.test.ts#L49) for this rule, [is running on .object file,](https://github.com/forcedotcom/sfdx-scanner/blob/dev/test/code-fixtures/projects/pmd-appexchange-test-app/objects/unclean.object) **this is incorrect**, and this is likely why the tests didn't fail for this issue.
2. When I create the same file unclean.object in my repo and then run it, I can see the violation now.
![image](https://github.com/user-attachments/assets/fc9771c8-0463-4cd3-8bb5-a788711477b8)
3. The violation should be coming in for the LightningMessagingChannel file instead and **NOT** for the object file.
![image](https://github.com/user-attachments/assets/61b0d4cb-79a3-4fe6-86cb-c467d26dc66a)

### Workaround

Use the Salesforce Code Analyzer version 3.26
![image](https://github.com/user-attachments/assets/7824b840-e80f-45c8-b3a8-ea132df71679)

### Urgency

Moderate

**Comment by stephen-carter-at-sf** [comment]
Thanks for reporting this issue. Let me get in touch with the developer of this rule and see what they say. Will report back here when I get more info.

**Comment by rrajaram-salesforce** [comment]
I can confirm this is a bug. I'll work on a fix for this.

**Comment by stephen-carter-at-sf** [comment]
The fix for this will go out with @salesforce/sfdx-scanner@4.7.0 to be released this upcoming tuesday
