### ISSUE TITLE
[BUG] InternalExecutionError - Graph Engine identified your source and sink

### ISSUE THREAD

**Issue by aleksaQuadrix** [forcedotcom/sfdx-scanner#1667]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

I've ran the analyzer to prepare my code for AppExchange Security Review, however, I've been getting this: 
"2","3","C:\Projects\[]\sync_streamer\force-app\main\default\classes\SyncSettingsController.cls","42","37","SyncSettingsController","getMetadataSettingsOptions","","","","InternalExecutionError","Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: Did not expect NOT_A_MATCH when ranking parameter match. parameterType = List<String>, type = OrderedTreeSet{internalList=[NULL, Object]}: com.salesforce.graph.ops.TypeableUtil.rankParameterMatch(TypeableUtil.java:211);com.salesforce.graph.vertex.Typeable.rankParameterMatch(Typeable.java:41);com.salesforce.graph.ops.MethodTypeMatchUtil.getMatchRank(MethodTypeMatchUtil.java:191);com.salesforce.graph.ops.MethodTypeMatchUtil.parameterTypesMatch(MethodTypeMatchUtil.java:136);com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:358);com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:158)","https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/apexflsviolation-rule.html","InternalExecutionError","sfge"

### Output / Logs

"2","3","C:\Projects\[]\sync_streamer\force-app\main\default\classes\SyncSettingsController.cls","42","37","SyncSettingsController","getMetadataSettingsOptions","","","","InternalExecutionError","Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: Did not expect NOT_A_MATCH when ranking parameter match. parameterType = List<String>, type = OrderedTreeSet{internalList=[NULL, Object]}: com.salesforce.graph.ops.TypeableUtil.rankParameterMatch(TypeableUtil.java:211);com.salesforce.graph.vertex.Typeable.rankParameterMatch(Typeable.java:41);com.salesforce.graph.ops.MethodTypeMatchUtil.getMatchRank(MethodTypeMatchUtil.java:191);com.salesforce.graph.ops.MethodTypeMatchUtil.parameterTypesMatch(MethodTypeMatchUtil.java:136);com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:358);com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:158)","https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/apexflsviolation-rule.html","InternalExecutionError","sfge"

### Steps To Reproduce

I just ran the dfa command to analyze my project code as it was described in the documentation.

### Expected Behavior

No issues

### Operating System

Windows 7

### Salesforce CLI Version

2.51.6

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner (4.7.0)

### Java Version

java version "18.0.1.1" 2022-04-22

### Urgency

High

**Comment by jfeingold35** [comment]
Closing this individual issue, as it is one of the broad categories of issue being tracked with #1497
