### ISSUE TITLE
Enable Automated Code Reviews (using free Codacy.com) on this repo

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-scanner#177]
@jbartolotta-sfdc / @rmohan20  I hope you recall me showing you Codacy.com. An online service that mimics the sfdx-scanner architecture in the cloud. I told you that I use it everywhere. You where interested to learn more about the abstractions and concepts they have used to build a facade that works on multiple languages and multiple engines.

I recommend you using Codacy.com yourself for this repo (its free forever for Open-source). It supports basically all the languages you use and could benefit the quality of this repo.

I am happy to help any admin of your repo to configure this. It will not take more than 30m.

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann thanks for the suggestion, I will have a look. We are currently dogfooding the scanner on parts of itself, but need to increase the coverage to include the Java code.

**Comment by rsoesemann** [comment]
@jbartolotta-sfdc those engines and languages are supported and (fine tunable) in Codacy https://docs.codacy.com/related-tools/engines/

**Comment by rsoesemann** [comment]
I didn't ask for a totally obscure and unrelated feature. Closed without any explanation?! @ranekere-sfdc @jbartolotta-sfdc

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann  - my apologies. @ranekere-sfdc is our scrum master and trying to keep the issues list tidy. I told him this could be closed since it was a process suggestion that I'm looking into and not a feature request that needs to be tracked. 
 
We will do a better job of explaining why we close out an issue in the future.
