### ISSUE TITLE
Expectations for upgrades?

### ISSUE THREAD

**Issue by henrymzhaoGS** [forcedotcom/sfdx-scanner#180]
Hello! I'm planning to integrate this plugin into our existing CI CD process, but I have a question regarding version upgrades.

Seeing as PMD is currently on version 6.26.0, and the plugin is currently running 6.22.0, what is the expectation for version increments in the future? Will the plugin update to include every major release (ie. 7.0.0 which is releasing soon), or how are version upgrades considered/rolled out?

The same question goes for ESLint version upgrades as well.

Thanks for the great plugin and your time in answering the question!

**Comment by jbartolotta-sfdc** [comment]
@henrymzhaoGS thanks for the question.

The Scanner will do its best to follow the Semantic Versioning model, quoting [semver.org](http://semver.org/)

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards compatible manner, and
> 3. PATCH version when you make backwards compatible bug fixes.
> 

**Upgrading Dependencies**
***Engines*** will be upgraded in a similar manner to the main code base. Our goal is to ship the most recent engine version that complies with the Semantic Versioning conventions.

1. A MAJOR version Scanner release ***may*** upgrade to a newer major version of an engine
2. A MINOR version Scanner release ***may*** upgrade to a newer minor version of an engine
3. A PATCH version Scanner release ***may*** upgrade to a newer patch version of an engine

***Dependencies*** not directly exposed ***may*** be upgraded independent of any Semantic Versioning convention as long as they don’t change the behavior of the Scanner.

**Situations that may delay upgrading to a newer engine version**
1. Known issues with the newer engine version that cause a regression
2. Incompatible breaking changes which need to be addressed before upgrading

**Situations where the Scanner may break the Semantic Versioning conventions**
We will do our best to communicate these in advance when possible.
1. A security vulnerability fix that is only available in a Semantic Versioning incompatible manner

There was an issue with PMD 6.24 that kept us from updating, but that issue has been fixed. The upgrade to 6.26 should occur in a Scanner 2.x release. The earliest possible upgrade to Eslint 7 would occur in the Scanner 3.x release.

Let us know if there are particular features in the newer versions that you are reliant upon and we can see about increasing priorities.

**Comment by henrymzhaoGS** [comment]
Hey, @jbartolotta-sfdc thanks so much for your response, that made a lot of sense!

We're not particularly reliant on an exact version but just wanted to understand what the plan was regarding future version upgrades so we can plan accordingly. Thanks again for answering my question!
