### ISSUE TITLE
@W-8105674@ Documentation says it uses PMD 6.23.0 but from output it says 6.22.0

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/sfdx-scanner#213]
How does Salesforce CLI Scanner is planned in terms of keeping PMD updated? 

As a developer, if I want to use the latest jar from PMD, how would i approach it?

When I run `sfdx scanner:run` the output shows the engine is `pmd-6.22.0`.

**Comment by jbartolotta-sfdc** [comment]
@msrivastav13 thanks for your question, sorry that the documentation is wrong, we will fix this. 

We plan to upgrade to PMD 6.27.0 in the next couple of weeks. There currently isn't a way for users to specify a different version of the scanner.

The following issue describes our upgrade strategy https://github.com/forcedotcom/sfdx-scanner/issues/180

**Comment by msrivastav13** [comment]
@jbartolotta-sfdc Thanks for the response. Looking forward to the latest version in the next 2 weeks.

**Comment by jbartolotta-sfdc** [comment]
Closing, this has been fixed.
