### ISSUE TITLE
@W-8117190@ engines.eslint-lwc.disabled value in Config.json gets overwritten in Windows and Linux

### ISSUE THREAD

**Issue by rmohan20** [forcedotcom/sfdx-scanner#220]
> ℹ️ **This is a known-issue and we are in the process of fixing it.**

In Scanner v2.2.0, we've added `eslint-lwc` as a new engine to execute rules related to Lightning Web Components. At this point, by default, eslint-lwc engine is disabled and we are allowed to enable this by modifying `~/.sfdx-scanner/Config.json`. 
However, we notice that the `engines.eslint-lwc.disabled` goes back to `true` when we invoke a scanner command.
Also, this overwrite doesn't happen for any other property in `Config.json`.

## Current workaround to invoke eslint-lwc
Use scanner command with `--engines` option to specifically use `eslint-lwc`. For example, we can do:
```
sfdx scanner:run --target <target_files> --engines eslint-lwc
```
Fyi, the `--engines` can take a comma separated list of one or more from: `pmd`, `eslint`, `eslint-typescript`, `eslint-lwc`

**Comment by ranekere-sfdc** [comment]
This issue was resolved in v2.3.0
