### ISSUE TITLE
Make it an official Github scanner

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-scanner#239]
[GitHub recently announced](https://github.blog/2020-10-05-announcing-third-party-code-scanning-tools-static-analysis-and-developer-security-training/) its scanner plugin architecture and 3 commercial scanner for Salesforce already support it. It would be great if the CLI Scanner would become a forth open and free option.

**Comment by jefersonchaves** [comment]
@rsoesemann: given the GitHub Code Scanning is available to open-source and Enterprise (not for Teams subscriptions), would it be worth to allow this option but not fully committing to that allowing more people to use it?

**Comment by FeldhackerChrisPFG** [comment]
+1

**Comment by rsoesemann** [comment]
@rmohan20 maybe you should join forces with @mitchspano who currently works on this. What he already has looks great
https://github.com/mitchspano/sfdx-scan-pull-request

**Comment by rmohan20** [comment]
@rsoesemann Thanks for calling this out.
@mitchspano Thanks so much, this looks like a great utility! I'll try it out as well.

**Comment by johnbelosf** [comment]
Just to add to the list, we also have this GitHub action from @packocz:

https://github.com/packocz/sfdx-code-review-action

**Comment by johnbelosf** [comment]
We have a couple of GitHub Actions available (thank you community!). Please open a new issue if there is more specific feedback to share.

**Comment by rsoesemann** [comment]
@johnbelosf you closed this, but I see @rmohan20 work on something like this in Github. Can we expect an official Pipeline by Salesforce? Whatabout Bitbucket and other providers?
