### ISSUE TITLE
Cannot install plugin using npm package

### ISSUE THREAD

**Issue by amarek-craftware** [forcedotcom/sfdx-scanner#240]
I've tried to install the package using npm to test this plugin, however, I'm getting errors like below

` npm install -g @salesforce/sfdx-scanner
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> dtrace-provider@0.6.0 install /usr/lib/node_modules/@salesforce/sfdx-scanner/node_modules/dtrace-provider
> node scripts/install.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/@salesforce/sfdx-scanner/node_modules/dtrace-provider/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

> @salesforce/sfdx-scanner@2.2.1 postinstall /usr/lib/node_modules/@salesforce/sfdx-scanner
> ts-node  -e "require('./lib/lib/postinstall').execute()"

sh: ts-node: command not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 (node_modules/@salesforce/sfdx-scanner/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @salesforce/sfdx-scanner@2.2.1 postinstall: `ts-node  -e "require('./lib/lib/postinstall').execute()"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @salesforce/sfdx-scanner@2.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-07T06_58_07_766Z-debug.log
`
Maybe there are some dependencies needed but I cannot find it anywhere in the documentation.

**Comment by jfeingold35** [comment]
@amarek-craftware , the scanner is intended to be used with Salesforce CLI. You can install that by following the instructions [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm), and then install the scanner plugin with `sfdx plugins:install @salesforce/sfdx-scanner`. Please let us know if you still have any problems.

**Comment by amarek-craftware** [comment]
Hi @jfeingold35 ,
I was installing a package using npm, but it was not working as in the previous comment.
I've installed the plugin again on Windows and then using command 
sfdx plugins:install @salesforce/sfdx-scanner
It solves the issue. The plugin is now working.

**Comment by amarek-craftware** [comment]
Plugin is working as expected after installing via sfdx console.
