### ISSUE TITLE
@W-8046146@ Digitally Sign the Plugin

### ISSUE THREAD

**Issue by jefersonchaves** [forcedotcom/sfdx-scanner#241]
I really like the plugin, but I think it will help if is digitally signed.

It would avoid the prompt:
`This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?`

If there is anything I could help with, more than glad to assist.

**Comment by jbartolotta-sfdc** [comment]
@jefersonchaves this is in progress.

**Comment by jefersonchaves** [comment]
That is great news @jbartolotta-sfdc. Thanks for the update.

Is there a target release where this is planned to be done?

**Comment by jbartolotta-sfdc** [comment]
@jefersonchaves this is a priority for us, but I don't have a scheduled date. I will let you know as soon as it's done. 

If this is causing issues for you in a CI/CD pipeline you can execute the following command to avoid the prompt. 

`echo y | sfdx plugins:install @salesforce/sfdx-scanner`

**Comment by jbartolotta-sfdc** [comment]
@jefersonchaves @msrivastav13 this is implemented in version 2.4.0. These are the [2.4.0 release notes](https://forcedotcom.github.io/sfdx-scanner/en/release-information/)

**Comment by jefersonchaves** [comment]
That is great, thanks a million for the update!
