### ISSUE TITLE
Let standard PMD rules be disabled by config file/args

### ISSUE THREAD

**Issue by jamessimone** [forcedotcom/sfdx-scanner#246]
Since we can only filter by category when running `sfdx scanner:run`, there are standard PMD rules within the categories that should ideally be disable-able by means of including a config file or by passing in args on the command line. 

For example, let's say I want to run all of the `Best Practices` category with the _exception_ of the [`ApexAssertionsShouldIncludeMessage` rule](https://pmd.github.io/pmd-6.28.0/pmd_rules_apex_bestpractices.html#apexassertionsshouldincludemessage). 

At the moment, I don't have the way to interact meaningfully with the default PMD rules; this adds to my CI burden because if I or my team feel this rule need not apply, I now have to validate the output file to say that, actually, this CI step has passed because only this rule was triggered on scan.

It would be a big quality of life improvement to be able to add rules to ignore to a config file that could then be committed, specific to the repository I'm looking to scan.

Thank you!

**Comment by jbartolotta-sfdc** [comment]
@jamessimone thanks for the feedback, we will consider adding this. You can currently control which rules are run by creating your own custom category.

Here are some instructions to get you started, the example creates a new category `My Best Practices` which is the `Best Practices` standard category minus the `ApexAssertionsShouldIncludeMessage` rule.

**Download the existing bestpractices.xml category file**
```bash
$ mkdir -p ~/tmp/my-pmd/category
$ cd ~/tmp/my-pmd/category
$ curl -O https://raw.githubusercontent.com/pmd/pmd/master/pmd-apex/src/main/resources/category/apex/bestpractices.xml
```

**Edit bestpractices.xml**
1. Change `<ruleset name="Best Practices"` to `<ruleset name="My Best Practices"`. 
2. Remove XML node that corresponds to the `ApexAssertionsShouldIncludeMessage` rule

**Add the bestpractices.xml file to the set of supported rules in the scanner**
``` bash
$ sfdx scanner:rule:add  --language apex --path ~/tmp/my-pmd/category/bestpractices.xml
Successfully added rules for apex.
1 Path(s) added: ~/tmp/my-pmd/category/bestpractices.xml
```

**Check that the rules have been added, ApexAssertionsShouldIncludeMessage should be missing from the output**
```bash
$ sfdx scanner:rule:list  --language apex --category 'My Best Practices'
NAME                                          LANGUAGES  CATEGORIES         RULESETS [DEP]  ENGINE
────────────────────────────────────────────  ─────────  ─────────────────  ──────────────  ──────
ApexUnitTestClassShouldHaveAsserts            apex       My Best Practices                  pmd
ApexUnitTestMethodShouldHaveIsTestAnnotation  apex       My Best Practices                  pmd
ApexUnitTestShouldNotUseSeeAllDataTrue        apex       My Best Practices                  pmd
AvoidGlobalModifier                           apex       My Best Practices                  pmd
AvoidLogicInTrigger                           apex       My Best Practices                  pmd
DebugsShouldUseLoggingLevel                   apex       My Best Practices                  pmd
UnusedLocalVariable                           apex       My Best Practices                  pmd
```

**Scan your code with the new category. You should no longer see any violations for ApexAssertionsShouldIncludeMessage**
```bash
$ sfdx scanner:run --target 'force-app/test/default/classes' --category 'My Best Practices'
```
**A few things to note**
1. The XML file needs to be contained within a directory named `category`
2. The name of the XML file is not important
3. Rules from different standard categories can be combined into a single custom category

Please let me know if you run into any issues.

**Comment by msrivastav13** [comment]
@jbartolotta-sfdc Does this mean if I have to add the rule category, I have to run the command for scanner rule add in my CI systems as well?  Thanks for the instructions!

**Comment by jbartolotta-sfdc** [comment]
> @jbartolotta-sfdc Does this mean if I have to add the rule category, I have to run the command for scanner rule add in my CI systems as well? Thanks for the instructions!

@msrivastav13 you would need to run that command on your CI/CD system, or recreate its effect. That command changes the `.sfdx-scanner/CustomPaths.json` file. You could copy your xml file and the CustomPaths.json to your CI/CD system if that is more convenient than running the command.

**Comment by jamessimone** [comment]
@jbartolotta-sfdc thanks for your insight on this. While your workaround (and responses to @msrivastav13) will work, I'll keep this issue open if that's ok in the hopes that one day this will be possible without having to manually re-create the existing categories. Thank you!

**Comment by jbartolotta-sfdc** [comment]
That makes sense @jamessimone. We will keep this open.

**Comment by harsheshshah** [comment]
@jbartolotta-sfdc  - Is this only applicable for PMD? What if we want to disable some rules for Lightning i.e. JS ones from ECMAScript etc.
Can you kindly share steps for that?

**Comment by harsheshshah** [comment]
> > @jbartolotta-sfdc Does this mean if I have to add the rule category, I have to run the command for scanner rule add in my CI systems as well? Thanks for the instructions!
> 
> @msrivastav13 you would need to run that command on your CI/CD system, or recreate its effect. That command changes the `.sfdx-scanner/CustomPaths.json` file. You could copy your xml file and the CustomPaths.json to your CI/CD system if that is more convenient than running the command.

@jbartolotta-sfdc or @msrivastav13 Where can we find CustomPaths.json? What is the path or steps.

**Comment by jbartolotta-sfdc** [comment]
> @jbartolotta-sfdc - Is this only applicable for PMD? What if we want to disable some rules for Lightning i.e. JS ones from ECMAScript etc.
> Can you kindly share steps for that?

@harsheshshah - the current release(2.4) doesn't support a way to disable individual eslint rules. The next release(2.5) will support this by accepting a path to an eslint configuration file.

The configurations for the scanner are located in the .sfdx-scanner directory which is in your home directory. Any changes to Catalog.json or PmdCatalog.json will be overwritten, you should not edit these.

**Comment by ranekere-sfdc** [comment]
This issue is resolved as part of the Scanner 2.5 release.

**Comment by jamessimone** [comment]
@jbartolotta-sfdc @ranekere-sfdc I would be hesistant to call this issue "resolved" with the way things stand, at present. While editing the home directory's config file will provide some level of customization that was previously not present, you are still forced as a user to run the same ruleset on _every_ project you have. If you want to run the Security PMD rules on one repo but not on another ... you can't really do that without editing the config file in your home directory prior to each run.

**Comment by jbartolotta-sfdc** [comment]
@jamessimone sorry for any confusion. We will be more explicit when closing issues going forward. 

I believe the use case is met with version `2.5.1` which was released today, you can update by running `sfdx plugins:update`. 

The `scanner:run` command accepts a new flag `--pmdconfig`.

Creating a file with the following content and passing its path to the command will run all `Best Practices` rules except for the `ApexUnitTestClassShouldHaveAsserts` rule. You can add multiple rule nodes if you want to scan multiple categories. 

```xml
<?xml version="1.0"?>
<ruleset name="MyRules"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

        <rule ref="category/apex/bestpractices.xml">
            <exclude name="ApexUnitTestClassShouldHaveAsserts"/>
        </rule>
</ruleset>
```

More information about constructing these files can be found at https://pmd.github.io/pmd-6.30.0/pmd_userdocs_making_rulesets.html

Let me know if you think this meets your use case or if you would like us to reopen the issue.

Thanks.

**Comment by jamessimone** [comment]
@jbartolotta-sfdc no worries at all - this is exactly what I’m looking for. I appreciate you taking the time to clarify!
