### ISSUE TITLE
The Scanner should (only) use each engine default configs/rulesets

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-scanner#248]
I know there is a bit of redundancy to other already submitted issues but I think I don't get the point. I also want to emphasize the importance of this as multiple well-recognized Salesforce experts (after looking into the CLI) publically raised this issue.

The standard way to configure which rules are used per engine should be the engines default config file. Not an internal proprietary format. If I use PMD I have a ruleset.xml in my repos root. I exclude rules, configure parameter to adjust Naming schemes for example and I add my own XPath rules. I expect the scanner to respect that and use that file as my VS code or my Intelij is doing. 

The same applies to ESLint (or future supported engines). My local tools pick up the eslint.conf in my repos root (Infrastructure as code). One rulesset for all developer and all tools.

The barrier of usage for the scanner is high when people have to learn and translate to a proprietary config schema.

**Comment by rsoesemann** [comment]
@jbartolotta-sfdc @rmohan20 this was voices by @nawforce, @Szandor72 and @msrivastav13 on this Twitter thread https://twitter.com/ch_sz_knapp/status/1315207418444427264?s=20

**Comment by msrivastav13** [comment]
+ 1 on this! This [one](https://github.com/forcedotcom/sfdx-scanner/issues/246) is a good workaround but still its lot of steps.

What would be good is just provide devs ability to add a ruleset XML or .eslintrc.json files for Eslint being obeyed.

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann thanks for filing. We will address this.

**Comment by jbartolotta-sfdc** [comment]
@msrivastav13 @rsoesemann version `2.5.1` was released to day. The `scanner:run` command accepts two new flags.

```
--eslintconfig=eslintconfig    location of eslintrc config to customize eslint engine
--pmdconfig=pmdconfig          location of PMD rule reference XML file to customize rule selection
```

For now the file must be explicitly referenced instead of auto-detecting. We may add auto-detection in the future.

Let us know your thoughts.

Thanks.

**Comment by rsoesemann** [comment]
Tested it and it worked greatly. It ignore custom XPath rule. Can I sfdx scanner add them or should I open a new feature request for that? @jbartolotta-sfdc @rmohan20

**Comment by jbartolotta-sfdc** [comment]
> Tested it and it worked greatly. It ignore custom XPath rule. Can I sfdx scanner add them or should I open a new feature request for that? @jbartolotta-sfdc @rmohan20

Thanks for trying it out @rsoesemann 

Are you running into an issue with the interaction of `scanner:rule:add` and this new flag? Could you let me know how to reproduce?

**Comment by jbartolotta-sfdc** [comment]
> @jbartolotta-sfdc I used the Scanner with the ruleset at https://github.com/CopadoSolutions/lma-app-cockpit/blob/master/ruleset.xml. It contains 2 XPath rules. They are not detected. How would I add them using the add cli command. There is only instructions about Custom Java rules.

@rsoesemann we will have a look. We can continue to use this issue to track it. Thanks.

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann You do not need to use `scanner:rule:add` since it is using the built in `ApexXPathRule` rule.

I am not able to recreate the issue. I saved that Ruleset to my local system and invoked it against the class below. The Scanner found three violations.  Two violations are from the custom XPath rules, and one is the builtin `DebugsShouldUseLoggingLevel`. 

Does your output show any warnings or errors? 
Does it detect the violation from the built in `DebugsShouldUseLoggingLevel` rule? 

```bash
> sfdx scanner:run --pmdconfig ruleset.xml --target MyClass.cls
About to run PMD with custom config in ruleset.xml. Please make sure that any custom rule references have already been added to the plugin through scanner:rule:add command.
LOCATION       DESCRIPTION                                           CATEGORY                                                                U R L
─────────────  ────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────
MyClass.cls:3    Avoid leaving System.debug() statments in code as   Default ruleset used by the CodeClimate Engine for Salesforce.com Apex
                 they negativly influence performance.
MyClass.cls:3    Calls to System.debug should specify a logging      Best Practices                                                          https://pmd.github.io/pmd-6.30.0/pmd_rules_apex_bestpractices.html#debugsshoulduselogginglevel
                 level.
MyClass.cls:8    Dont hardcode Callout endpoint URLs in Apex code.   Default ruleset used by the CodeClimate Engine for Salesforce.com Apex
                 Leverage Named Credential metadata instead.
Executed pmd-custom, found 3 violation(s) across 1 file(s).
Rule violations logged to console above.
```


```java
public class MyClass {
   public void badDebug() {
      System.debug('This is not ok');
   }

   public void badCredentials() {
      HttpRequest req = new HttpRequest();
      req.setEndpoint('https://facebook.com/login');
   }
}
```

**Comment by rsoesemann** [comment]
My bad your right.
