### ISSUE TITLE
[Feature Request] Provide first class native support in VSCode for Salesforce CLI Scanner

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/sfdx-scanner#252]
**Is your feature request related to a problem? Please describe.**

[Salesforce CLI scanner](https://forcedotcom.github.io/sfdx-scanner/) uses PMD, ESlint, and has the flexibility to add my own rules. Great!!!!!! 

Love a couple of aspects of it

1. Smooth installs
2. Neat command in SFDX format. Makes it consistent with CLI experience.

What needs to improve

First-class support in the VSCode Salesforce extension pack.

**Describe the solution you'd like**

1. The results returned from the Scan command should show up in the file. Provide vsCode commands so I can run the command from vscode and squiggly line as per results returned.
2. Provide a feature that runs a scan on file save

**Describe alternatives you've considered**
For now, I build my own tasks.json, however, results do not squiggly line the file

<img width="1687" alt="Screen Shot 2020-10-09 at 5 04 31 PM" src="https://user-images.githubusercontent.com/2276156/95631399-a2822900-0a51-11eb-9af6-5beb9df57aec.png">

**Additional context**
Note we can use Apex PMD extension from the community and ESlint extensions but they are not in parity with how we set  CLI Scanner categories. Apex PMD maintains a ruleset XML while CLI has categories and rule add commands to build own categories. So a developer has to maintain two different configs.

 Loved this new CLI plugin because I don't have to install and set APEX PMD paths etc and everything is aggregated just needs to be commands for it in the Extension Pack.

**Comment by jonathanwiesel** [comment]
With the continued effort being put into the (now named) Code Analyzer, and the introduction of very promising functionality with DFA, is the VSCode extension approach still a thing?

**Comment by DougMidgley** [comment]
Strong support for this since APEX PMD is often throwing different errors than scanner which leads to frustration in developersr :(

**Comment by jefersonchaves** [comment]
Is there anything we can help to make it happen?

**Comment by jefersonchaves** [comment]
Hey @jfeingold35 - That is already a great sign; I loved it. Thanks for the transparency; I deal with software and know what you mean. I'm eager to see this becoming real and get my hands on it!

**Comment by johnbelosf** [comment]
@jefersonchaves @msrivastav13 @jonathanwiesel our VSCode Extension (beta) is now [available in the VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=salesforce.sfdx-code-analyzer-vscode).

I am closing this issue. Stay tuned for further updates on the extension as we move towards GA.

**Comment by jefersonchaves** [comment]
It looks very promising @johnbelosf. It is a great addition to improve code reliability.
