### ISSUE TITLE
Internal error running scanner commands from VS Code terminal with custom rules

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/sfdx-scanner#261]
Bit of a convoluted title I know, but it does seem very specific.

I've created my own version of the best practices and security rulesets to remove a couple of things that I'm not interested in, and added a custom rule of my own. All via XML so I'm not installing any custom Java classes.

Once these rules are installed, running any scanner command from the VS Code terminal throws an internal error:

```
$ sfdx scanner:rule:list
ERROR: An internal error occurred. [TODO: Information on how to contact us and what details to provide]
ERROR running scanner:rule:list:  Please see error details displayed above.
```

I can run the same command from the same directory using iTerm or the standard MacOS terminal without issue.  All other CLI and plug-ins functionality work okay.

I've run with -`-verbose` and `--loglevel` trace, but I don't get any more information about the error.

**Operating system**: MacOS 10.15.7
**CLI version** : sfdx-cli/7.76.1-f301d5641f darwin-x64 node-v12.18.3
**Plug-ins**:
@oclif/plugin-autocomplete 0.2.0
@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-update 1.3.9
└─ @oclif/plugin-help 2.2.1
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-scanner 2.3.0

**Comment by keirbowden** [comment]
The problem was MacOS blocking VS Code access to the folder where I had the XML ruleset files. It would be nice to get a better message than an internal error and TODO.

**Comment by rmohan20** [comment]
@keirbowden Thanks for notifying us about this issue. We'll fix the error message.
You probably found this already, but when we run a command with `--loglevel trace`, the trace log lines go to `~/.sfdx/sfdx.log`.

**Comment by jbartolotta-sfdc** [comment]
The error message has been improved in [2.4.0](https://forcedotcom.github.io/sfdx-scanner/en/release-information/#v240-11-04-2020).
