### ISSUE TITLE
[Feature Request] enable remove eslint rules from rule list

### ISSUE THREAD

**Issue by Tzeimi** [forcedotcom/sfdx-scanner#264]
It would be nice to be able to remove some rules from the eslint rule set.

currently I tried the following, create a custom eslintrc.json, but it's ignored by the scanner, also using the command `sfdx scanner:rule:remove -p path/with/js/rules`  or `eslintrc.json` it doesn't works.

Thank you.

**Comment by johnbelosf** [comment]
This can be achieved with custom ESlint configs: https://forcedotcom.github.io/sfdx-scanner/en/v3.x/custom-config/eslint/
