### ISSUE TITLE
[Feature Request] Improve the Install time of the Salesforce CLI Scanner

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/sfdx-scanner#265]
First off thanks for this great open source project. We are adopting this for our [sample-gallery](https://github.com/trailheadapps) apps projects maintained by the developer evangelism team.

Currently, it takes `23` seconds to install this plugin. You can check [here](https://github.com/trailheadapps/lwc-recipes/pull/405/checks?check_run_id=1309013424)

I do not know what it takes to reduce this time. Anything (even 5 seconds) that reduces this time will be helpful!

**Comment by ranekere-sfdc** [comment]
@msrivastav13 - Over the past releases, we have reduced the size of the plugin and the install time has reduced. Just checking one of the runs [here](https://github.com/trailheadapps/lwc-recipes/runs/5229141391?check_suite_focus=true) took 8s. Hope this helps. 

Pls note,  in the future, if we add new engines, this size of the plugin could increase and hence the time to download. It will the cost of adding new functionality. 

I'll be closing this issue now, pls feel free to reopen if needed.

**Comment by johnbelosf** [comment]
It still takes around 23 seconds as of today. This is not a priority for us at the moment, but I'll add it to the backlog.

**Comment by johnbelosf** [comment]
Unfortunately we are not prioritizing this at this time
