### ISSUE TITLE
eslint-lwc engine not running by default on scanner:run

### ISSUE THREAD

**Issue by harsheshshah** [forcedotcom/sfdx-scanner#276]
When we run scanner:run using below command, it does not run eslint-lwc

example:
sfdx scanner:run -t "<Target path>"  -f csv -o "Output\result.csv"

It runs PMD and Eslint but not eslint-lwc.
We need to explicitly run that by giving engine command.
example:
sfdx scanner:run -t "<Target path>"  --engine "eslint-lwc" -f csv -o "Output\result.csv"

Moreover documentation at https://forcedotcom.github.io/sfdx-scanner/en/scanner-commands/run/ have no mention of engine.
Can we get the documentation updated so that it will be useful for others.

**Comment by ranekere-sfdc** [comment]
@harsheshshah We are making the documentation changes to mention the usage of --engine for eslint-lwc. It will be released soon.

**Comment by jfeingold35** [comment]
Documentation for the `--engine` flag was added in the 2.4.0, published in November.
