### ISSUE TITLE
Is there a way to scan only the files specified in the manifest/package.xml file instead?

### ISSUE THREAD

**Issue by aalazzani** [forcedotcom/sfdx-scanner#302]
I want to be able to use the same command in my CI pipeline to scan only the files listed in the manifest/package.xml instead of hard coding the files/folders in my command. Is there a way to do that?

**Comment by jbartolotta-sfdc** [comment]
@aalazzani Using the package.xml as an input is not currently supported. However, the `scanner:run` command support globs and exclusions. 

Does something like `sfdx scanner:run --target 'force-app,!./**/*Test.cls'` meet the requirements? This command will scan all supported files located below the `force-app` directory but exclude Apex files that end in `Test.cls`.

**Comment by aalazzani** [comment]
@jbartolotta-sfdc thanks for response. Just to explain the situation.

- I want to have a single Jenkinsfile that centrally managed and shared across all developers. I don't want developers to modify the Jenkinsfile (which is where the scanning command exists).
- To avoid scanning all files in the developer's feature branch, a developer would list the files they want to merge in the manifest file and the scanner would scan only these files.

Is there a way to achieve that?

**Comment by jbartolotta-sfdc** [comment]
@aalazzani It is possible that the Scanner will eventually support a text file as input for a list of targets, but I don't believe it's likely that the Scanner will support package.xml as the format. More and more projects are stored in the Salesforce DX format which doesn't rely on a package.xml file. 

You could keep your list of targets in a separate file and use `cat` and `tr` to provide the list of targets. As an example. I did the following

1. Created a file named  `files-to-scan.txt` with the following contents
```txt
./**/*.cls
!./**/*TestClass.cls
```

2. Use this file as as input to the `--target` flag.
```bash
# The output of "cat files-to-scan.txt | tr '\n' ','" is `./**/*.cls,!./**/*TestClass.cls,`. This string is passed as the --target flag.
$ sfdx scanner:run --target "$(cat files-to-scan.txt | tr '\n' ',')"
```

Alternatively you could write a script `package-xml-parser.sh` that parses the package.xml and returns a comma separated string.
```bash
$ sfdx scanner:run --target "$(package-xml-parser.sh)"
```

Let me know if this gets you closer to meeting your requirements.

**Comment by johnbelosf** [comment]
We've provided feedback - please reopen the issue if you still have questions
