### ISSUE TITLE
Salesforce CLI Scanner Integration

### ISSUE THREAD

**Issue by jonathanwiesel** [forcedotcom/sfdx-scanner#304]
**Is your feature request related to a problem? Please describe.**
It's common in a development workflow to use static analysis tools that search the code for problems before proceeding to make it available for usage, this way you can guarantee the code follows a certain degree of security measures and best practices by using standard rules in a project / company.

**Describe the solution you'd like**
With the recent introduction of the [Salesforce CLI Scanner Plugin](https://forcedotcom.github.io/sfdx-scanner/) seems like the only thing missing is filling the gap between the development environment (VS Code) and the plugin. 

It should have the ability to run the static analysis on demand directly from the VS Code palette, or automatically when a file is saved. Results should be shown as errors, warnings or hints in the Problems tab.

**Describe alternatives you've considered**
There's currently a [great extension (Apex PMD)](https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-pmd) developed by @ChuckJonas that fills the gap between PMD and Apex and shows the output appropriately, however seems like the logical way moving forward is to delegate all the communication with the static analysis tools to the CLI Scanner plugin and make the extension interact directly with the plugin instead making the implementation on the extension decoupled from the engine, rules and configuration.

**Comment by johnbelosf** [comment]
We are planning this work at some point in the future. Let's track this in #252 going forward.
