### ISSUE TITLE
Enable eslintrc rules to be used by default for JS files

### ISSUE THREAD

**Issue by DougMidgley** [forcedotcom/sfdx-scanner#330]
**Issue**
Currently it seems that you cannot use the default ESLINT config files (for example which comes in Aura and LWC folders) as the config. This means that either you need to rebuild all the rules OR have conflicting rules. For example "Parsing error: Unexpected character '@'" is coming up when though the default Aura ESLINT config shows no issues.

**Proposed Resolution**
 I see there is a tsconfig.json, this could potentially be added, but in an ideal world there should be some way to take the "standard" ESLINT rules, since this would provide the most consistent experience for developers.

**Comment by jfeingold35** [comment]
Hi Doug.
You could run the ESLint Aura/LWC rules against your files by using  `--engine eslint-lwc` in your command. Does that resolve your problem, or is there something I'm not understanding?

**Comment by DougMidgley** [comment]
Hi j! 
I tried doing this and outcome was
- EsLint in VScode -> no errors
- eslint-lwc engine -> various errors, especially stylistic. Often conflicting for example tabs vs spaces.
It definitely seems like it is not reading the .eslintrc.json files in the lwc and aura folders

**Comment by DougMidgley** [comment]
Also side note where is docs on using eslint-lwc engine? I couldn't see anything

**Comment by jfeingold35** [comment]
There's been a miscommunication. By default, we use our own soft-coded eslintrc.json file, skipping any that are actually in the folders being scanned. However, in the next release, due sometime next week, we'll be adding a `--eslintconfig` flag that you can point at an eslintrc.json file to make the scanner use that file instead. Documentation available here: https://github.com/forcedotcom/sfdx-scanner/blob/dev/docs/_articles/en/custom-config/eslint.md.
Also, we'll be adding more documentation about the `eslint-lwc` engine in general in that same release, but you can see it early here: https://github.com/forcedotcom/sfdx-scanner/blob/dev/docs/_articles/en/architecture/eslint-engine.md.

**Comment by DougMidgley** [comment]
Perfect, so sounds like next release will do exactly what we need! thanks :)
