### ISSUE TITLE
Salesforce Scanner CLI - GitHub Action

### ISSUE THREAD

**Issue by firatesmer** [forcedotcom/sfdx-scanner#345]
Hi,

Is there a way to use `Salesforce Scanner CLI` as `GitHub Action`? I checked [sfdx-actions](https://github.com/sfdx-actions) and there is an action allows us to use `Salesforce CLI` but not `Salesforce Scanner CLI`. Any thoughts about this?

Thanks.

**Comment by firatesmer** [comment]
Currently, I've found a way to handle this gap with those steps as mixed

1. Install Salesforce CLI
2. Install Salesforce Scanner CLI as plugin
3. Run Salesforce Scanner CLI commands

**Comment by jbartolotta-sfdc** [comment]
@firatesmer thanks for your question. Your solution is the currently supported way to use the Scanner in a Github Action. 

We will look into making this easier.

**Comment by firatesmer** [comment]
Thanks @jbartolotta-sfdc!

**Comment by nvuillam** [comment]
If you want to use sfdx-scanner in a GitHub action, you can use [Mega-Linter GitHub action](https://nvuillam.github.io/mega-linter/).

It [embeds sfdx-scanner](https://nvuillam.github.io/mega-linter/descriptors/salesforce_sfdx_scanner/
), and you can customize the number of allowed errors 

To install it in your repo, you can use:

`npx mega-linter-runner --install` , and select **Salesforce Flavor**

**Comment by mitchspano** [comment]
I just published a Github action which will execute sfdx-scanner on the contents of a pull request and generate the findings as in-line comments:

https://github.com/marketplace/actions/sfdx-scan-pull-request

**Comment by johnbelosf** [comment]
Many thanks for this @mitchspano! Are you OK if we point to your GitHub action from our documentation, as we want to provide instructions on CI/CD integration?

Additionally, one suggestion to evolve your GitHub action would be to support our latest code branch for Code Analyzer (3.x) and Graph Engine, which has a dedicated scanner:run:dfa command. We are going to keep investing significantly in Code Analyzer, so it would be of great value if the GitHub action supported it.

**Comment by mitchspano** [comment]
@johnbelosf  - that sounds fine by me! I will take a look into the `scanner:run:dfa` command and see if I can incorporate it into the github action.

**Comment by johnbelosf** [comment]
Many thanks @mitchspano and let me know how you get on!

**Comment by johnbelosf** [comment]
The community has delivered on this issue - we're closing it for now
