### ISSUE TITLE
eslint: Parsing error: Unexpected character '@'

### ISSUE THREAD

**Issue by vbhasker** [forcedotcom/sfdx-scanner#360]
eslint continues to fail on LWC decorators and exists scanning. Is there something that I'm missing?

**Comment by jbartolotta-sfdc** [comment]
@vbhasker Can you try invoking the `eslint-lwc` engine? It is configured with the `eslint-lwc` rules.

```bash
# Example
sfdx scanner:run --engine eslint-lwc --target test/code-fixtures/projects/lwc/chartBar
```

**Comment by vbhasker** [comment]
Thank you @jbartolotta-sfdc, that worked! 👍
