### ISSUE TITLE
[Feature Request] CHANGELOG

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/sfdx-scanner#371]
Is there a way to see differences between versions ?

Maybe it could be wise to add a CHANGELOG.md in the repository ? :)

**Comment by jbartolotta-sfdc** [comment]
@nvuillam this information is contained on the github.io site here https://forcedotcom.github.io/sfdx-scanner/en/release-information/

The raw markdown is found here https://github.com/forcedotcom/sfdx-scanner/blob/dev/docs/_articles/en/release-information.md

**Comment by nvuillam** [comment]
Thanks :)
