### ISSUE TITLE
[BUG] Accept ES6 in LWC lint

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/sfdx-scanner#372]
Is there an argument to send to sfdx-scanner so ES6 can be accepted ?
Because now I see compilation errors about class fields with initialization value :/

```shell
"Problem","File","Severity","Line","Column","Rule","Description","URL","Category","Engine"
"1","/builds/busalesforce/cermix-client/cermix/force-app/main/default/lwc/stock/stock.js","2","8","22","files-must-compile","Parsing error: Unexpected token =",,"Scanner Internal","eslint"
"2","/builds/busalesforce/cermix-client/cermix/force-app/main/default/lwc/stockPaginator/stockPaginator.js","2","8","5","files-must-compile","Parsing error: Unexpected character '@'",,"Scanner Internal","eslint"
"3","/builds/busalesforce/cermix-client/cermix/force-app/main/default/lwc/stockTable/stockTable.js","2","16","5","files-must-compile","Parsing error: Unexpected character '@'",,"Scanner Internal","eslint" ```

**Comment by jbartolotta-sfdc** [comment]
@nvuillam Sorry for the inconvenience, we are working on making this more user friendly. 

Can you try invoking the `eslint-lwc` engine? It is configured with the `eslint-lwc` rules. 

```bash
# Example
sfdx scanner:run --engine eslint-lwc --target /builds/busalesforce/cermix-client/cermix/force-app/main/default/lwc
```

**Comment by nvuillam** [comment]
The problem is that I use sfdx-scanner within [Mega-Linter](https://nvuillam.github.io/mega-linter/descriptors/salesforce_sfdx_scanner/), and for architecture reasons I need to call all engines (including pmd) in a single call... do you have a solution for such case ?

**Comment by nvuillam** [comment]
@jbartolotta-sfdc Any chance to have a fix in a near future ?
Just to know if I have to tweak Mega-Linter and separate apex and lwc lints :/

**Comment by nvuillam** [comment]
I am currently declaring sfdx-scanner as 3 different linters, as engines are unable to run in a single sfdx-scanner call :/
- apex
- aura
- lwc

**Comment by jbartolotta-sfdc** [comment]
@nvuillam Thanks for the info. We considered auto detecting the type of JavaScript which the user is scanning but there are a lot of edge cases where the scanner could make the wrong decision, also introspecting the files would lengthen the time of a scan. We ultimately decided on letting the user explicitly declare their intention.
 
I will add a new `auto-detect` mode to our list of future ideas.

**Comment by johnbelosf** [comment]
This is a feature request, not a bug. Please follow #383 for future updates
