### ISSUE TITLE
[Feature Request] Add rule for deprecated SLDS classes 

### ISSUE THREAD

**Issue by JeroenSfdc** [forcedotcom/sfdx-scanner#373]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a rules which scans for deprecated SLDS classes (e.g. using the old -- BEM notation). Similar to how Illuminated Cloud reports these. 

![image](https://user-images.githubusercontent.com/27854769/112328957-0f634580-8cb7-11eb-9f07-5b15fa97fc97.png)

**Describe the solution you'd like**
Probable a PMD Rule scanning for a pattern within SLDS classes using `--` 
But rules could even be more complete, e.g. if SLDS decide to deprecate other (current) classes by name. 

**Describe alternatives you've considered**
n/a

**Additional context**
Deprecated SLDS classes (specifically those with a changed BEM notation) will be a big issue if not resolved by customers before Summer '22 as they will be removed. 

"Workaround": Can you do something similar with existing capabilities?

"Urgency": How badly do you need this feature? "Nice to have" vs "Highly beneficial" vs "Can't live without it".

**Comment by jfeingold35** [comment]
The time when this was worth doing has passed.
