### ISSUE TITLE
[Feature] Allow scanner:run to fail automated builds #171

### ISSUE THREAD

**Issue by Rightback** [forcedotcom/sfdx-scanner#374]
salesforce/sfdx-scanner 2.7.0
This is a followup of "Allow scanner:run to fail automated builds #171 bug"  that is closed currently. Can we define the severity to which the pipeline should fail. for example if we set the severity to 2 it means any violation greater than 2 once detected should fail the pipeline but if its less than 2 it should pass. How can we achieve that. What you have now is anything other than 0 should fail

Thanks
Mike

**Comment by ranekere-sfdc** [comment]
@Rightback We have another issue/work item related to severity. Currently, PMD and ESLint have different scales, and also the order of importance is also opposite. So, we are looking into the design to consolidate them. As part of that work, we'll address this tool.

**Comment by Rightback** [comment]
Thanks..looking forward to the update

**Comment by rmohan20** [comment]
Hi @Rightback - as a part of 2.10.0 release, we've added a new flag `--severity-threshold` to `scanner:run` command. This can take a value between 1 and 3 as a parameter. This flag would return with a non-zero exit code when at least one detected rule violation has a severity value equal to or more severe than the given parameter value. A CI/CD system would recognize this non-zero exit code as an error.

You can find more information [here](https://forcedotcom.github.io/sfdx-scanner/en/faq/#questions-about-severity-threshold-and-normalization).

I'm closing this issue for now. Please reopen or create a new issue for us if this doesn't address your requirements. Thanks!
