### ISSUE TITLE
CPD Scan

### ISSUE THREAD

**Issue by StevenWCox** [forcedotcom/sfdx-scanner#378]
First - I'm SOOO glad I found this plugin. Thanks for providing it! I'm not going to get rid of all my static analysis tools and configurations and use your simple solution.

Feature request: I would like to see you support CPD (Copy / Paste Detector) or some similar tool. In my experience, one of the primary sources of defects in software is copy/pasted code that is not understood or maintained. CPD is a tool in the PMD package and is very easy to use. It works on Apex or Visualforce.

Thanks again for the great tool!

**Comment by ranekere-sfdc** [comment]
@StevenWCox  Thanks for using our tool and logging a feature request. We'll add this to our backlog and get back to you soon when we have a solution.

**Comment by nvuillam** [comment]
IF you are in a hurry, you can use [Mega-Linter](https://nvuillam.github.io/mega-linter/), it embeds:
- sfdx-scanner (i'm currently making an update so it can lint LWC correctly)
- [jscpd](https://github.com/kucherenko/jscpd)

**Comment by rmohan20** [comment]
@StevenWCox Thanks for your suggestion. We will be supporting CPD as another engine in our upcoming release. You should be able to invoke it through:
```
sfdx scanner:run --engine cpd --target /your/target/pattern
```
