### ISSUE TITLE
Running scanner throws JAVA error[BUG]

### ISSUE THREAD

**Issue by bvsh030** [forcedotcom/sfdx-scanner#381]
After running a command, this error is triggerred: **_"ERROR running scanner:run:  Could not fetch Java version from path C:\Program Files\Java\jdk1.8.0_111. Reason: spawn C:\Program Files\Java\jdk1.8.0_111\bin\java ENOENT_**

I am using SFDX since long, so naturally java is installed on my machine, eventually i made a check with the command **java -version** with a positive result.
I have checked the folder that the above error message is referencing to, i found that it is an empty folder. I thought that i need to change the folder to another where the correct JAVA version is installed but i can't seem to find a proper way of doing this.
Or if there is any other solution, i would really appreciate.
Thanks

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/82386897/114399350-e34e2c80-9bb1-11eb-80d1-89fb4a48e970.png)

**Desktop:**
 - OS: Windows 10
 - Scanner Version: sfdx-scanner 2.7.0

Urgency:  Not business-stopping.

**Comment by rmohan20** [comment]
Hi @bvsh030 - you are right - the error seems to be about the empty directory too.

To fix it:
Under your home directory (`C:\Users\<your_username>`), there should be a `.sfdx-scanner\Config.json` file. Towards the end of the file, there should be a `"javaHome"` property and value. 
Delete the property and value. Save and exit. Rerun your `scanner:run` command - this should hopefully identify the correct path and update the `Config.json` file.
If this still identified the same empty path and threw the same error, you can [find the correct java path](https://stackoverflow.com/questions/4681090/how-do-i-find-where-jdk-is-installed-on-my-windows-machine/19576957) in your machine and manually update the `"javaHome"` value yourself.

Please let us know if this works for you. Thanks!

**Comment by bvsh030** [comment]
> Hi @bvsh030 - you are right - the error seems to be about the empty directory too.
> 
> To fix it:
> Under your home directory (`C:\Users\<your_username>`), there should be a `.sfdx-scanner\Config.json` file. Towards the end of the file, there should be a `"javaHome"` property and value.
> Delete the property and value. Save and exit. Rerun your `scanner:run` command - this should hopefully identify the correct path and update the `Config.json` file.
> If this still identified the same empty path and threw the same error, you can [find the correct java path](https://stackoverflow.com/questions/4681090/how-do-i-find-where-jdk-is-installed-on-my-windows-machine/19576957) in your machine and manually update the `"javaHome"` value yourself.
> 
> Please let us know if this works for you. Thanks!

Hello @rmohan20 
Brillant, i was searching for the config file on my vscode project like an idiot. 

Actually the whole **_javaHome_** line was missing, so i added it with the correct path to java and it worked like a charm.
Thanks a lot.
