### ISSUE TITLE
[Feature Request] - Suppress Violation

### ISSUE THREAD

**Issue by firatesmer** [forcedotcom/sfdx-scanner#386]
Hi,

First of all, thanks for the plugin. I use it with GitHub Actions to maintain and improve the code quality of the repository but sometimes violations are inevitable. In that case, we want to suppress the violations.

I've searched but couldn't find. Is it possible to achieve this goal?

Thank you.

**Comment by jbartolotta-sfdc** [comment]
@firatesmer you can disable PMD violations by following [these instructions](https://pmd.github.io/latest/pmd_userdocs_suppressing_warnings.html) You can disabl

**Comment by firatesmer** [comment]
Hey @jbartolotta-sfdc,

I have a PMD extension on my Visual Studio Code and `@SuppressWarnings` annotation works fine. However, when I use Salesforce Scanner plugin (on GitHub actions), it doesn't suppress warnings and I just see the violations in the result.

**Comment by jbartolotta-sfdc** [comment]
@firatesmer I ran the command `sfdx scanner:run --target test/code-fixtures/apex/SoqlInLoop.cls` against the following file. https://github.com/forcedotcom/sfdx-scanner/blob/dev/test/code-fixtures/apex/SoqlInLoop.cls

The file has 7 violations when no annotations are present.
```java
public class SoqlInLoop {
    public static void main() {
        for (Integer i = 0; i < 10; i++) {
            List<Account> accounts = [SELECT Id FROM Account];
        }
    }
}
```

This file has 0 violations when the following annotation is added
```java
@SuppressWarnings('PMD')
public class SoqlInLoop {
    public static void main() {
        for (Integer i = 0; i < 10; i++) {
            List<Account> accounts = [SELECT Id FROM Account];
        }
    }
}
```

The file has 3 violations when the following comment is added
```java
public class SoqlInLoop {
    public static void main() {
        for (Integer i = 0; i < 10; i++) {
            List<Account> accounts = [SELECT Id FROM Account]; //NOPMD
        }
    }
}
```

I did not try this in a GitHub action, but I expect it should behave the same. 

* Can you run the scanner on your local machine outside of the GitHub action and let me know if the violations are suppressed as expected?
* If the scanner is not suppressing the violations, can you provide a test case that demonstrates the issue? The issue might be content dependent and my test above case is not exposing the issue.
* Can you double check that the annotation contains `'PMD'` it needs to be `@SuppressWarnings('PMD')` not `@SuppressWarnings`

Thanks.

**Comment by firatesmer** [comment]
Hi jbartolotta-sfdc,

Sorry for taking your time but I just tried with fresh repository and it worked so I believe I made a mistake in configuration. Thanks.

**Comment by jbartolotta-sfdc** [comment]
@firatesmer Thanks for the update, I'm glad it's working. Let us know if you have any other issues.
