### ISSUE TITLE
Engine for scanner is not working if I specify pmd for Apex classes

### ISSUE THREAD

**Issue by Gaurav-Rally** [forcedotcom/sfdx-scanner#442]
**Describe the bug**
When I use the scanner with the engine as pmd it is not returning any result. I am trying to use multiple engines (pmd and eslint-lwc) I am getting results only for lwc files but not for apex classes.

**To Reproduce**
Scenario one:
- command to use `sfdx scanner:run -e "pmd,eslint-lwc" -t force-app/main/default/classes/XYZ.cls,force-app/main/default/lwc/newLwcComp -f html`
- It return result only for LWC component

Scenario two:

- tried to use `sfdx scanner:run -e "pmd" -t force-app/main/default/classes/XYZ.cls -f html`
- did not give me any result with message `Executed engines: . No rule violations found.`
- But if I use without engine as pmd `sfdx scanner:run -t force-app/main/default/classes/XYZ.cls -f html` I am getting the scan result.

**Desktop (please complete the following information):**
 - OS: IOS
 - sfdx-cli/7.109.0 darwin-x64 node-v14.16.0
 - Scanner Version @salesforce/sfdx-scanner 2.9.2

"Workaround": I don't have any workaround for this

"Urgency": How severe is this problem? As we are using this in our CICD process all the deployments are passing without the actual code scan.

**Comment by ranekere-sfdc** [comment]
@Gaurav-Rally Thanks for reporting this issue. Looks like this is very similar to https://github.com/forcedotcom/sfdx-scanner/issues/260 

We are shipping a fix for this in the upcoming release (Fix PR is attached to this issue)

**Comment by Gaurav-Rally** [comment]
@ranekere-sfdc, thanks for your update. I will subscribe to that issue for resolution.

**Comment by jfeingold35** [comment]
The upcoming 2.10.0 release contains a fix for this bug. Please update to that version when available, and then reopen this record if the issue persists.
