### ISSUE TITLE
[BUG] Unable to install sfdx-scanner: FailedDigitalSignatureVerification

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/sfdx-scanner#453]
**Describe the bug**
Unable to install sfdx-scanner become of digital signature error

**To Reproduce**

```shell
$ sfdx plugins:install @salesforce/sfdx-scanner
    FailedDigitalSignatureVerification: A digital signature is specified for this plugin but it didn't verify against the certificate.
```

**Expected behavior**
sfdx-scanner to be installed :)

**Desktop**

- Latest sfdx-cli
- latest sfdx-scanner

Same behaviour on Windows or on CI (Github actions - alpine linux)

"Business stopping" -> Can not release a new version of [MegaLinter](https://nvuillam.github.io/mega-linter/), which is widely used

No workaround ( i tried `npm set strict-ssl false` , but same result )

**Comment by jbartolotta-sfdc** [comment]
@nvuillam - We are looking into this. I will report back within 1 hour.

**Comment by jbartolotta-sfdc** [comment]
@nvuillam We have verified that this is not a security issue, it is a configuration issue that we will need time to address.

We have changed the default installation version to the previous version(2.9.1). `sfdx plugins:install @salesforce/sfdx-scanner` should now succeed for you. 

Thanks for reporting this. Sorry for the inconvenience.

**Comment by nvuillam** [comment]
Thanks for your quick feedback :)

**Comment by vishu-shedbal-marlabs** [comment]
> Thanks for your quick feedback :)

Did it get installed ? in vscode ? after using that command ?

**Comment by nvuillam** [comment]
@vishu-shedbal-marlabs latest version works fine for me now
Not on your side ?

**Comment by ranekere-sfdc** [comment]
The issue has been fixed and please upgrade to the latest version. Closing this issue. Feel free to open a new issue if needed.
