### ISSUE TITLE
[Business Stopping or Security Bug] Test issue - please ignore

### ISSUE THREAD

**Issue by rmohan20** [forcedotcom/sfdx-scanner#477]
Describe the bug

"Urgency":  How is this Business stopping?

To Reproduce

Expected behavior

Screenshots

Desktop (please complete the following information):

Scanner Version [e.g. 22]
Additional context

"Workaround": Have you found any ways to sidestep the problem?

**Comment by jbartolotta-sfdc** [comment]
Test is over.
