### ISSUE TITLE
[FEATURE REQUEST]Support Scan Flows 

### ISSUE THREAD

**Issue by RubenHalman** [forcedotcom/sfdx-scanner#558]
**Is your feature request related to a problem? Please describe.**
The need for scanning flows on quality in the sfdx-scanner.

**Describe the solution you'd like**
The ability to scan flows for potential issues and improvements, adding flow-scanner to the supported rule engines.

[ vscode extension using the rule engine](https://github.com/Force-Config-Control/lightning-flow-scanner-vsce)
[core module which could be integrated](https://github.com/Force-Config-Control/lightning-flow-scanner-core)

Disclaimer: I am the author but its free and open source and I can adapt it however necessary

**Comment by ranekere-sfdc** [comment]
Thanks @RubenHalman for creating this feature request. I have created a work item to track this in our internal systems. We will update this thread if/when we pick it up.
