### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kamilsz** [forcedotcom/sfdx-scanner#569]
Severity threshold flag does not throw an error even in the lowes severity, -v parameter is still required.

**To Reproduce**
Steps to reproduce the behaviour:
run following against a test class that has System.assert() method without message or System.debug() without logging level
'sfdx scanner:run -c 'Best Practices, Error Prone, Code Design' -t 'force-app/main/default/classes' --severity-treshold=3'

**Expected behaviour**
throw an error

**Screenshots**
code with severity threshold set to 3 and not -v flag
![image](https://user-images.githubusercontent.com/3039025/146126829-80c3aab6-56f1-4732-9f75-e6822843dd6c.png)

same command, but with -v
![image](https://user-images.githubusercontent.com/3039025/146126896-a07be36b-25c2-48ee-8028-0071585606ec.png)

NOTE: my IDE indicates an error with red font.

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.0.1
 - Scanner Version 2.5.1

"Workaround": add deprecated flag "-v"

"Urgency": How severe is this problem?  "Not business-stopping".

**Comment by ranekere-sfdc** [comment]
Thanks @Kamilsz  for logging an issue. 

I was able to verify that `--severity-threshold=3` is working for me. @salesforce/sfdx-scanner 2.12.0 is the version I have.

Is it possible that your command has a typo? I see in your description `--severity-treshold=3` is missing an h

**Comment by Kamilsz** [comment]
Hi,

You were right, it was a typo. My mistake, thanks for your help!

Kind regards,
Kamil
