### ISSUE TITLE
[BUG] JavaScript heap out of memory while invoking RetireJS engine

### ISSUE THREAD

**Issue by rmohan20** [forcedotcom/sfdx-scanner#570]
**Describe the bug**
CLI Scanner runs into this error while invoking RetireJS engine:
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

**To Reproduce**

```
sfdx scanner:run --engine retire-js --target <target_dir>
```

**Environment**
 - OS: [OSx, Linux, Windows]
 - Scanner Version [2.12.0]
 - Node Version [16.13.1]

**Workaround**
No known workaround yet

**Comment by ranekere-sfdc** [comment]
We are currently experiencing this issue due to a dependency that Retire-JS has on a broken version of Colors. Details on the retire-js issue [here](https://github.com/RetireJS/retire.js/issues/358)

**Comment by ranekere-sfdc** [comment]
The broken version of Colors has been unpublished. This issue can be resolved by uninstalling and re-installing the scanner plugin.

```
$sfdx plugins:uninstall @salesforce/sfdx-scanner

$sfdx plugins:install @salesforce/sfdx-scanner 

```
