### ISSUE TITLE
update to use PMD v6.40 or higher?

### ISSUE THREAD

**Issue by denverquentin** [forcedotcom/sfdx-scanner#575]
**Is your feature request related to a problem? Please describe.**
We're using the sfdx-scanner plugin to run PMD Apex rules during our CI/CD process in GitHub Actions. Our Apex code is used in a managed package listed on the AppExchange so the `ApexCRUDViolation` rule is very useful to us. I noticed that this rule has new `AuthMethodPattern` properties as of v6.40 - https://github.com/pmd/pmd/releases/tag/pmd_releases%2F6.40.0 that we would love to use. The problem is the sfdx-scanner only supports PMD v6.38 per your documentation - https://forcedotcom.github.io/sfdx-scanner/en/architecture/architecture/

**Describe the solution you'd like**
Is it possible to upgrade sfdx-scanner to use PMD v6.40 or higher? What would the timeline be for this?

**Describe alternatives you've considered**
Try to install the latest PMD Apex library in some custom way for the sfdx-scanner plugin to use.

**Additional context**
Thanks for your hard work on this project - it's been really easy to configure and use!

**Comment by ranekere-sfdc** [comment]
@denverquentin We are planning a release later this month to upgrade the PMD engine. I'll update this thread when the plugin is upgraded.

**Comment by denverquentin** [comment]
@ranekere-sfdc thanks for the quick turn-around! Much appreciated.

**Comment by ranekere-sfdc** [comment]
@denverquentin we released a new version of the plugin yesterday and it has PMD 6.42.0. Could you please upgrade? 

I'll mark this issue closed, pls feel free to open a new one if you need.

**Comment by denverquentin** [comment]
@ranekere-sfdc works great - thanks!
