### ISSUE TITLE
[BUG] Cannot find Config.json after installing sfdx-scanner in an Ubuntu machine

### ISSUE THREAD

**Issue by jorgesolebur** [forcedotcom/sfdx-scanner#581]
**Describe the bug**
After installing sfdx + sfdx-scanner plugins in an Ubuntu Machine, I cannot find the Config.json file that should be located in /.sfdx-scanner/ folder. I need to update this JSON file to define the targetted files for the scan

**To Reproduce**
I have an Ubuntu machine (running form a Docker ubuntu:latest image)
I have installed the Salesforce CLI from wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz and have update it (sfdx update)
I have installed sfdx-scanner as a sfdx plugins (sfdx plugins:install @salesforce/sfdx-scanner)
After installation I have tested few sfdx-scanner commands and they are running fine
I try to find for .sfdx-scanner folder (find / -name sfdx-scanner) or try to find all config.json files (find / -iname Config.json) but did not find any Config.json file in a sfdx-scanner folder. 

**Expected behavior**
I should be able to find Config.json file created from the sfdx-scanner plugins installation so I can edit it

**Screenshots**
Results from find / -iname Config.json:
<img width="1374" alt="Screenshot 2022-02-14 at 7 11 52 AM" src="https://user-images.githubusercontent.com/31279773/153779476-9c254796-2e99-4377-829f-fd846ffba1af.png">

**Desktop (please complete the following information):**
 - Ubuntu:latest image from Docker (using 20.04.3 LTS (Focal Fossa))
 - Scanner Version 2.12.0

**Additional context**

"Workaround": Have you found any ways to sidestep the problem? Not yet

**Comment by jfeingold35** [comment]
Hi @jorgesolebur .
From your stacktrace, it looks like you may be looking in the wrong place. The `.sfdx-scanner` directory is created in your home directory, and you seem to be in SFDX's `node_modules` directory. Can you please check your home directory and let us know if the folder and file are present?

**Comment by jorgesolebur** [comment]
Thanks @jfeingold35 , thanks for your response ! I am not an expert on Linux, but as far as I learn from the command 
**find / -iname Config.json** it should display all the files Config.json located in the computer, no matter where I am located. Agree? 

If I look into my home folder it seems to be empty:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/31279773/153899159-de7c505f-f91d-44c6-8810-57ce51ff69e9.png">
(even if I use ls -a to list hidden files). 

Also running **find $HOME -name "Config.json"** does not return any results: 
<img width="816" alt="image" src="https://user-images.githubusercontent.com/31279773/153900685-005e0c4a-2095-47eb-93fb-49c82199e24c.png">

Any help? Maybe I am doing something very stupid. SFDX is installed:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/31279773/153900889-ef3b625b-0634-4a85-bdbb-293a3fbcc19c.png">

**Comment by jorgesolebur** [comment]
I can create an image from my container and share it with you if that might help

**Comment by jfeingold35** [comment]
@jorgesolebur , so it looks like there's two things happening here.
First, the `$HOME` directory likely isn't `/home`, which is why running `ls -a` from within that directory didn't return any meaningful results. You can discern the actual value with `echo $HOME`.
Second, the `.sfdx-scanner` folder is a hidden folder, so you'd need to include the `-a` flag in your command, e.g. `ls -a $HOME`.
Alternatively, if you do `ls -lt $HOME/.sfdx-scanner`, it should display the contents of the `.sfdx-scanner` folder, including the `Config.json` file. Please try that and let us know if it works.
Thanks!

**Comment by jorgesolebur** [comment]
@jfeingold35 , thanks for your guidance and help, I really appreciate !
So I have followed your steps:

1. Execute  `eco $HOME` -> Result is **/root**
2. I go to /root with `cd /root`
3. From there I do a `ls -a`. I can find .sfdx folder but not .sfdx-scanner folder: 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/31279773/153995804-bbbf09ca-ed22-48ea-bd88-7cdc36f831a0.png">
It seems .sfdx-scanner is not in HOME folder

4. I try your other command `ls -lt $HOME/.sfdx-scanner` : 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/31279773/153995980-e4490312-94cb-44a0-b73a-55285a2d24c8.png">
which confirms that .sfdx-scanner folder is not in $HOME

5. Is there any other way to find the .sfdx-scanner folder? The user I used to install sfdx:scanner in this container is the same one as I am using right now while executing the commands, so do not think it is a user permission issue

**Comment by jfeingold35** [comment]
@jorgesolebur , are you using fresh containers each time? The most likely reason that the `.sfdx-scanner` folder wouldn't exist is if you haven't yet run a command that creates it.
After installing the plugin, can you run `sfdx scanner:rule:list` and then run `ls -lt $HOME/.sfdx-scanner`?

**Comment by jorgesolebur** [comment]
@jfeingold35  thanks a lot ! Indeed after runnning a sfdx command I can finally view and edit Config.json! Everything is working fine ! I will take that into account in my CI, to execute the command before updating Config.json.
Thanks again for your support, really really appreciate !! :-)
