### ISSUE TITLE
[BUG] sfdx-scanner install/update fail - broken URL

### ISSUE THREAD

**Issue by firatesmer** [forcedotcom/sfdx-scanner#613]
Hi,

A couple of hours ago I realized my GitHub action that runs static code analyze on the code failed on `install @salesforce/sfdx-scanner` step. Then I tried to update `sfdx-scanner` plugin on my local machine through Salesforce CLI but it again failed.

This is the error message I received on Salesforce CLI.
`Error: HTTP Error 404 for GET https://developer.salesforce.com/channels/@salesforce/sfdx-scanner/win32-x64`

I see that URL throws error 404 therefore CLI is not able to download `sfdx-scanner plugin`.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/15785611/160100881-5b1528e3-e226-4eb3-a48d-31906b874ba5.png">

**Comment by jfeingold35** [comment]
Thanks for bringing this to our attention. Can you confirm that you are, in fact, running a Win32 OS? Just want to rule out the obvious.

**Comment by firatesmer** [comment]
It's 64-bit.

**Comment by jfeingold35** [comment]
Thanks.
We have a GHA that runs on an interval to verify the plugin's availability, and that hasn't detected any issues. Can you please give us a bit more information about the commands that you were running, and the full output? We don't have quite enough information to start chasing this down yet.

**Comment by firatesmer** [comment]
Hi again,

First of all, I shared a wrong error message but it was failing at that time and this is the original output taken from my GitHub action.

Also, now, it is working as expected and I literally did nothing. I believe we can close the issue since it is working.

```
Run sfdx plugins:install @salesforce/sfdx-scanner
  sfdx plugins:install @salesforce/sfdx-scanner
  shell: /usr/bin/bash -e {0}
Successfully validated digital signature for @salesforce/sfdx-scanner.
Finished digital signature check.
Installing plugin @salesforce/sfdx-scanner... yarn add v1.22.10
Installing plugin @salesforce/sfdx-scanner... info No lockfile found.Installing plugin @salesforce/sfdx-scanner... [1/4] Resolving packages...Installing plugin @salesforce/sfdx-scanner... [2/4] Fetching packages...Installing plugin @salesforce/sfdx-scanner... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin @salesforce/sfdx-scanner... failed
warning @salesforce/sfdx-scanner > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning @salesforce/sfdx-scanner > @salesforce/eslint-config-lwc > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning @salesforce/sfdx-scanner > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @salesforce/sfdx-scanner > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @salesforce/sfdx-scanner > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning @salesforce/sfdx-scanner > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
error isbinaryfile@4.0.9: The engine "node" is incompatible with this module. Expected version ">= 14.0.0". Got "12.18.3"
error Found incompatible module.
    Error: yarn add @salesforce/sfdx-scanner@latest --non-interactive 
    --mutex=file:/home/runner/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/home/runner/.cache/sfdx/yarn --check-files 
    exited with code 1
Error: Process completed with exit code 1.
```
