### ISSUE TITLE
[BUG]  Java version  not supported. Please install Java 1.8 or later in MacOS

### ISSUE THREAD

**Issue by akhilanil2007** [forcedotcom/sfdx-scanner#625]
**Describe the bug**
I have java installed in my system, yet when I install and run this plugin, it gives me the error "Java version  not supported. Please install Java 1.8 or later."

**To Reproduce**
Install the plugin in a MacOS with version 10.15.7 and try running the scan for the workspace. 

**Expected behavior**
A CSV output should be generated with the identified violations

**Desktop:**
 - MacOS version - 10.15.7
 - Scanner Version - 2.13.1

"Workaround": No workaround available. I have tried setting the javaHome variable to "/Library/Java/JavaVirtualMachines/jdk-18.jdk/Contents/Home" location in the Config.js and can confirm that's the correct location of my java installation.

"Urgency": Unable to configure this on our CI/CD pipeline due to this issue

**Comment by rmohan20** [comment]
Hi @akhilanil2007 - am I correct in understanding you are using jdk18? Could you please share the output of `java -version` on your machine so we can use it as a reference?

Also, as a workaround, could you switch to an older version such as Java11 and check if the problem gets resolved?

**Comment by johnbelosf** [comment]
No further update here - please open a new issue if this is still a problem
