### ISSUE TITLE
[BUG] SFDX scanner Issue [TypeError: Cannot read properties of undefined (reading 'prototype')]

### ISSUE THREAD

**Issue by saileshkhadka** [forcedotcom/sfdx-scanner#804]
We are getting TypeError: Cannot read properties of undefined (reading 'prototype') while running sfdx scanner plugin. 
Previously, it works fine and recently we updated to latest pilot version using `sfdx plugins:install @salesforce/sfdx-scanner@latest-pilot`. After that we faced the error and revert back to previous stable version uninstalling pilot version using `sfdx plugins:install @salesforce/sfdx-scanner`, it installed the scanner version of 2.13.8 
sfdx version : sfdx-cli/7.164.2 linux-x64 node-v16.17.0

**To Reproduce**
we run the scanner command i.e.
`sfdx scanner:run --engine retire-js --pmdconfig ./.pmdruleset.xml --format html --target delta -o abc.html --severity-threshold 2`
after that we got an error 
**TypeError: Cannot read properties of undefined (reading 'prototype')**

**Expected behavior**
We are expecting to have an output like 
![image](https://user-images.githubusercontent.com/26744853/185611098-fdfae584-88f1-4850-aa2b-175feff16ebc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS 
 - Scanner Version : salesforce/sfdx-scanner 2.13.8
 - sfdx version : sfdx-cli/7.164.2 linux-x64 node-v16.17.0

"Workaround": 
Tried re-installing and updating sfdx cli version and scanner plugin but still getting same issue.

"Urgency": It was in high priority. We are having issue in getting scanning reports.

**Comment by rmohan20** [comment]
@saileshkhadka Thank you for reporting the issue. We’ll look into this problem and attempt to repro it.

I notice that your command individually invokes retire-js engine, but also provides —pmdconfig, which is specific for pmd. Could you help me understand the intention?

Also, -o (—outfile) and —format could be redundant when used together. —outfile can determine the format based on the provided file name’s extension. 

Might be worth retrying with using only one of —pmdconfig or —engine retire-js, and only one of —format or -o.

In the meantime, if the suggestions above don’t work, to temporarily unblock, could you install the previous versions please?
Pilot version:
sfdx plugins:install @salesforce/sfdx-scanner@3.3.0
Stable version:
sfdx plugins:install @salesforce/sfdx-scanner@2.13.7

Thanks.

**Comment by saileshkhadka** [comment]
Thanks it worked now using the stable version of sfdx-scanner !

**Comment by jfeingold35** [comment]
Hi @saileshkhadka .
We wanted to check in and see whether this issue is still reproducible in the most recent version of the pilot. If possible, would you mind upgrading to `lateset-pilot` again and attempting to reproduce? If the issue still occurs, could you please provide us with a little more information about your set-up, so we can attempt to reproduce it internally?
Thanks!
