### ISSUE TITLE
[BUG] Winter 22 Assert classes are not considered when scanning for PMD.ApexUnitTestClassShouldHaveAsserts rule

### ISSUE THREAD

**Issue by jamessimone** [forcedotcom/sfdx-scanner#836]
**Describe the bug**

Scanner currently reports false positives for `PMD.ApexUnitTestClassShouldHaveAsserts` rule when a test method uses the new `Assert` class.

**To Reproduce**

Create a unit test that calls any `Assert` class method instead of the corresponding `System` assert methods.

**Expected behavior**

Test methods should not be flagged as being in violation of this rule when using the new `Assert`

**Desktop (please complete the following information):**
 - OS: Windows
 - Scanner Version: repro'd on `v3.5.1` and `v2.13.8`

**Comment by jamessimone** [comment]
Seems like this has already been fixed upstream - if we upgrade PMD to `6.49.0` this should fix this issue (a la the `6.48.0` upgrade [here](https://github.com/forcedotcom/sfdx-scanner/commit/cfdb936b9443e86d7049633b4dbaff83b1f793f3)).

**Comment by jamessimone** [comment]
@jfeingold35 I see this is already going to be taken care of in W-11689621 - happy to keep this open or close, up to you. Thanks!

**Comment by jfeingold35** [comment]
@jamessimone , I'm happy to leave this open and pinned until such time as we release a version including PMD >= 6.49.

**Comment by jfeingold35** [comment]
@jamessimone , the release of v3.6.2 updates PMD to 6.50.0, which resolves this issue. As such, I'll be closing it at this point.

**Comment by jamessimone** [comment]
Thank you!
