### ISSUE TITLE
List command - INTERNAL ERROR: Unexpected error occurred while cataloging rules: null

### ISSUE THREAD

**Issue by wkuehler** [forcedotcom/sfdx-scanner#882]
I am trying to create a custom rule that would allow me to flag methods with a CyclomaticComplexity of 5 or greater.  After a few `scanner:rule:add` commands trying to add my new custom rule, I must have made a mistake because now the list command is throwing an error.  Previously when i ran:

`scanner:rule:list`

I was getting the full list of rules, but I am now receiving the following:

```
INTERNAL ERROR: Unexpected error occurred while cataloging rules: null.
Please log an issue with us at github.com/forcedotcom/sfdx-scanner.
ERROR running scanner:rule:list:  Please see error details displayed above.
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Scanner Version 3.6.2

**Comment by rmohan20** [comment]
Hi @wkuehler - thanks for checking with us.
Sounds like removing the custom rule might help to fix the list command. `scanner:rule:remove` command ([related doc](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/scanner-commands/remove/)) can do this for you.

Please do let us know if this unblocks you. Thanks!

**Comment by wkuehler** [comment]
Hi @rmohan20, when i try to remove the existing rules, i am presented with the same error.

Command
`sfdx scanner:rule:remove --path ".\sfdx-scanner\design\apex\CyclomaticComplexity_custom.xml"`

Result
`INTERNAL ERROR: Unexpected error occurred while cataloging rules: null. Please log an issue with us at github.com/forcedotcom/sfdx-scanner.
ERROR running scanner:rule:remove:  Please see error details displayed above.`

**Comment by wkuehler** [comment]
Even running a run command now results in this error:

Command
`sfdx scanner:run -t .\force-app\main\default\classes\PTOHelper.cls --format=html > results.html`

**Comment by jfeingold35** [comment]
@wkuehler , please try the following steps. One of them should be able to clear up the problem.
1. First, you can manually remove the rules in question by editing the `~/.sfdx-scanner/CustomPaths.json`.
2. If that doesn't work, you can delete the `~/.sfdx-scanner/CustomPaths.json` file altogether.
3. If that doesn't work either, you can just delete the entire `~/.sfdx-scanner` folder.
Please give this a shot and let us know whether it unblocks you.
Thanks!

**Comment by wkuehler** [comment]
Thanks @jfeingold35, option 2 worked and i am able to run commands again.  Thanks for the help!
