### ISSUE TITLE
[Question] Can the DFA detect CRUD/FLS using all forms of schema checking?

### ISSUE THREAD

**Issue by sirephil** [forcedotcom/sfdx-scanner#883]
We have a utility class that has various methods that accept `DescribeObjectResult` and `DescribeFieldResult` parameters or array parameters and this utility performs the various checks.

I saw the demo by John Belo and Roopa Mohan where I could see the DFA was able to do this with strings. I simply want to understand if it also handles `SObjectType`, `SObjectField`, `DescribeObjectResult` and `DescribeFieldResult` instances or instance arrays.

**Comment by rmohan20** [comment]
Hi @sirephil - thanks for your question.
Graph Engine can understand and handle `SObjectType`, `SObjectField`, `DescribeObjectResult`, `DescribeFieldResult`, and `FieldSet` objects. However, we recently noticed a bug with handling method calls that have one of these Schema library objects as a parameter. We'll be pushing a fix for this in the upcoming minor release.

**Comment by sirephil** [comment]
Thanks @rmohan20. Does that work regardless as to how these are passed (such as in a list, set or even an Apex [POTATO](https://twitter.com/ca_peterson/status/1100481781537468417?s=20))?

**Comment by sirephil** [comment]
Thanks. Will do.
