### ISSUE TITLE
Scanner does not show up in sfdx commands after installation

### ISSUE THREAD

**Issue by Szandor72** [forcedotcom/sfdx-scanner#89]
Hello, 

On my win machine with node 13 and current DX CLI I tried the installation and no apparent errors were thrown. 

```
sfdx plugins:install scanner
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning "@salesforce/lwc-dev-server > @webruntime/compiler > @lwc/rollup-plugin@1.0.2-222.18" has incorrect peer dependency "@lwc/engine@1.0.x".
warning "sfdx-migration-automatic > @oclif/command@1.5.20" has unmet peer dependency "@oclif/plugin-help@^2".
Installing plugin scanner... !
```
After that

`sfdx scanner` is not recognized. I get `»   Warning: scanner:run is not a sfdx command.`

`sfdx commands` shows all my other plugins but not the scanner. 

PS: 
love the idea to intergrate salesforce security scans into our ci process bundled with pmd in a handy plugin.

**Comment by michaelhoefer** [comment]
Hello @Szandor72, thanks for reporting this.  That certainly should not be happening.  Couple questions:

1. Is the plugin listed as installed when you run sfdx plugins?
2. Can you see if anything of interest is dumped out (sorry, it is a lot of output) when you run sfdx plugins:install @salesforce/sfdx-scanner --verbose?
3. What JDK do you have installed locally, if any?  If you do, do you have a JAVA_HOME set?  The installer should tell you if it cannot find a JVM and ask you to install one, but something could be going wrong there with the version you have...

We'll get this figured out.  Thankfully this is the first time we've heard of an issue with install...

@rmohan20 FYI.

**Comment by michaelhoefer** [comment]
Following up quickly, we just noticed that your original install command is wrong.  Make sure you install our plugin: sfdx plugins:install **@salesforce/sfdx-scanner**

We don't know what sfdx plugins:install scanner will do...that would be a different plugin...

**Comment by Szandor72** [comment]
Thanks for pointing me to the solution. Installation with `sfdx plugins:install @salesforce/sfdx-scanner` worked and it now shows up as expected in the command list. 

May I suggest to update the Readme - I wrongly guessed the name for the dev/npm instructions.

**Comment by michaelhoefer** [comment]
Will do.  Looking forward to improving and expanding this.  Just the tip of the iceberg now.
