### ISSUE TITLE
[BUG] SObjectType.My_Obj__c is not recognized as a DescribeSObjectResult type

### ISSUE THREAD

**Issue by mfrenchlitify** [forcedotcom/sfdx-scanner#890]
**Describe the bug**
We are receiving a CRUD Delete false positive when using isDeletable at the beginning of a function. 

We get the following violation note:
`CRUD validation is missing for [DELETE] operation on [My_Obj__c]`

**To Reproduce**
The following code produces a CRUD Delete violation even though it should be secure 
```
    @AuraEnabled
    public static void deleteMyObj(String objId){
        if (SObjectType.My_Obj__c.isDeletable() == false){
            throw new AuraHandledException('User does not have access to delete My Objs');//exception here prevents code from advancing to delete operation
        }
        try{
            My_Obj__c mObj = new My_Obj__c();
            mObj=[select id from Volume_Based_discount_Tier__c where id=:VolumeBasedDiscountId LIMIT 1];//inefficiency noted
            if(mObj != null){
                delete mObj;//CRUD violation marked here
            }
        }
        catch(Exception ex){
            system.debug('Exception at delete obj '+ex);
        }
    }
```

**Expected behavior**
No violations reported

**Screenshots**

**Desktop (please complete the following information):**
`sfdx version` results:
```
sfdx-cli/7.174.0 darwin-x64 node-v16.17.1
```

scan command:
```
sfdx scanner:run:dfa --target "./force-app/main/default/classes/*.cls" --projectdir "./force-app/main/default/classes" -o "./scanresults.html" --sfgejvmargs "-Xmx4g"
```

OS:
Mac OS 12.5.1 (21G83)

**Comment by rmohan20** [comment]
Hi @mfrenchlitify - thanks for letting us know.
This helped us find that Graph Engine doesn't recognize `SObjectType.My_Obj__c` as an `SObjectType`. Replacing it with `Schema.SObjectType.My_Obj__c` might unblock you.
We are looking into fixing this in an upcoming minor release.
