### ISSUE TITLE
[BUG] Category negative filter not working

### ISSUE THREAD

**Issue by surbhitomar** [forcedotcom/sfdx-scanner#900]
When I am running below command it's not working but vise versa is working.

Working
sfdx scanner:run --target=C:\Software\VisualStudio_Code\Ofcom-Salesforce-Pilot\force-app\main\default\lwc\midContactLwc --format table --severity-threshold 3 --engine eslint-lwc --category 'problem'   **Category positive filter working**
__
Not working
sfdx scanner:run --target=C:\Software\VisualStudio_Code\Ofcom-Salesforce-Pilot\force-app\main\default\lwc\midContactLwc --format table --severity-threshold 3 --engine eslint-lwc --category '!layout'   **Category negative filter not working**

**Comment by jfeingold35** [comment]
Hi @surbhitomar .
Looks like this is an issue with how we filter rules. This seems to be isolated to ESLint and its derivatives, though, and PMD seems to be unaffected.
We'll log this and add it to our backlog, but in the meantime you should be able to work around it by using a custom ESLint config.
