### ISSUE TITLE
Question: Will scanner provide the same results as Checkmarx/Partner Security Portal

### ISSUE THREAD

**Issue by Szandor72** [forcedotcom/sfdx-scanner#92]
Hello, 

I am currently using `--category Security` to scan my codebase. 

What is the relation between the security scanner (customer / partner) and this plugin?

In other words: Will the results be the same and can I use this plugin instead of checkmarx' source scanner tool for my daily operations?

We'll be presenting this DX Plugin at [Virtual Dreamin](http://virtualdreamin.com/the-dynamic-dx-duo-presents-the-very-best-of-plugins-2020/) this weekend. Also, our (appero's) security scanner account is currently unusable, so if the answer is 'YES, exactly same results' you've helped us out a lot.

**Comment by ranekere-sfdc** [comment]
@Szandor72 the sfdx-scanner does NOT provide the same results as Checkmarx. As of now, it is a different rule base.
