### ISSUE TITLE
[BUG]   ENV  variable   is  not working 

### ISSUE THREAD

**Issue by antonsatskyi** [forcedotcom/sfdx-scanner#920]
**Describe the bug**
sfdx scanner:run --target src/main/default --env {"rules":{"no-unused-vars":"off"}

**To Reproduce**
sfdx scanner:run --target src/main/default --env {"rules":{"no-unused-vars":"off"}

**Expected behavior**
rule no-unused-vars is disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/98826005/208178956-bc4bf522-d89b-4eed-b822-21590690dd22.png)

**Desktop (please complete the following information):**
 -IOs

**Comment by jfeingold35** [comment]
Hi @antonsatskyi .
It looks like the JSON that you provided here is malformed. It's missing a trailing `}` character. Also, the whole thing should be wrapped in single-quotes so the analyzer receives it as a string.
But more importantly, this isn't how the `--env` flag is intended to be used. The intent is to change which environments are used when the analyzer runs an ESLint variant, to prevent that environment's unique syntax or global variables from causing compilation errors or false positives.
E.g., if your code used web workers, you could use `--env '{"worker": true}'` to include the global variables related to web workers. (ESLint has [its own documentation](https://eslint.org/docs/latest/user-guide/configuring/language-options#specifying-environments) of the available environments.)
To get your desired behavior, you'd want to create a `.eslintrc.json` file that enables/disables your desired rules, and provide that to the analyzer via the `--eslintconfig` flag.
Let me know if that helps.

**Comment by antonsatskyi** [comment]
> Hi @antonsatskyi . It looks like the JSON that you provided here is malformed. It's missing a trailing `}` character. Also, the whole thing should be wrapped in single-quotes so the analyzer receives it as a string. But more importantly, this isn't how the `--env` flag is intended to be used. The intent is to change which environments are used when the analyzer runs an ESLint variant, to prevent that environment's unique syntax or global variables from causing compilation errors or false positives. E.g., if your code used web workers, you could use `--env '{"worker": true}'` to include the global variables related to web workers. (ESLint has [its own documentation](https://eslint.org/docs/latest/user-guide/configuring/language-options#specifying-environments) of the available environments.) To get your desired behavior, you'd want to create a `.eslintrc.json` file that enables/disables your desired rules, and provide that to the analyzer via the `--eslintconfig` flag. Let me know if that helps.

oh  it was a typo 
i use 
--env {"rules":{"no-unused-vars":"off"}}
thanks  for reply
