### ISSUE TITLE
[BUG] Not able to run code scan in Staging environment. Error message is in attached screenshot.

### ISSUE THREAD

**Issue by Nupur-Gupta-Olympus** [forcedotcom/sfdx-scanner#933]
**Describe the bug**
Not able to run code scan in Sandbox. Error message is in attached screenshot.

**Screenshots**
Attached
<img width="1160" alt="1" src="https://user-images.githubusercontent.com/88093881/210362394-56d6f3b7-4f11-40ba-a569-cb56ff528b07.png">
![2](https://user-images.githubusercontent.com/88093881/210362409-d384244b-4949-4611-b804-7771244570e0.png)

"Workaround": No

"Urgency":  "Not business-stopping".

**Comment by jfeingold35** [comment]
Hi @Nupur-Gupta-Olympus . Could you please tell us what version of the analyzer you're using? (e.g., please run `sfdx plugins` and let us know what it tells you.)
Thanks!

**Comment by Nupur-Gupta-Olympus** [comment]
@salesforce/sfdx-scanner 3.7.1

**Comment by rmohan20** [comment]
@Nupur-Gupta-Olympus - thanks for reporting this issue. This has helped us identify a bug with Code Analyzer while handling a specific type of violation from RetireJs. We are hoping to get you a fix in the next few weeks. Will update here when we have more information.

**Comment by Nupur-Gupta-Olympus** [comment]
++ Balaji
________________________________
From: rmohan20 ***@***.***>
Sent: Tuesday, January 10, 2023 12:30 AM
To: forcedotcom/sfdx-scanner ***@***.***>
Cc: Nupur Gupta ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [forcedotcom/sfdx-scanner] Not able to run code scan in Staging environment. Error message is in attached screenshot. (Issue #933)


PLEASE NOTE: Please use caution when opening links and attachments in this message.


@Nupur-Gupta-Olympus<https://github.com/Nupur-Gupta-Olympus> - thanks for reporting this issue. This has helped us identify a bug with Code Analyzer while handling a specific type of violation from RetireJs. We are hoping to get you a fix in the next few weeks. Will update here when we have more information.

**Comment by jfeingold35** [comment]
@Nupur-Gupta-Olympus , as mentioned, we anticipate releasing a fix for this issue in the coming weeks, but in the meantime we do have some more information for you. It looks like the specific libraries capable of causing this outcome when scanned with RetireJS are `ember` with a version below `v0.9.7.1` and `jquery.dataTables` with a version below `v1.10.0`.
Could you please check whether either of those libraries are present in your project? If so, you should be able to unblock yourselves by updating those libraries to more recent versions.

**Comment by Nupur-Gupta-Olympus** [comment]
Can we skip these libraries instead of updating them during scan?
________________________________
From: Josh Feingold ***@***.***>
Sent: Wednesday, January 11, 2023 10:42 PM
To: forcedotcom/sfdx-scanner ***@***.***>
Cc: Nupur Gupta ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [forcedotcom/sfdx-scanner] Not able to run code scan in Staging environment. Error message is in attached screenshot. (Issue #933)


PLEASE NOTE: Please use caution when opening links and attachments in this message.


@Nupur-Gupta-Olympus<https://github.com/Nupur-Gupta-Olympus> , as mentioned, we anticipate releasing a fix for this issue in the coming weeks, but in the meantime we do have some more information for you. It looks like the specific libraries capable of causing this outcome when scanned with RetireJS are ember with a version below v0.9.7.1 and jquery.dataTables with a version below v1.10.0.
Could you please check whether either of those libraries are present in your project? If so, you should be able to unblock yourselves by updating those libraries to more recent versions.

**Comment by jfeingold35** [comment]
`ember@<0.9.7.1` and `jquery.dataTables@<1.10.0` are both over 7 years old, and RetireJS shows that both are affected by multiple high severity security issues. So if possible, your best option really is to update to a more recent version of the libraries in question. Is that not an option in this case?

**Comment by jfeingold35** [comment]
Closing this issue, as it will be resolved by the upcoming `3.9.0` release.
