### ISSUE TITLE
[BUG] Specifying a target path that contains escape characters doesn't work

### ISSUE THREAD

**Issue by gadamson-upco** [forcedotcom/sfdx-scanner#952]
**Describe the bug**
If the path value provided to `--target` contains characters that need escaping, like spaces, parenthesis, etc, sfdx-scanner does not appear to resolve the path correctly. The scanner will return 0 issues. Quoting the path (either with or without the escapes) does not resolve the issue

**To Reproduce**
1. Create two directories that contain the same org source, where the code is known to have at least one issue. Name the directories `test` and `test (1)`, or something similar.
2. Run `sfdx-scanner --target test/classes` (plus whatever other relevant flags) and note the results
3. Now run `sfdx-scanner --target test\ \(1\)/classes` and note those results

**Expected behavior**
sfdx-scanner resolves the path with the escape characters correctly, and presents the same results for both directories

**Screenshots**
<img width="805" alt="image" src="https://user-images.githubusercontent.com/6810264/212771747-f10ac4a1-fbd9-4e1d-b9fd-ec86912c3850.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Scanner Version: 3.7.1

**Additional context**
Issue was found as part of a scripted process where sfdx-scanner is part of a series of commands run on org metadata, but the issue exists when scanning interactively from the command line as well. The issue occurs with both pmd and eslint-lwc engines. Other engines were not tried.

**Workaround**
Renaming the directory, or changing directory into the source folder and then scanning with a target of `.` both sidestep the issue.

**Urgency**
Not business-stopping

**Comment by gadamson-upco** [comment]
FYI, I upgraded to v3.8.0, same results as with 3.7.1

**Comment by jfeingold35** [comment]
@gadamson-upco , thanks for bringing this to our attention. We've logged this as a bug and added it to our backlog.

**Comment by jfeingold35** [comment]
@gadamson-upco , in the meantime, we have the following information to hopefully help unblock you.
1. In general, you should wrap paths with spaces or special characters in double-quotes (single quotes for Windows), e.g., `--target "./test/classes/"`.
2. It looks like the specific problem here is that the parentheses are messing with [`globby`](https://www.npmjs.com/package/globby)'s pattern matching. Something similar would happen if you used curly brackets, exclamation points, or asterisks. As such, we advise against using those characters in your file/directory names.

Thanks!
