### ISSUE TITLE
[BUG] ERROR Cannot find module '/home/runner/.local/share/sfdx/node_modules/eslint/conf/eslint-recommended.js'

### ISSUE THREAD

**Issue by PreziosiRaffaele** [forcedotcom/sfdx-scanner#986]
**Describe the bug**
ERROR Cannot find module '/home/runner/.local/share/sfdx/node_modules/eslint/conf/eslint-recommended.js'

**To Reproduce**
Run command \
sfdx scanner:run --format sarif --target './**/*.cls' --engine=pmd --pmdconfig ruleset.xml --outfile 'apexScanResults.sarif'

**Expected behavior**
Rule violations were written to apexScanResults.sarif.

**Screenshots**
![image](https://user-images.githubusercontent.com/74841513/221417177-d42d0abe-f1af-4318-967d-063494b09f90.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Scanner Version: v3.9.0

**Additional context**
Friday 24/02/2023 same pipeline was working

"Workaround":  Removing the SFDX scanner from the pipeline
"Urgency": Highly beneficial

**Comment by rmohan20** [comment]
@PreziosiRaffaele - thanks for reporting. Pinning this issue for more visibility.

Looks like every user who needs to install `@salesforce/sfdx-scanner` plugin now is affected. Users who already have Code Analyzer setup in their environment should be safe.

Will add more information as I find it.

**Comment by nvuillam** [comment]
I have exactly the same error in MegaLinter (that embeds sfdx-scanner)

**Comment by vaibhavdangar-woolies** [comment]
Hi, please advise if we have any workaround, issue is impacting CICD?

**Comment by rmohan20** [comment]
Sorry for the delay. We have more clarity on the issue, but the fix is still pending.

The root cause is that eslint made a change to breakaway the [eslint-recommended config into its own dependency](https://github.com/eslint/eslint/pull/16844) in 8.35.0. This has caused the reference from Code Analyzer to this config to break.

A workaround would be to temporarily install from CI/CD, Salesforce CLI version 7.179.0, which somehow refers to an older version of eslint.

```
npm install -g sfdx-cli@7.179.0
```

Will update you with an ETA for the fix tomorrow morning.

**Comment by vaibhavdangar-woolies** [comment]
Hi @rmohan20 , Thanks for quick reply. I'll check on the workaround suggested.

**Comment by noerremark** [comment]
7.179.0 doesn't work for me :-( 

```
 ›   Warning: sfdx-cli update available from 7.179.0 to 7.188.1.
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
ERROR running scanner:run:  Cannot find module '/home/vsts_azpcontainer/.local/share/sfdx/node_modules/eslint/conf/eslint-recommended.js'
```

**Comment by vaibhavdangar-woolies** [comment]
> 7.179.0 doesn't work for me :-(
> 
> ```
>  ›   Warning: sfdx-cli update available from 7.179.0 to 7.188.1.
> WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
> ERROR running scanner:run:  Cannot find module '/home/vsts_azpcontainer/.local/share/sfdx/node_modules/eslint/conf/eslint-recommended.js'
> ```

correct, **same error**

**Comment by jkossoy** [comment]
We are having the same issue, our CI is broken because of this..

**Comment by constantine-prokopenko-vrp** [comment]
As temp workaround, I manually created file using latest version from the [eslint](https://github.com/eslint/eslint) repo.
Here is the [file](https://github.com/eslint/eslint/blob/main/packages/js/src/configs/eslint-recommended.js)

**Comment by Mikelsoma** [comment]
**We also have error !!**
![image](https://user-images.githubusercontent.com/36003472/221574286-c3919e14-ec4d-4dc3-90c2-2ce28fbcb8c1.png)

**Comment by johnbelosf** [comment]
Thank you all for bearing with us on this. We are working to issue a fix ASAP.

**Comment by rmohan20** [comment]
Update: the fix is ready. We are planning to make a release in the next few hours.

**Comment by rmohan20** [comment]
The fix is now available with the latest 3.10.0 version.
Thank you all for your patience - truly appreciate it!

**Comment by andreyshestakov-phsa** [comment]
The pligin now works fine, thanks!

**Comment by PreziosiRaffaele** [comment]
I can confirm that is working fine for me. Thank you for resolving this issue so quickly!

**Comment by nvuillam** [comment]
All good in [MegaLinter sfdx-scanner integration](https://megalinter.io/latest/descriptors/salesforce_sfdx_scanner_apex/) :)

**Comment by constantine-prokopenko-vrp** [comment]
Many thanks
Works fine for me

**Comment by noerremark** [comment]
Also confirmed fixed from us! Thanks for helping out...

**Comment by sameer544** [comment]
Work fine in our Azure DevOps pipeline. Thank you for the quick fix :)

**Comment by Esabilin** [comment]
Works for us, thanks!
