### ISSUE TITLE
[Azure DevOps Pipeline error || Cannot find module - share/sfdx/node_modules/eslint/conf/eslint-recommended.js ]

### ISSUE THREAD

**Issue by sameer544** [forcedotcom/sfdx-scanner#987]
**Describe the bug**
Getting ERROR running scanner:run:  Cannot find module '/home/vsts/.local/share/sfdx/node_modules/eslint/conf/eslint-recommended.js' in Azure DevOps pipeline.

**To Reproduce**
Step 1 - Create node.JS build YML pipeline on Azure DevOps
Step 2 - Create new job for scanning salesforce org code by running below command
 `sfdx scanner:run --target ./changed-sources --engine "eslint-lwc,pmd" --format table`

**Expected behavior**
Should provide violation report like mentioned in below image.
![image](https://user-images.githubusercontent.com/33362531/221583822-74d4b3ee-e8ac-44a8-9271-d1f8baa4f5b9.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/33362531/221584058-bbeb73f1-3a78-41d3-b6b9-20e5111d6118.png)

**Desktop (please complete the following information):**
 - OS: Azure DevOps VM Image ubuntu-latest
 - Scanner Version : v3.9.0

**Additional context**
Issue is only on Azure DevOps Pipeline level not on local machine.

"Workaround": Have you found any ways to sidestep the problem? No

"Urgency": Not business-stopping.

**Comment by johnbelosf** [comment]
hi @sameer544 thanks for raising this. We are working on this issue - please follow #986 and I'll close this as a duplicate in the meantime
