### ISSUE TITLE
[BUG] Cannot execute PMD scan with custom XML rules

### ISSUE THREAD

**Issue by tombone25** [forcedotcom/sfdx-scanner#992]
Calling scanner run command for pmd engine while specified any custom rules in custom rulesets results with unexpected error. Executing rule with PMD directly via IDE plugin works correctly:
![image](https://user-images.githubusercontent.com/18499974/221852310-be37e036-5d83-47fd-9156-c739b366b3bd.png)

**Steps to reproduce:**
1. Create custom ruleset with custom rule:
```
<?xml version="1.0" ?>
<ruleset name="Custom XML rules"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd"
>
    <description>Custom PMD ruleset for XML files</description>

    <rule name="NoUnderscoresInFieldNames"
          language="xml"
          message="Custom fields should not contain underscores."
          class="net.sourceforge.pmd.lang.rule.XPathRule"
    >
        <priority>3</priority>
        <properties>
            <property name="xpath">
                <value>
                    <![CDATA[
                        //CustomField/fullName/text[matches(@Image, ".*_.*__c")]
                    ]]>
                </value>
            </property>
        </properties>
    </rule>
</ruleset>
```
2. Add ruleset to scanner `sfdx scanner rule add -l xml -p ".\customRule.xml"`
3. Execute `sfdx scanner run --target ".\force-app\" --engine "pmd"`
4. Result output:
```
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
INTERNAL ERROR: Unexpected error occurred while cataloging rules: begin 0, end 3, length 0. Please log an issue with us at github.com/forcedotcom/sfdx-scanner.
ERROR running scanner:run:  Please see error details displayed above.
```

**Expected behavior**
I'm expecting list of violations

Version: @salesforce/sfdx-scanner 3.10.0

**Comment by johnbelosf** [comment]
Thank you for raising this - we will review ASAP

**Comment by tombone25** [comment]
@jfeingold35, I apologise for my ignorance and thank you for your time and help. I made a mistake on path setup which was generating an issue.
After correction I'm not getting an error, I'm able to add custom rules but still there is different results in comparison to local plugin. Target is same in both scans. If possible I would be grateful further instructions.
![image](https://user-images.githubusercontent.com/18499974/222072335-c861d737-6e2c-4ddc-8ee9-b87b932d4bc8.png)

**Comment by jfeingold35** [comment]
@tombone25 , glad we were able to resolve the error. If possible, could you please post the code snippet that you expect to throw a violation? If we have that, we can try to figure out why it's not doing that.

**Comment by tombone25** [comment]
@jfeingold35 
PMD scan:
`pmd --rulesets ".\category\xml\custom-xml.xml" --dir ".\force-app\main\default\objects\"`
Result:
```
.\force-app\main\default\objects\Account\fields\My_Field__c.field-meta.xml:2:   CustomFieldNamingConvention:    Incorrectly named field
.\force-app\main\default\objects\Account\fields\My_Field__c.field-meta.xml:3:   NoUnderscoresInFieldNames:      Custom fields should not contain underscores.
.\force-app\main\default\objects\Account\fields\chk_IsCandidate__c.field-meta.xml:3:    NoUnderscoresInFieldNames:      Custom fields should not contain underscores.
```

Scanner run:
`sfdx scanner run --target ".\force-app\main\default\objects\" --engine "pmd" `

Result: 
`Executed engines: pmd. No rule violations found.`

Expected result: list of violations same as from direct PMD scan

**Comment by jfeingold35** [comment]
@tombone25 , thanks! I'm seeing the behavior on my end as well. I'll get back to you once I've figured out the problem.

**Comment by jfeingold35** [comment]
@tombone25 , I believe I've figured out the problem. Please check the analyzer's config file, which lives in `~/.sfdx-scanner/Config.json`, and take a look at the `targetPatterns` array for PMD's `engines` entry.
By default, the configuration has an exclusion pattern, `!**/*-meta.xml`, which causes files ending in `-meta.xml` to be ignored. If you want those files to be included, you can either remove this exclusion pattern or modify it to be more lax.
Let us know if that works for you.

**Comment by tombone25** [comment]
@jfeingold35 thank you very much for your assistance, changing config file fixed my problem.
