### ISSUE TITLE
[BUG] - Error when running any command: Only json and js message files are allowed, not .md

### ISSUE THREAD

**Issue by denford** [forcedotcom/sfdx-scanner#998]
**Describe the bug**
Running any scanner command just returns an error message "Error: Only json and js message files are allowed, not .md"

**To Reproduce**
1. Install jdk 11 (have also tried jdk 17), and salesforce cli
2. Install the scanner
3. Run any scanner command (e.g. sfdx scanner:run, sfdx scanner:rule:list) and the only output on the cli is the error message above

**Expected behavior**
Expect the commands to run

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1 (M1 macbook pro)
 - Scanner Version 3.10.0

"Workaround": Have you found any ways to sidestep the problem?
No workaround

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".
Business stopping

**Comment by jfeingold35** [comment]
@denford , I'm unable to reproduce this. Could you check whether this occurs with all plugins or just the scanner? If it just happens with the scanner, can you please post the exact install steps you did?

**Comment by denford** [comment]
@jfeingold35 - thanks for the reply. Interesting, I can run the --help commands for plugins, but you're right, I can't run "executing" commands for other plugins either...must be my environment, i'll try uninstalling plugins and cli and re-installing

**Comment by denford** [comment]
update: uninstalling plugin and reinstalling seemed to work
